<?php
declare(strict_types=1); require __DIR__.'/bootstrap.php'; $me=sf_admin_require_auth(true);
if(($_SERVER['REQUEST_METHOD']??'')!=='POST')sf_json_response(['ok'=>false,'error'=>'method_not_allowed'],405);
$body=sf_request_json();$batch=sf_admin_slug((string)($body['batch_id']??''),'');$templateId=sf_admin_slug((string)($body['template_id']??''),'');$release=sf_clean_text($body['release']??'Unreleased',180);$tracks=is_array($body['tracks']??null)?$body['tracks']:[];
if($batch===''||$templateId==='')sf_json_response(['ok'=>false,'message'=>'Batch and metadata template are required.'],422);$template=sf_admin_template($templateId);if(!$template)sf_json_response(['ok'=>false,'message'=>'Metadata template was not found.'],404);if(!$tracks)sf_json_response(['ok'=>false,'message'=>'There are no tracks to import.'],422);
$catalog=sf_catalog();$errors=[];$imported=[];$existingIsrc=[];foreach($catalog as $t){$x=(string)($t['metadata']['isrc']??'');if($x!=='')$existingIsrc[$x]=(string)($t['id']??'');}
$uploadDir=SF_ROOT.'/storage/imports/'.$batch.'/uploads';
$loadUpload=function(string $id)use($uploadDir,$batch){if(!preg_match('/^UP-[A-F0-9]{12}$/',$id))return null;$p=$uploadDir.'/'.$id.'.json';if(!is_file($p))return null;$d=json_decode((string)file_get_contents($p),true);return is_array($d)&&($d['batch_id']??'')===$batch?$d:null;};
foreach($tracks as $n=>$raw){
  if(!is_array($raw)){$errors[]='Invalid track row '.($n+1).'.';continue;}
  $title=sf_clean_text($raw['title']??'',180);if($title===''){$errors[]='Track '.($n+1).' needs a title.';continue;}
  $isrc=sf_admin_normalize_isrc($raw['isrc']??'');if(!sf_admin_isrc_valid($isrc)){$errors[]="$title has an invalid ISRC.";continue;}
  if($isrc!==''&&isset($existingIsrc[$isrc])){$errors[]="$title uses an ISRC already assigned to {$existingIsrc[$isrc]}.";continue;}
  $uploadIds=array_values(array_filter(array_map('strval',(array)($raw['upload_ids']??[]))));$masterId=(string)($raw['master_upload_id']??'');$previewId=(string)($raw['preview_upload_id']??'');
  $uploads=[];foreach($uploadIds as $uid){$u=$loadUpload($uid);if($u)$uploads[$uid]=$u;}if(!$uploads){$errors[]="$title has no uploaded files.";continue;}
  $master=$uploads[$masterId]??reset($uploads);$preview=$uploads[$previewId]??null;if(!$preview){foreach($uploads as $u)if(($u['extension']??'')==='mp3'){$preview=$u;break;}}if(!$preview)$preview=$master;
  $masterHash=(string)($master['sha256']??'');$existingIndex=null;foreach($catalog as $i=>$t)if(($t['metadata']['source']['master_sha256']??'')===$masterHash&&$masterHash!==''){$existingIndex=$i;break;}
  $baseId=sf_admin_slug($title,'track');$id=$existingIndex!==null?(string)$catalog[$existingIndex]['id']:$baseId;if($existingIndex===null){$used=array_column($catalog,'id');$k=2;while(in_array($id,$used,true))$id=$baseId.'-'.$k++;}
  try{$masterAsset=sf_media_register_existing_file((string)$master['stored_path'],(string)$master['original_name'],(int)$me['id']);$previewAsset=sf_media_register_existing_file((string)$preview['stored_path'],(string)$preview['original_name'],(int)$me['id']);sf_db()->prepare("UPDATE media_links SET role='audio_candidate',public_visible=0,updated_at=? WHERE entity_type='track' AND entity_id=? AND role='primary_audio'")->execute([gmdate('c'),$id]);sf_media_attach((int)$masterAsset['id'],'track',$id,'master_audio',['public_visible'=>false,'download_allowed'=>false]);sf_media_attach((int)$previewAsset['id'],'track',$id,'primary_audio',['public_visible'=>true,'download_allowed'=>false]);$publicRel='api/media.php?id='.rawurlencode((string)$previewAsset['uuid']);}catch(Throwable $mediaError){$errors[]="$title media registration failed: ".$mediaError->getMessage();continue;}
  $overrides=is_array($raw['overrides']??null)?$raw['overrides']:[];$metadata=sf_admin_merge_metadata($template,$overrides,$isrc,$batch,['master_sha256'=>$masterHash,'preview_sha256'=>(string)$preview['sha256'],'files'=>array_values(array_map(fn($u)=>['name'=>$u['original_name'],'relative_path'=>$u['relative_path'],'extension'=>$u['extension'],'size'=>$u['size'],'sha256'=>$u['sha256']],$uploads))]);
  if(($metadata['isrc_policy']??'')==='required_on_import'&&$isrc===''){$errors[]="$title requires an ISRC under this template.";continue;}
  $track=['id'=>$id,'title'=>$title,'duration'=>max(0,(int)round((float)(($previewAsset['duration_seconds']??0)>0?$previewAsset['duration_seconds']:($raw['duration']??0)))),'year'=>(int)($metadata['release_year']??0),'mood'=>sf_admin_array_strings($raw['mood']??[]),'themes'=>sf_admin_array_strings($raw['themes']??[]),'energy'=>max(1,min(5,(int)($raw['energy']??3))),'release'=>$release!==''?$release:'Unreleased','audio'=>$publicRel,'artwork'=>sf_clean_text(($raw['artwork']??'')!==''?$raw['artwork']:($metadata['album_cover']??''),300),'price'=>(float)($metadata['price']??2),'podEligible'=>(bool)($metadata['pod_eligible']??true),'lyrics'=>sf_clean_text($raw['lyrics']??'',10000),'credits'=>sf_admin_public_credits($metadata),'story'=>sf_clean_text($raw['story']??'',10000),'metadata'=>$metadata];
  if($existingIndex!==null)$catalog[$existingIndex]=$track;else$catalog[]=$track;if($isrc!=='')$existingIsrc[$isrc]=$id;$imported[]=['id'=>$id,'title'=>$title,'updated'=>$existingIndex!==null,'audio'=>$publicRel];
}
if($errors)sf_json_response(['ok'=>false,'errors'=>$errors,'imported'=>$imported],422);sf_admin_write_catalog($catalog);$summary=['schema'=>'stonefellow.import-batch.v1','batch_id'=>$batch,'template'=>['id'=>$template['id'],'name'=>$template['name'],'version'=>$template['version']],'release'=>$release,'imported'=>$imported,'completed_at'=>gmdate('c')];sf_write_json(SF_ROOT.'/storage/imports/'.$batch.'/finalized.json',$summary);sf_json_response(['ok'=>true,'batch'=>$summary,'catalog_count'=>count($catalog)]);
