<?php
declare(strict_types=1); require __DIR__.'/bootstrap.php';
if(($_SERVER['REQUEST_METHOD']??'GET')==='GET'){sf_admin_require_auth(false);$d=sf_admin_knowledge_index();sf_json_response(['ok'=>true,'knowledge'=>$d]);}
if(($_SERVER['REQUEST_METHOD']??'')!=='POST')sf_json_response(['ok'=>false,'error'=>'method_not_allowed'],405);sf_admin_require_auth(true);$b=sf_request_json();$a=(string)($b['action']??'');$d=sf_admin_knowledge_index();
if($a==='folder_create'){$name=sf_clean_text($b['name']??'',120);if($name==='')sf_json_response(['ok'=>false,'message'=>'Folder name is required.'],422);$id='KF-'.strtoupper(bin2hex(random_bytes(4)));$d['folders'][]=['id'=>$id,'name'=>$name,'created_at'=>gmdate('c'),'updated_at'=>gmdate('c')];sf_admin_write_knowledge($d);sf_json_response(['ok'=>true,'knowledge'=>$d]);}
if($a==='folder_rename'){$id=(string)($b['id']??'');$name=sf_clean_text($b['name']??'',120);foreach($d['folders'] as &$f)if(($f['id']??'')===$id){$f['name']=$name;$f['updated_at']=gmdate('c');}unset($f);sf_admin_write_knowledge($d);sf_json_response(['ok'=>true,'knowledge'=>$d]);}
if($a==='folder_delete'){$id=(string)($b['id']??'');$ids=[];foreach($d['files'] as $f)if(($f['folder_id']??'')===$id)$ids[]=(string)$f['id'];foreach($d['files'] as $f)if(in_array((string)($f['id']??''),$ids,true)&&!empty($f['stored_path']))@unlink(SF_ROOT.'/'.ltrim((string)$f['stored_path'],'/'));$d['files']=array_values(array_filter($d['files'],fn($f)=>(string)($f['folder_id']??'')!==$id));$d['folders']=array_values(array_filter($d['folders'],fn($f)=>(string)($f['id']??'')!==$id));sf_admin_write_knowledge($d);sf_json_response(['ok'=>true,'knowledge'=>$d]);}
if($a==='file_update'){$id=(string)($b['id']??'');foreach($d['files'] as &$f)if(($f['id']??'')===$id){if(array_key_exists('name',$b))$f['name']=sf_clean_text($b['name'],180);if(array_key_exists('folder_id',$b))$f['folder_id']=sf_clean_text($b['folder_id'],40);if(array_key_exists('public_agent',$b))$f['public_agent']=sf_admin_bool($b['public_agent']);if(array_key_exists('notes',$b))$f['notes']=sf_clean_text($b['notes'],2000);$f['updated_at']=gmdate('c');}unset($f);sf_admin_write_knowledge($d);sf_json_response(['ok'=>true,'knowledge'=>$d]);}
if($a==='file_delete'){$id=(string)($b['id']??'');foreach($d['files'] as $f)if(($f['id']??'')===$id&&!empty($f['stored_path']))@unlink(SF_ROOT.'/'.ltrim((string)$f['stored_path'],'/'));$d['files']=array_values(array_filter($d['files'],fn($f)=>(string)($f['id']??'')!==$id));sf_admin_write_knowledge($d);sf_json_response(['ok'=>true,'knowledge'=>$d]);}
if($a==='search'){$q=strtolower(sf_clean_text($b['query']??'',200));$hits=[];if($q!=='')foreach($d['files'] as $f){$hay=strtolower(implode(' ',[(string)($f['name']??''),(string)($f['notes']??''),(string)($f['text']??'')]));if(str_contains($hay,$q))$hits[]=['id'=>$f['id'],'name'=>$f['name'],'folder_id'=>$f['folder_id'],'type'=>$f['type'],'snippet'=>substr((string)($f['text']??$f['notes']??''),0,500),'public_agent'=>(bool)($f['public_agent']??false)];if(count($hits)>=20)break;}sf_json_response(['ok'=>true,'hits'=>$hits]);}
sf_json_response(['ok'=>false,'message'=>'Unsupported knowledge action.'],422);
