<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';$method=$_SERVER['REQUEST_METHOD']??'GET';$me=sf_admin_require_auth($method!=='GET');sf_media_ensure_schema();
if($method==='GET'){$entityType=sf_clean_text($_GET['entity_type']??'',40);$entityId=sf_clean_text($_GET['entity_id']??'',160);if($entityType!==''&&$entityId!=='')sf_json_response(['ok'=>true,'links'=>sf_media_links($entityType,$entityId),'capabilities'=>sf_media_capabilities()]);$category=sf_clean_text($_GET['category']??'',40);$q=sf_clean_text($_GET['q']??'',180);sf_json_response(['ok'=>true,'assets'=>sf_media_list($category,$q,500),'capabilities'=>sf_media_capabilities()]);}
if($method!=='POST')sf_json_response(['ok'=>false,'error'=>'method_not_allowed'],405);$b=sf_request_json();$action=(string)($b['action']??'');
try{
 if($action==='attach'){$links=sf_media_attach((int)($b['asset_id']??0),sf_clean_text($b['entity_type']??'',40),sf_clean_text($b['entity_id']??'',160),sf_clean_text($b['role']??'media',60),['featured'=>!empty($b['featured']),'public_visible'=>!empty($b['public_visible']),'download_allowed'=>!empty($b['download_allowed'])]);sf_log_admin_action((int)$me['id'],'media_attached','media_asset',(string)($b['asset_id']??0),['entity_type'=>$b['entity_type']??'','entity_id'=>$b['entity_id']??'','role'=>$b['role']??'']);sf_json_response(['ok'=>true,'links'=>$links]);}
 if($action==='detach'){$ok=sf_media_detach((int)($b['link_id']??0));sf_log_admin_action((int)$me['id'],'media_detached','media_link',(string)($b['link_id']??0));sf_json_response(['ok'=>$ok]);}
 if($action==='update_asset'){$a=sf_media_update_asset((int)($b['id']??0),(array)($b['asset']??[]));sf_log_admin_action((int)$me['id'],'media_metadata_updated','media_asset',(string)$a['id']);sf_json_response(['ok'=>true,'asset'=>$a]);}
 if($action==='update_link'){sf_media_update_link((int)($b['id']??0),(array)($b['link']??[]));sf_json_response(['ok'=>true]);}
 if($action==='delete_asset'){$id=(int)($b['id']??0);$ok=sf_media_delete_asset($id);if($ok)sf_log_admin_action((int)$me['id'],'media_deleted','media_asset',(string)$id);sf_json_response(['ok'=>$ok]);}
 if($action==='publish_track_audio'){$trackId=sf_clean_text($b['track_id']??'',160);$linkId=(int)($b['link_id']??0);$r=sf_media_publish_track_audio($trackId,$linkId);sf_log_admin_action((int)$me['id'],'track_primary_audio_published','track',$trackId,['asset_id'=>(int)$r['asset']['id'],'previous_audio'=>$r['previous_audio'],'duration'=>(float)$r['asset']['duration_seconds']]);if(function_exists('sf_agent_brain_log'))sf_agent_brain_log((int)$me['id'],'admin_media','media_publish',['route'=>'track_media','action'=>'publish_primary_audio','context_profile'=>'catalog','needs_llm'=>false,'requires_confirmation'=>true,'status'=>'completed','request'=>'Replace primary audio for '.$trackId,'response'=>'Published asset '.$r['asset']['uuid'].'; previous source preserved in audit metadata.']);sf_json_response(['ok'=>true]+$r);}
 if($action==='publish_track_artwork'){$trackId=sf_clean_text($b['track_id']??'',160);$linkId=(int)($b['link_id']??0);$r=sf_media_publish_track_artwork($trackId,$linkId);sf_log_admin_action((int)$me['id'],'track_primary_artwork_published','track',$trackId,['asset_id'=>(int)$r['asset']['id'],'previous_artwork'=>$r['previous_artwork']]);if(function_exists('sf_agent_brain_log'))sf_agent_brain_log((int)$me['id'],'admin_media','media_publish',['route'=>'track_media','action'=>'publish_primary_artwork','context_profile'=>'catalog','needs_llm'=>false,'requires_confirmation'=>true,'status'=>'completed','request'=>'Replace primary artwork for '.$trackId,'response'=>'Published artwork asset '.$r['asset']['uuid'].'.']);sf_json_response(['ok'=>true]+$r);}
 sf_json_response(['ok'=>false,'error'=>'unknown_action'],400);
}catch(Throwable $e){sf_json_response(['ok'=>false,'message'=>$e->getMessage()],422);}
