<?php
declare(strict_types=1); require __DIR__.'/bootstrap.php';
if(($_SERVER['REQUEST_METHOD']??'GET')==='GET'){sf_admin_require_auth(false);sf_json_response(['ok'=>true,'releases'=>sf_admin_releases()]);}
if(($_SERVER['REQUEST_METHOD']??'')!=='POST')sf_json_response(['ok'=>false,'error'=>'method_not_allowed'],405);
sf_admin_require_auth(true);$b=sf_request_json();$action=(string)($b['action']??'save');$rows=sf_admin_releases();
if($action==='delete'){$id=sf_admin_slug((string)($b['id']??''),'');$rows=array_values(array_filter($rows,fn($r)=>(string)($r['id']??'')!==$id));sf_admin_write_releases($rows);sf_json_response(['ok'=>true]);}
$raw=is_array($b['release']??null)?$b['release']:[];$title=sf_clean_text($raw['title']??'',180);if($title==='')sf_json_response(['ok'=>false,'message'=>'Release title is required.'],422);$id=sf_admin_slug((string)($raw['id']??$title),'release');$idx=null;foreach($rows as $i=>$r)if((string)($r['id']??'')===$id){$idx=$i;break;}$old=$idx===null?[]:$rows[$idx];
$state=(string)($raw['state']??($old['state']??'draft'));if(!in_array($state,['draft','review','scheduled','published','archived'],true))$state='draft';
$catalog=sf_catalog();$trackMap=[];foreach($catalog as $t)if(!empty($t['id']))$trackMap[(string)$t['id']]=$t;
$trackIds=[];foreach((array)($raw['track_ids']??[]) as $tid){$tid=sf_clean_text($tid,100);if($tid===''||in_array($tid,$trackIds,true))continue;if(!isset($trackMap[$tid]))sf_json_response(['ok'=>false,'message'=>'Unknown catalog track: '.$tid],422);$trackIds[]=$tid;}
$featured=sf_clean_text($raw['featured_track_id']??'',100);if($featured!==''&&!in_array($featured,$trackIds,true))sf_json_response(['ok'=>false,'message'=>'Featured track must belong to this release.'],422);
$inheritedCover='';if($trackIds){$ct=$trackMap[$trackIds[0]]??[];$inheritedCover=(string)($ct['artwork']??($ct['metadata']['album_cover']??''));}
$credits=[];foreach((array)($raw['credits']??[]) as $credit){$credit=sf_clean_text($credit,300);if($credit!==''&&!in_array($credit,$credits,true))$credits[]=$credit;if(count($credits)>=100)break;}
$ra=is_array($raw['archive']??null)?$raw['archive']:[];$archive=['era'=>sf_clean_text($ra['era']??'',180),'edition'=>sf_clean_text($ra['edition']??'',180),'original_release_date'=>sf_clean_text($ra['original_release_date']??'',20),'reissue_of'=>sf_clean_text($ra['reissue_of']??'',100),'media'=>[]];
if($archive['reissue_of']===$id)sf_json_response(['ok'=>false,'message'=>'A release cannot be a reissue of itself.'],422);
if($archive['reissue_of']!==''){$found=false;foreach($rows as $rr)if((string)($rr['id']??'')===$archive['reissue_of']){$found=true;break;}if(!$found)sf_json_response(['ok'=>false,'message'=>'Reissue of must reference an existing release ID.'],422);}
foreach((array)($ra['media']??[]) as $m){if(!is_array($m))continue;$url=sf_clean_text($m['url']??'',500);if($url==='')continue;$archive['media'][]=['type'=>sf_clean_text($m['type']??'link',40),'title'=>sf_clean_text($m['title']??'Archive item',180),'url'=>$url,'caption'=>sf_clean_text($m['caption']??'',500),'date'=>sf_clean_text($m['date']??'',20)];if(count($archive['media'])>=80)break;}
$art=is_array($raw['artwork']??null)?$raw['artwork']:[];
$release=['schema'=>'stonefellow.release.v2','id'=>$id,'title'=>$title,'type'=>sf_clean_text($raw['type']??'album',40),'state'=>$state,'release_date'=>sf_clean_text($raw['release_date']??'',20),'catalog_number'=>sf_clean_text($raw['catalog_number']??'',80),'upc_ean'=>sf_clean_text($raw['upc_ean']??'',40),'label'=>sf_clean_text($raw['label']??'',140),'genre'=>sf_clean_text($raw['genre']??'',80),'description'=>sf_clean_text($raw['description']??'',4000),'liner_notes'=>sf_clean_text($raw['liner_notes']??($raw['notes']??''),10000),'credits'=>$credits,'archive'=>$archive,'track_ids'=>$trackIds,'featured_track_id'=>$featured,'digital_price'=>max(0,(float)($raw['digital_price']??10)),'purchasable'=>sf_admin_bool($raw['purchasable']??true),'agent_discoverable'=>sf_admin_bool($raw['agent_discoverable']??true),'public_visible'=>sf_admin_bool($raw['public_visible']??($state==='published')),'artwork'=>['cover'=>sf_clean_text(($art['cover']??'')!==''?$art['cover']:$inheritedCover,300),'back'=>sf_clean_text($art['back']??'',300),'label_a'=>sf_clean_text($art['label_a']??'',300),'label_b'=>sf_clean_text($art['label_b']??'',300),'social_square'=>sf_clean_text($art['social_square']??'',300),'social_story'=>sf_clean_text($art['social_story']??'',300)],'created_at'=>$old['created_at']??gmdate('c'),'updated_at'=>gmdate('c')];
if($idx===null)$rows[]=$release;else$rows[$idx]=$release;sf_admin_write_releases($rows);
if($state==='published'){foreach($catalog as &$t){if(in_array((string)($t['id']??''),$trackIds,true)){$t['release']=$title;if(empty($t['artwork'])&&!empty($release['artwork']['cover']))$t['artwork']=$release['artwork']['cover'];}}unset($t);sf_admin_write_catalog($catalog);}
sf_json_response(['ok'=>true,'release'=>$release]);