<?php
declare(strict_types=1); require __DIR__.'/bootstrap.php';
if(($_SERVER['REQUEST_METHOD']??'GET')==='GET'){sf_admin_require_auth(false);sf_json_response(['ok'=>true,'releases'=>sf_admin_releases()]);}
if(($_SERVER['REQUEST_METHOD']??'')!=='POST')sf_json_response(['ok'=>false,'error'=>'method_not_allowed'],405);sf_admin_require_auth(true);$b=sf_request_json();$action=(string)($b['action']??'save');$rows=sf_admin_releases();
if($action==='delete'){$id=sf_admin_slug((string)($b['id']??''),'');$rows=array_values(array_filter($rows,fn($r)=>(string)($r['id']??'')!==$id));sf_admin_write_releases($rows);sf_json_response(['ok'=>true]);}
$raw=is_array($b['release']??null)?$b['release']:[];$title=sf_clean_text($raw['title']??'',180);if($title==='')sf_json_response(['ok'=>false,'message'=>'Release title is required.'],422);$id=sf_admin_slug((string)($raw['id']??$title),'release');$idx=null;foreach($rows as $i=>$r)if((string)($r['id']??'')===$id){$idx=$i;break;}$old=$idx===null?[]:$rows[$idx];
$state=(string)($raw['state']??($old['state']??'draft'));if(!in_array($state,['draft','review','scheduled','published','archived'],true))$state='draft';$trackIds=[];foreach((array)($raw['track_ids']??[]) as $tid){$tid=sf_clean_text($tid,100);if($tid!==''&&!in_array($tid,$trackIds,true))$trackIds[]=$tid;}
$inheritedCover='';if(!empty($trackIds)){foreach(sf_catalog() as $ct){if((string)($ct['id']??'')===$trackIds[0]){$inheritedCover=(string)($ct['artwork']??($ct['metadata']['album_cover']??''));break;}}}
$release=['schema'=>'stonefellow.release.v1','id'=>$id,'title'=>$title,'type'=>sf_clean_text($raw['type']??'album',40),'state'=>$state,'release_date'=>sf_clean_text($raw['release_date']??'',20),'catalog_number'=>sf_clean_text($raw['catalog_number']??'',80),'upc_ean'=>sf_clean_text($raw['upc_ean']??'',40),'label'=>sf_clean_text($raw['label']??'',140),'genre'=>sf_clean_text($raw['genre']??'',80),'description'=>sf_clean_text($raw['description']??'',4000),'track_ids'=>$trackIds,'featured_track_id'=>sf_clean_text($raw['featured_track_id']??'',100),'digital_price'=>max(0,(float)($raw['digital_price']??10)),'purchasable'=>sf_admin_bool($raw['purchasable']??true),'agent_discoverable'=>sf_admin_bool($raw['agent_discoverable']??true),'public_visible'=>sf_admin_bool($raw['public_visible']??($state==='published')),'artwork'=>['cover'=>sf_clean_text(($raw['artwork']['cover']??'')!==''?$raw['artwork']['cover']:$inheritedCover,300),'back'=>sf_clean_text($raw['artwork']['back']??'',300),'label_a'=>sf_clean_text($raw['artwork']['label_a']??'',300),'label_b'=>sf_clean_text($raw['artwork']['label_b']??'',300),'social_square'=>sf_clean_text($raw['artwork']['social_square']??'',300),'social_story'=>sf_clean_text($raw['artwork']['social_story']??'',300)],'created_at'=>$old['created_at']??gmdate('c'),'updated_at'=>gmdate('c')];
if($idx===null)$rows[]=$release;else$rows[$idx]=$release;sf_admin_write_releases($rows);
if($state==='published'){ $catalog=sf_catalog();foreach($catalog as &$t){if(in_array((string)($t['id']??''),$trackIds,true)){$t['release']=$title;if(empty($t['artwork'])&&!empty($release['artwork']['cover']))$t['artwork']=$release['artwork']['cover'];}}unset($t);sf_admin_write_catalog($catalog);}
sf_json_response(['ok'=>true,'release'=>$release]);
