<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';$me=sf_admin_require_auth(($_SERVER['REQUEST_METHOD']??'GET')!=='GET');sf_entitlements_ensure_schema();sf_customer_lifecycle_ensure_schema();sf_billing_ensure_schema();
if(($_SERVER['REQUEST_METHOD']??'GET')==='GET'){$rows=sf_db()->query('SELECT id,email,display_name,role,status,created_at,last_login_at,email_verified_at FROM users ORDER BY created_at DESC')->fetchAll();foreach($rows as &$u){$e=sf_entitlement_state((int)$u['id']);$u['active_tokens']=$u['role']==='admin'?null:$e['balance'];$u['subscription']=$e['subscription'];$u['email_verified']=!empty($u['email_verified_at']);$u['active_sessions']=count(sf_auth_sessions((int)$u['id']));}unset($u);sf_json_response(['ok'=>true,'users'=>$rows]);}
$body=sf_request_json();$action=(string)($body['action']??'update');$id=(int)($body['id']??0);if($id<1)sf_json_response(['ok'=>false,'message'=>'Invalid user.'],422);
if($action==='grant_tokens'){$amount=max(1,min(100000000,(int)($body['amount']??0)));$note=sf_clean_text($body['note']??'Admin free-token grant',180);$balance=sf_token_adjust($id,$amount,'admin_grant','admin:'.(int)$me['id'],[],$note);sf_notify_user($id,'tokens','Active Tokens added',number_format($amount).' Active Tokens were added to your account.','?view=account');sf_log_user_activity($id,'token_grant','Received '.number_format($amount).' Active Tokens','tokens',(string)$amount);sf_log_admin_action((int)$me['id'],'tokens_granted','user',(string)$id,['amount'=>$amount,'balance'=>$balance]);sf_json_response(['ok'=>true,'balance'=>$balance]);}
if($action==='revoke_sessions'){sf_auth_revoke_all_user_sessions($id);sf_notify_user($id,'security','Sessions revoked','An Administrator signed out all of your Stonefellow sessions.','?view=login');sf_log_admin_action((int)$me['id'],'user_sessions_revoked','user',(string)$id);sf_json_response(['ok'=>true]);}
if($action==='send_verification'){$q=sf_db()->prepare('SELECT id,email,email_verified_at FROM users WHERE id=?');$q->execute([$id]);$target=$q->fetch();if(!$target)sf_json_response(['ok'=>false,'message'=>'User not found.'],404);if(!empty($target['email_verified_at']))sf_json_response(['ok'=>true,'message'=>'Email already verified.']);try{$mail=sf_send_email_verification($id,(string)$target['email']);sf_json_response(['ok'=>true,'message'=>'Verification email queued.','delivery_status'=>$mail['status']??'queued']);}catch(Throwable $e){sf_json_response(['ok'=>false,'message'=>$e->getMessage()],422);}}
if($action==='assign_package'){$packageId=(int)($body['package_id']??0);try{$managed=sf_billing_subscription_row($id);if($managed&&($managed['provider']??'local')==='stripe'&&!empty($managed['provider_subscription_id'])&&in_array((string)($managed['status']??''),['active','trialing','past_due'],true))throw new RuntimeException('This subscription is managed by Stripe. Change the plan through Stripe billing instead of replacing it locally.');$state=$packageId?sf_activate_package($id,$packageId,'admin_package'):sf_enroll_user($id,null);$packageName=(string)($state['subscription']['package_name']??'Stonefellow plan');sf_notify_user($id,'subscription','Subscription updated','Your Stonefellow package is now '.$packageName.'.','?view=account');sf_log_user_activity($id,'subscription_update','Subscription changed to '.$packageName,'subscription',(string)$packageId);sf_log_admin_action((int)$me['id'],'package_assigned','user',(string)$id,['package_id'=>$packageId,'package_name'=>$packageName]);sf_json_response(['ok'=>true,'entitlement'=>$state]);}catch(Throwable $e){sf_json_response(['ok'=>false,'message'=>$e->getMessage()],422);}}
$role=(string)($body['role']??'user');$status=(string)($body['status']??'active');if(!in_array($role,['user','admin'],true)||!in_array($status,['active','disabled'],true))sf_json_response(['ok'=>false,'message'=>'Invalid user update.'],422);$q=sf_db()->prepare('SELECT id,role,status FROM users WHERE id=?');$q->execute([$id]);$target=$q->fetch();if(!$target)sf_json_response(['ok'=>false,'message'=>'User not found.'],404);if($target['role']==='admin'&&$target['status']==='active'&&($role!=='admin'||$status!=='active')&&sf_count_active_admins()<=1)sf_json_response(['ok'=>false,'message'=>'You cannot remove or disable the last active administrator.'],422);$q=sf_db()->prepare('UPDATE users SET role=?,status=?,updated_at=? WHERE id=?');$q->execute([$role,$status,gmdate('c'),$id]);sf_log_admin_action((int)$me['id'],'user_access_updated','user',(string)$id,['role'=>$role,'status'=>$status]);sf_json_response(['ok'=>true]);
