<?php
declare(strict_types=1);

function sf_commerce_json(array $v): string {return json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?:'{}';}
function sf_commerce_decode(mixed $v,array $fallback=[]): array {$d=is_array($v)?$v:json_decode((string)$v,true);return is_array($d)?$d:$fallback;}
function sf_commerce_slug(string $v,string $fallback='product'): string {$v=strtolower(trim($v));$v=preg_replace('/[^a-z0-9]+/','-',$v)??'';$v=trim(substr($v,0,120),'-');return $v!==''?$v:$fallback;}

function sf_commerce_ensure_schema(): void {
    static $done=false;if($done)return;$pdo=sf_db();$driver=(string)(sf_db_config()['driver']??'');
    if($driver==='sqlite'){
        $pdo->exec("CREATE TABLE IF NOT EXISTS store_products (id TEXT PRIMARY KEY,slug TEXT NOT NULL UNIQUE,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',category TEXT NOT NULL DEFAULT 'merch',status TEXT NOT NULL DEFAULT 'draft',physical INTEGER NOT NULL DEFAULT 1,fulfillment_type TEXT NOT NULL DEFAULT 'manual',base_price_cents INTEGER NOT NULL DEFAULT 0,compare_at_price_cents INTEGER NOT NULL DEFAULT 0,inventory_mode TEXT NOT NULL DEFAULT 'unlimited',inventory_qty INTEGER NOT NULL DEFAULT 0,low_stock_threshold INTEGER NOT NULL DEFAULT 5,max_per_order INTEGER NOT NULL DEFAULT 10,featured INTEGER NOT NULL DEFAULT 0,sort_order INTEGER NOT NULL DEFAULT 0,tags_json TEXT NOT NULL DEFAULT '[]',metadata_json TEXT NOT NULL DEFAULT '{}',created_by INTEGER NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_store_products_status_sort ON store_products(status,featured,sort_order,title)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS store_variants (id INTEGER PRIMARY KEY AUTOINCREMENT,product_id TEXT NOT NULL,sku TEXT NOT NULL UNIQUE,title TEXT NOT NULL,options_json TEXT NOT NULL DEFAULT '{}',price_cents INTEGER NULL,compare_at_price_cents INTEGER NULL,inventory_mode TEXT NOT NULL DEFAULT 'inherit',inventory_qty INTEGER NOT NULL DEFAULT 0,low_stock_threshold INTEGER NOT NULL DEFAULT 5,status TEXT NOT NULL DEFAULT 'active',sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(product_id) REFERENCES store_products(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_store_variants_product_status ON store_variants(product_id,status,sort_order,id)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS store_inventory_events (id INTEGER PRIMARY KEY AUTOINCREMENT,product_id TEXT NOT NULL,variant_id INTEGER NULL,order_id TEXT NOT NULL DEFAULT '',external_key TEXT NOT NULL UNIQUE,delta INTEGER NOT NULL,before_qty INTEGER NULL,after_qty INTEGER NULL,reason TEXT NOT NULL,actor_user_id INTEGER NULL,created_at TEXT NOT NULL,FOREIGN KEY(product_id) REFERENCES store_products(id) ON DELETE CASCADE,FOREIGN KEY(variant_id) REFERENCES store_variants(id) ON DELETE SET NULL,FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_store_inventory_product_created ON store_inventory_events(product_id,variant_id,created_at)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS store_order_items (id INTEGER PRIMARY KEY AUTOINCREMENT,order_id TEXT NOT NULL,line_index INTEGER NOT NULL,user_id INTEGER NULL,contact_id INTEGER NULL,customer_email TEXT NOT NULL DEFAULT '',product_id TEXT NOT NULL,variant_id INTEGER NULL,sku TEXT NOT NULL DEFAULT '',title TEXT NOT NULL,variant_title TEXT NOT NULL DEFAULT '',quantity INTEGER NOT NULL DEFAULT 1,unit_price_cents INTEGER NOT NULL DEFAULT 0,subtotal_cents INTEGER NOT NULL DEFAULT 0,inventory_source TEXT NOT NULL DEFAULT 'unlimited',inventory_status TEXT NOT NULL DEFAULT 'reserved',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(order_id,line_index),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(contact_id) REFERENCES fan_contacts(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_store_order_items_product ON store_order_items(product_id,variant_id,created_at)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_store_order_items_customer ON store_order_items(user_id,customer_email,created_at)");
    }else{
        $pdo->exec("CREATE TABLE IF NOT EXISTS store_products (id VARCHAR(120) NOT NULL PRIMARY KEY,slug VARCHAR(140) NOT NULL UNIQUE,title VARCHAR(180) NOT NULL,description TEXT NOT NULL,category VARCHAR(80) NOT NULL DEFAULT 'merch',status VARCHAR(32) NOT NULL DEFAULT 'draft',physical TINYINT(1) NOT NULL DEFAULT 1,fulfillment_type VARCHAR(40) NOT NULL DEFAULT 'manual',base_price_cents INT NOT NULL DEFAULT 0,compare_at_price_cents INT NOT NULL DEFAULT 0,inventory_mode VARCHAR(20) NOT NULL DEFAULT 'unlimited',inventory_qty INT NOT NULL DEFAULT 0,low_stock_threshold INT NOT NULL DEFAULT 5,max_per_order INT NOT NULL DEFAULT 10,featured TINYINT(1) NOT NULL DEFAULT 0,sort_order INT NOT NULL DEFAULT 0,tags_json LONGTEXT NOT NULL,metadata_json LONGTEXT NOT NULL,created_by BIGINT UNSIGNED NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,INDEX idx_store_products_status_sort(status,featured,sort_order,title),CONSTRAINT fk_store_product_admin FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS store_variants (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,product_id VARCHAR(120) NOT NULL,sku VARCHAR(120) NOT NULL UNIQUE,title VARCHAR(180) NOT NULL,options_json LONGTEXT NOT NULL,price_cents INT NULL,compare_at_price_cents INT NULL,inventory_mode VARCHAR(20) NOT NULL DEFAULT 'inherit',inventory_qty INT NOT NULL DEFAULT 0,low_stock_threshold INT NOT NULL DEFAULT 5,status VARCHAR(32) NOT NULL DEFAULT 'active',sort_order INT NOT NULL DEFAULT 0,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,INDEX idx_store_variants_product_status(product_id,status,sort_order,id),CONSTRAINT fk_store_variant_product FOREIGN KEY(product_id) REFERENCES store_products(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS store_inventory_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,product_id VARCHAR(120) NOT NULL,variant_id BIGINT UNSIGNED NULL,order_id VARCHAR(100) NOT NULL DEFAULT '',external_key VARCHAR(220) NOT NULL UNIQUE,delta INT NOT NULL,before_qty INT NULL,after_qty INT NULL,reason VARCHAR(120) NOT NULL,actor_user_id BIGINT UNSIGNED NULL,created_at VARCHAR(40) NOT NULL,INDEX idx_store_inventory_product_created(product_id,variant_id,created_at),CONSTRAINT fk_store_inventory_product FOREIGN KEY(product_id) REFERENCES store_products(id) ON DELETE CASCADE,CONSTRAINT fk_store_inventory_variant FOREIGN KEY(variant_id) REFERENCES store_variants(id) ON DELETE SET NULL,CONSTRAINT fk_store_inventory_actor FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS store_order_items (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,order_id VARCHAR(100) NOT NULL,line_index INT NOT NULL,user_id BIGINT UNSIGNED NULL,contact_id BIGINT UNSIGNED NULL,customer_email VARCHAR(190) NOT NULL DEFAULT '',product_id VARCHAR(120) NOT NULL,variant_id BIGINT UNSIGNED NULL,sku VARCHAR(120) NOT NULL DEFAULT '',title VARCHAR(180) NOT NULL,variant_title VARCHAR(180) NOT NULL DEFAULT '',quantity INT NOT NULL DEFAULT 1,unit_price_cents INT NOT NULL DEFAULT 0,subtotal_cents INT NOT NULL DEFAULT 0,inventory_source VARCHAR(24) NOT NULL DEFAULT 'unlimited',inventory_status VARCHAR(32) NOT NULL DEFAULT 'reserved',created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,UNIQUE KEY uq_store_order_line(order_id,line_index),INDEX idx_store_order_items_product(product_id,variant_id,created_at),INDEX idx_store_order_items_customer(user_id,customer_email,created_at),CONSTRAINT fk_store_order_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,CONSTRAINT fk_store_order_contact FOREIGN KEY(contact_id) REFERENCES fan_contacts(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    }
    $done=true;
}

function sf_commerce_variant_public(array $v,array $product): array {
    $mode=(string)($v['inventory_mode']??'inherit');$source=$mode==='inherit'?(string)($product['inventory_mode']??'unlimited'):$mode;$qty=$mode==='inherit'?(int)($product['inventory_qty']??0):(int)($v['inventory_qty']??0);$price=$v['price_cents']===null?(int)$product['base_price_cents']:(int)$v['price_cents'];$compare=$v['compare_at_price_cents']===null?(int)$product['compare_at_price_cents']:(int)$v['compare_at_price_cents'];
    return ['id'=>(int)$v['id'],'sku'=>(string)$v['sku'],'title'=>(string)$v['title'],'options'=>sf_commerce_decode($v['options_json']??'',[]),'price_cents'=>$price,'compare_at_price_cents'=>$compare,'inventory_mode'=>$source,'inventory_qty'=>$source==='finite'?$qty:null,'available'=>$source!=='finite'||$qty>0,'low_stock'=>$source==='finite'&&$qty<=max(0,(int)($v['low_stock_threshold']??$product['low_stock_threshold']??5)),'status'=>(string)$v['status'],'sort_order'=>(int)$v['sort_order']];
}
function sf_commerce_product(string $id,bool $publicOnly=false): ?array {
    sf_commerce_ensure_schema();$q=sf_db()->prepare('SELECT * FROM store_products WHERE id=? OR slug=? LIMIT 1');$q->execute([$id,$id]);$p=$q->fetch();if(!$p||($publicOnly&&($p['status']??'')!=='active'))return null;$q=sf_db()->prepare('SELECT * FROM store_variants WHERE product_id=? '.($publicOnly?"AND status='active' ":'').'ORDER BY sort_order,id');$q->execute([(string)$p['id']]);$vars=$q->fetchAll();$p['tags']=sf_commerce_decode($p['tags_json']??'',[]);$p['metadata']=sf_commerce_decode($p['metadata_json']??'',[]);$p['variants']=array_map(fn($v)=>sf_commerce_variant_public($v,$p),$vars);$media=function_exists('sf_media_public_links')?sf_media_public_links('store',(string)$p['id']):[];$p['media']=$media;$primary=null;foreach($media as $m)if(($m['role']??'')==='product_primary'){$primary=$m;break;}if(!$primary)foreach($media as $m)if(($m['category']??'')==='image'){$primary=$m;break;}$p['image']=$primary['url']??'';$mode=(string)$p['inventory_mode'];$p['available']=$mode!=='finite'||(int)$p['inventory_qty']>0||count(array_filter($p['variants'],fn($v)=>!empty($v['available'])))>0;$p['low_stock']=$mode==='finite'&&(int)$p['inventory_qty']<=max(0,(int)$p['low_stock_threshold']);return $p;
}
function sf_commerce_products(bool $publicOnly=false): array {
    sf_commerce_ensure_schema();$sql='SELECT id FROM store_products'.($publicOnly?" WHERE status='active'":'').' ORDER BY featured DESC,sort_order,title';$rows=[];foreach(sf_db()->query($sql)->fetchAll(PDO::FETCH_COLUMN) as $id){$p=sf_commerce_product((string)$id,$publicOnly);if($p)$rows[]=$p;}return $rows;
}
function sf_commerce_save_product(array $raw,int $adminId): array {
    sf_commerce_ensure_schema();$title=sf_clean_text($raw['title']??'',180);if($title==='')throw new InvalidArgumentException('Product title is required.');$idInput=trim((string)($raw['id']??''));$slugInput=trim((string)($raw['slug']??''));$id=sf_commerce_slug($idInput!==''?$idInput:($slugInput!==''?$slugInput:$title));$slug=sf_commerce_slug($slugInput!==''?$slugInput:$id);$status=(string)($raw['status']??'draft');if(!in_array($status,['draft','active','archived'],true))throw new InvalidArgumentException('Invalid product status.');$mode=(string)($raw['inventory_mode']??'unlimited');if(!in_array($mode,['unlimited','finite'],true))$mode='unlimited';$fulfillment=(string)($raw['fulfillment_type']??'manual');if(!in_array($fulfillment,['manual','self','pod'],true))$fulfillment='manual';$now=gmdate('c');$existing=sf_commerce_product($id,false);$fields=['slug'=>$slug,'title'=>$title,'description'=>sf_clean_text($raw['description']??'',10000),'category'=>sf_clean_text($raw['category']??'merch',80),'status'=>$status,'physical'=>!isset($raw['physical'])||!empty($raw['physical'])?1:0,'fulfillment_type'=>$fulfillment,'base_price_cents'=>max(0,(int)($raw['base_price_cents']??0)),'compare_at_price_cents'=>max(0,(int)($raw['compare_at_price_cents']??0)),'inventory_mode'=>$mode,'inventory_qty'=>max(0,(int)($raw['inventory_qty']??0)),'low_stock_threshold'=>max(0,(int)($raw['low_stock_threshold']??5)),'max_per_order'=>max(1,min(50,(int)($raw['max_per_order']??10))),'featured'=>!empty($raw['featured'])?1:0,'sort_order'=>(int)($raw['sort_order']??0),'tags_json'=>sf_commerce_json(array_values(array_unique(array_filter(array_map(fn($x)=>sf_clean_text($x,60),(array)($raw['tags']??[])))))),'metadata_json'=>sf_commerce_json((array)($raw['metadata']??[])),'updated_at'=>$now];
    if($existing){$sets=[];$args=[];foreach($fields as $k=>$v){$sets[]="$k=?";$args[]=$v;}$args[]=$id;sf_db()->prepare('UPDATE store_products SET '.implode(',',$sets).' WHERE id=?')->execute($args);}else{$cols=['id','created_by','created_at']+[];$q=sf_db()->prepare('INSERT INTO store_products(id,slug,title,description,category,status,physical,fulfillment_type,base_price_cents,compare_at_price_cents,inventory_mode,inventory_qty,low_stock_threshold,max_per_order,featured,sort_order,tags_json,metadata_json,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$q->execute([$id,$fields['slug'],$fields['title'],$fields['description'],$fields['category'],$fields['status'],$fields['physical'],$fields['fulfillment_type'],$fields['base_price_cents'],$fields['compare_at_price_cents'],$fields['inventory_mode'],$fields['inventory_qty'],$fields['low_stock_threshold'],$fields['max_per_order'],$fields['featured'],$fields['sort_order'],$fields['tags_json'],$fields['metadata_json'],$adminId?:null,$now,$now]);}
    $seen=[];foreach((array)($raw['variants']??[]) as $i=>$vr){if(!is_array($vr))continue;$vt=sf_clean_text($vr['title']??'',180);if($vt==='')continue;$vid=max(0,(int)($vr['id']??0));$sku=strtoupper(preg_replace('/[^A-Z0-9_-]+/i','-',sf_clean_text($vr['sku']??'',120))??'');if($sku==='')$sku=strtoupper(substr($id.'-'.sf_commerce_slug($vt),0,120));$vm=(string)($vr['inventory_mode']??'inherit');if(!in_array($vm,['inherit','finite','unlimited'],true))$vm='inherit';$vs=(string)($vr['status']??'active');if(!in_array($vs,['active','archived'],true))$vs='active';$vp=array_key_exists('price_cents',$vr)&&$vr['price_cents']!==''&&$vr['price_cents']!==null?max(0,(int)$vr['price_cents']):null;$vc=array_key_exists('compare_at_price_cents',$vr)&&$vr['compare_at_price_cents']!==''&&$vr['compare_at_price_cents']!==null?max(0,(int)$vr['compare_at_price_cents']):null;$options=(array)($vr['options']??[]);
        if($vid){$q=sf_db()->prepare('UPDATE store_variants SET sku=?,title=?,options_json=?,price_cents=?,compare_at_price_cents=?,inventory_mode=?,inventory_qty=?,low_stock_threshold=?,status=?,sort_order=?,updated_at=? WHERE id=? AND product_id=?');$q->execute([$sku,$vt,sf_commerce_json($options),$vp,$vc,$vm,max(0,(int)($vr['inventory_qty']??0)),max(0,(int)($vr['low_stock_threshold']??5)),$vs,$i,$now,$vid,$id]);if($q->rowCount()||sf_db()->prepare('SELECT 1 FROM store_variants WHERE id=? AND product_id=?')->execute([$vid,$id]))$seen[]=$vid;}
        else{$q=sf_db()->prepare('INSERT INTO store_variants(product_id,sku,title,options_json,price_cents,compare_at_price_cents,inventory_mode,inventory_qty,low_stock_threshold,status,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');$q->execute([$id,$sku,$vt,sf_commerce_json($options),$vp,$vc,$vm,max(0,(int)($vr['inventory_qty']??0)),max(0,(int)($vr['low_stock_threshold']??5)),$vs,$i,$now,$now]);$seen[]=(int)sf_db()->lastInsertId();}
    }
    $q=sf_db()->prepare('SELECT id FROM store_variants WHERE product_id=?');$q->execute([$id]);foreach($q->fetchAll(PDO::FETCH_COLUMN) as $vid)if(!in_array((int)$vid,$seen,true))sf_db()->prepare("UPDATE store_variants SET status='archived',updated_at=? WHERE id=?")->execute([$now,(int)$vid]);
    return sf_commerce_product($id,false)?:[];
}
function sf_commerce_delete_product(string $id): bool {sf_commerce_ensure_schema();$q=sf_db()->prepare('SELECT COUNT(*) FROM store_order_items WHERE product_id=?');$q->execute([$id]);if((int)$q->fetchColumn()>0){sf_db()->prepare("UPDATE store_products SET status='archived',updated_at=? WHERE id=?")->execute([gmdate('c'),$id]);return true;}$q=sf_db()->prepare('DELETE FROM store_products WHERE id=?');$q->execute([$id]);return $q->rowCount()>0;}

function sf_commerce_quote_item(array $raw): array {
    $productId=sf_clean_text($raw['product_id']??'',120);$p=sf_commerce_product($productId,true);if(!$p)return ['ok'=>false,'error'=>'Merch product is unavailable.'];$qty=max(1,min(50,(int)($raw['quantity']??1)));if($qty>(int)$p['max_per_order'])return ['ok'=>false,'error'=>$p['title'].' is limited to '.$p['max_per_order'].' per order.'];$variant=null;$variantId=max(0,(int)($raw['variant_id']??0));$activeVariants=array_values(array_filter((array)$p['variants'],fn($v)=>($v['status']??'')==='active'));
    if($activeVariants){if(!$variantId)return ['ok'=>false,'error'=>'Choose an option for '.$p['title'].'.'];foreach($activeVariants as $v)if((int)$v['id']===$variantId){$variant=$v;break;}if(!$variant)return ['ok'=>false,'error'=>'Selected product option is unavailable.'];}
    $price=$variant?(int)$variant['price_cents']:(int)$p['base_price_cents'];$inventoryMode=$variant?(string)$variant['inventory_mode']:(string)$p['inventory_mode'];$available=$variant?($variant['inventory_qty']??null):($inventoryMode==='finite'?(int)$p['inventory_qty']:null);if($inventoryMode==='finite'&&$qty>(int)$available)return ['ok'=>false,'error'=>$p['title'].' does not have enough stock for quantity '.$qty.'.'];$source=$inventoryMode==='finite'?($variant&&((string)($variant['inventory_mode']??'')==='finite')?'variant':'product'):'unlimited';
    return ['ok'=>true,'item'=>['type'=>'merch','product_id'=>(string)$p['id'],'variant_id'=>$variant?(int)$variant['id']:null,'sku'=>$variant?(string)$variant['sku']:(string)$p['id'],'label'=>(string)$p['title'],'variant_label'=>$variant?(string)$variant['title']:'','quantity'=>$qty,'unit_price_cents'=>$price,'price_cents'=>$price*$qty,'physical'=>!empty($p['physical']),'fulfillment_type'=>(string)$p['fulfillment_type'],'inventory_source'=>$source]];
}
function sf_commerce_reserve_order(string $orderId,array $quote,?int $userId,string $email): array {
    sf_commerce_ensure_schema();$items=[];foreach((array)($quote['items']??[]) as $i=>$item)if(($item['type']??'')==='merch')$items[$i]=$item;if(!$items)return ['reserved'=>0];$pdo=sf_db();$check=$pdo->prepare('SELECT COUNT(*) FROM store_order_items WHERE order_id=?');$check->execute([$orderId]);if((int)$check->fetchColumn()>0)return ['reserved'=>0,'idempotent'=>true];$now=gmdate('c');$reserved=0;
    $pdo->beginTransaction();try{foreach($items as $line=>$item){$productId=(string)$item['product_id'];$variantId=!empty($item['variant_id'])?(int)$item['variant_id']:null;$qty=max(1,(int)$item['quantity']);$source=(string)($item['inventory_source']??'unlimited');$before=null;$after=null;
        if($source==='variant'&&$variantId){$u=$pdo->prepare("UPDATE store_variants SET inventory_qty=inventory_qty-?,updated_at=? WHERE id=? AND product_id=? AND inventory_qty>=? AND status='active'");$u->execute([$qty,$now,$variantId,$productId,$qty]);if(!$u->rowCount())throw new RuntimeException('Stock changed before checkout completed. Please review your cart.');$q=$pdo->prepare('SELECT inventory_qty FROM store_variants WHERE id=?');$q->execute([$variantId]);$after=(int)$q->fetchColumn();$before=$after+$qty;}
        elseif($source==='product'){$u=$pdo->prepare("UPDATE store_products SET inventory_qty=inventory_qty-?,updated_at=? WHERE id=? AND inventory_qty>=? AND status='active'");$u->execute([$qty,$now,$productId,$qty]);if(!$u->rowCount())throw new RuntimeException('Stock changed before checkout completed. Please review your cart.');$q=$pdo->prepare('SELECT inventory_qty FROM store_products WHERE id=?');$q->execute([$productId]);$after=(int)$q->fetchColumn();$before=$after+$qty;}
        if($source!=='unlimited'){$key='reserve:'.$orderId.':'.$line;$q=$pdo->prepare('INSERT INTO store_inventory_events(product_id,variant_id,order_id,external_key,delta,before_qty,after_qty,reason,actor_user_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)');$q->execute([$productId,$variantId,$orderId,$key,-$qty,$before,$after,'order_reserve',null,$now]);$reserved+=$qty;}
        $q=$pdo->prepare('INSERT INTO store_order_items(order_id,line_index,user_id,contact_id,customer_email,product_id,variant_id,sku,title,variant_title,quantity,unit_price_cents,subtotal_cents,inventory_source,inventory_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$q->execute([$orderId,$line,$userId?:null,null,strtolower($email),$productId,$variantId,(string)($item['sku']??''),(string)$item['label'],(string)($item['variant_label']??''),$qty,(int)$item['unit_price_cents'],(int)$item['price_cents'],$source,'reserved',$now,$now]);}
        $pdo->commit();return ['reserved'=>$reserved];
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}
function sf_commerce_release_order_inventory(string $orderId,string $reason='order_canceled',?int $actorId=null): int {
    sf_commerce_ensure_schema();$pdo=sf_db();$q=$pdo->prepare("SELECT * FROM store_order_items WHERE order_id=? AND inventory_status='reserved'");$q->execute([$orderId]);$rows=$q->fetchAll();if(!$rows)return 0;$released=0;$now=gmdate('c');$pdo->beginTransaction();try{foreach($rows as $r){$qty=(int)$r['quantity'];$source=(string)$r['inventory_source'];$before=null;$after=null;if($source==='variant'&&!empty($r['variant_id'])){$q=$pdo->prepare('SELECT inventory_qty FROM store_variants WHERE id=?');$q->execute([(int)$r['variant_id']]);$before=(int)$q->fetchColumn();$pdo->prepare('UPDATE store_variants SET inventory_qty=inventory_qty+?,updated_at=? WHERE id=?')->execute([$qty,$now,(int)$r['variant_id']]);$after=$before+$qty;}elseif($source==='product'){$q=$pdo->prepare('SELECT inventory_qty FROM store_products WHERE id=?');$q->execute([(string)$r['product_id']]);$before=(int)$q->fetchColumn();$pdo->prepare('UPDATE store_products SET inventory_qty=inventory_qty+?,updated_at=? WHERE id=?')->execute([$qty,$now,(string)$r['product_id']]);$after=$before+$qty;}if($source!=='unlimited'){$key='release:'.$orderId.':'.$r['line_index'];$pdo->prepare('INSERT INTO store_inventory_events(product_id,variant_id,order_id,external_key,delta,before_qty,after_qty,reason,actor_user_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([(string)$r['product_id'],!empty($r['variant_id'])?(int)$r['variant_id']:null,$orderId,$key,$qty,$before,$after,$reason,$actorId?:null,$now]);$released+=$qty;}$pdo->prepare("UPDATE store_order_items SET inventory_status='released',updated_at=? WHERE id=?")->execute([$now,(int)$r['id']]);}$pdo->commit();return $released;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}
function sf_commerce_mark_order_sold(string $orderId): void {sf_commerce_ensure_schema();sf_db()->prepare("UPDATE store_order_items SET inventory_status='sold',updated_at=? WHERE order_id=? AND inventory_status='reserved'")->execute([gmdate('c'),$orderId]);}
function sf_commerce_adjust_inventory(string $productId,?int $variantId,int $delta,string $reason,int $adminId): array {
    if($delta===0)throw new InvalidArgumentException('Inventory adjustment must be non-zero.');sf_commerce_ensure_schema();$pdo=sf_db();$now=gmdate('c');$pdo->beginTransaction();try{if($variantId){$q=$pdo->prepare('SELECT inventory_qty FROM store_variants WHERE id=? AND product_id=?');$q->execute([$variantId,$productId]);$v=$q->fetchColumn();if($v===false)throw new InvalidArgumentException('Variant not found.');$before=(int)$v;$after=max(0,$before+$delta);$pdo->prepare("UPDATE store_variants SET inventory_mode='finite',inventory_qty=?,updated_at=? WHERE id=?")->execute([$after,$now,$variantId]);}else{$q=$pdo->prepare('SELECT inventory_qty FROM store_products WHERE id=?');$q->execute([$productId]);$v=$q->fetchColumn();if($v===false)throw new InvalidArgumentException('Product not found.');$before=(int)$v;$after=max(0,$before+$delta);$pdo->prepare("UPDATE store_products SET inventory_mode='finite',inventory_qty=?,updated_at=? WHERE id=?")->execute([$after,$now,$productId]);}$actual=$after-$before;$key='admin:'.bin2hex(random_bytes(12));$pdo->prepare('INSERT INTO store_inventory_events(product_id,variant_id,order_id,external_key,delta,before_qty,after_qty,reason,actor_user_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$productId,$variantId,'',$key,$actual,$before,$after,sf_clean_text($reason,120),$adminId?:null,$now]);$pdo->commit();return ['before'=>$before,'after'=>$after,'delta'=>$actual];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}
function sf_commerce_record_purchase(string $orderId,?int $userId,array $customer,array $quote): void {
    sf_commerce_ensure_schema();$email=strtolower((string)($customer['email']??''));$contact=null;try{$contact=sf_crm_upsert_contact($email,(string)($customer['name']??''),'purchase',$userId,null,'customer');}catch(Throwable $e){}$contactId=(int)($contact['id']??0);$q=sf_db()->prepare('UPDATE store_order_items SET user_id=COALESCE(user_id,?),contact_id=?,customer_email=?,updated_at=? WHERE order_id=?');$q->execute([$userId?:null,$contactId?:null,$email,gmdate('c'),$orderId]);$merch=array_values(array_filter((array)($quote['items']??[]),fn($x)=>($x['type']??'')==='merch'));if($contactId&&$merch){$meta=['total_cents'=>(int)($quote['total_cents']??0),'items'=>array_map(fn($x)=>['product_id'=>$x['product_id'],'variant_id'=>$x['variant_id'],'sku'=>$x['sku'],'title'=>$x['label'],'variant'=>$x['variant_label'],'quantity'=>$x['quantity'],'subtotal_cents'=>$x['price_cents']],$merch)];sf_crm_log_event($contactId,$userId,'merch_purchase','Purchased Stonefellow merchandise','order',$orderId,$meta);}
}
function sf_commerce_order_items(string $orderId): array {sf_commerce_ensure_schema();$q=sf_db()->prepare('SELECT * FROM store_order_items WHERE order_id=? ORDER BY line_index,id');$q->execute([$orderId]);return $q->fetchAll();}
function sf_commerce_purchase_history(?int $userId,string $email='',int $limit=50): array {sf_commerce_ensure_schema();$where=[];$args=[];if($userId){$where[]='user_id=?';$args[]=$userId;}if($email!==''){$where[]='customer_email=?';$args[]=strtolower($email);}if(!$where)return [];$sql='SELECT * FROM store_order_items WHERE ('.implode(' OR ',$where).") AND inventory_status<>'released' ORDER BY id DESC LIMIT ".max(1,min(200,$limit));$q=sf_db()->prepare($sql);$q->execute($args);return $q->fetchAll();}
function sf_commerce_summary(): array {
    sf_commerce_ensure_schema();$pdo=sf_db();$products=(int)$pdo->query('SELECT COUNT(*) FROM store_products')->fetchColumn();$active=(int)$pdo->query("SELECT COUNT(*) FROM store_products WHERE status='active'")->fetchColumn();$low=(int)$pdo->query("SELECT COUNT(*) FROM store_products WHERE status='active' AND inventory_mode='finite' AND inventory_qty<=low_stock_threshold")->fetchColumn();$low+=(int)$pdo->query("SELECT COUNT(*) FROM store_variants WHERE status='active' AND inventory_mode='finite' AND inventory_qty<=low_stock_threshold")->fetchColumn();$q=$pdo->query("SELECT COALESCE(SUM(quantity),0) units,COALESCE(SUM(subtotal_cents),0) revenue FROM store_order_items WHERE inventory_status<>'released'");$s=$q->fetch()?:[];return ['products'=>$products,'active'=>$active,'low_stock'=>$low,'units_sold'=>(int)($s['units']??0),'gross_merch_cents'=>(int)($s['revenue']??0)];
}
function sf_commerce_inventory_events(string $productId='',int $limit=100): array {sf_commerce_ensure_schema();$limit=max(1,min(500,$limit));if($productId!==''){$q=sf_db()->prepare('SELECT * FROM store_inventory_events WHERE product_id=? ORDER BY id DESC LIMIT '.$limit);$q->execute([$productId]);return $q->fetchAll();}return sf_db()->query('SELECT * FROM store_inventory_events ORDER BY id DESC LIMIT '.$limit)->fetchAll();}
function sf_commerce_agent_context(): string {$rows=sf_commerce_products(true);if(!$rows)return '';$out=['ACTIVE STONEFELLOW MERCH'];foreach($rows as $p){$variants=array_map(fn($v)=>$v['title'].' '.($v['available']?'available':'sold out'),(array)$p['variants']);$out[]='- product_id='.$p['id'].' | '.$p['title'].' | $'.sf_money((int)$p['base_price_cents']).' | '.($p['available']?'available':'sold out').' | category '.$p['category'].' | '.implode(', ',$variants).' | '.substr((string)$p['description'],0,280);}return implode("\n",$out);}
