<?php
declare(strict_types=1);

function sf_entitlements_ensure_schema(): void {
    $pdo=sf_db();$driver=(string)(sf_db_config()['driver']??'');
    if($driver==='sqlite'){
        $pdo->exec("CREATE TABLE IF NOT EXISTS subscription_packages (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,description TEXT NOT NULL DEFAULT '',monthly_price_cents INTEGER NOT NULL DEFAULT 0,monthly_tokens INTEGER NOT NULL DEFAULT 0,trial_days INTEGER NOT NULL DEFAULT 0,trial_tokens INTEGER NOT NULL DEFAULT 0,is_public INTEGER NOT NULL DEFAULT 1,is_active INTEGER NOT NULL DEFAULT 1,is_featured INTEGER NOT NULL DEFAULT 0,sort_order INTEGER NOT NULL DEFAULT 0,features_json TEXT NOT NULL DEFAULT '[]',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS user_token_balances (user_id INTEGER PRIMARY KEY,balance INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS token_ledger (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,delta INTEGER NOT NULL,balance_after INTEGER NOT NULL,entry_type TEXT NOT NULL,source TEXT NOT NULL DEFAULT '',provider TEXT NOT NULL DEFAULT '',model TEXT NOT NULL DEFAULT '',input_tokens INTEGER NOT NULL DEFAULT 0,output_tokens INTEGER NOT NULL DEFAULT 0,voice_chars INTEGER NOT NULL DEFAULT 0,note TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS user_subscriptions (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL UNIQUE,package_id INTEGER NULL,status TEXT NOT NULL,trial_started_at TEXT NULL,trial_ends_at TEXT NULL,current_period_start TEXT NULL,current_period_end TEXT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(package_id) REFERENCES subscription_packages(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS user_trial_history (user_id INTEGER PRIMARY KEY,first_trial_package_id INTEGER NULL,first_trial_started_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(first_trial_package_id) REFERENCES subscription_packages(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS agent_conversations (id TEXT PRIMARY KEY,user_id INTEGER NOT NULL,title TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS agent_messages (id INTEGER PRIMARY KEY AUTOINCREMENT,conversation_id TEXT NOT NULL,user_id INTEGER NOT NULL,role TEXT NOT NULL,content TEXT NOT NULL,provider TEXT NOT NULL DEFAULT '',model TEXT NOT NULL DEFAULT '',input_tokens INTEGER NOT NULL DEFAULT 0,output_tokens INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,FOREIGN KEY(conversation_id) REFERENCES agent_conversations(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS agent_brain_decisions (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,conversation_id TEXT NOT NULL,phase TEXT NOT NULL,route TEXT NOT NULL DEFAULT '',action TEXT NOT NULL DEFAULT '',context_profile TEXT NOT NULL DEFAULT '',needs_llm INTEGER NOT NULL DEFAULT 0,requires_confirmation INTEGER NOT NULL DEFAULT 0,request_excerpt TEXT NOT NULL DEFAULT '',response_excerpt TEXT NOT NULL DEFAULT '',provider_run_id TEXT NOT NULL DEFAULT '',provider_status TEXT NOT NULL DEFAULT '',input_tokens INTEGER NOT NULL DEFAULT 0,output_tokens INTEGER NOT NULL DEFAULT 0,details_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)");
    } else {
        $pdo->exec("CREATE TABLE IF NOT EXISTS subscription_packages (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,slug VARCHAR(120) NOT NULL UNIQUE,description TEXT NOT NULL,monthly_price_cents INT NOT NULL DEFAULT 0,monthly_tokens INT NOT NULL DEFAULT 0,trial_days INT NOT NULL DEFAULT 0,trial_tokens INT NOT NULL DEFAULT 0,is_public TINYINT(1) NOT NULL DEFAULT 1,is_active TINYINT(1) NOT NULL DEFAULT 1,is_featured TINYINT(1) NOT NULL DEFAULT 0,sort_order INT NOT NULL DEFAULT 0,features_json LONGTEXT NOT NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS user_token_balances (user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,balance BIGINT NOT NULL DEFAULT 0,updated_at VARCHAR(40) NOT NULL,CONSTRAINT fk_token_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS token_ledger (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,delta BIGINT NOT NULL,balance_after BIGINT NOT NULL,entry_type VARCHAR(40) NOT NULL,source VARCHAR(120) NOT NULL DEFAULT '',provider VARCHAR(40) NOT NULL DEFAULT '',model VARCHAR(160) NOT NULL DEFAULT '',input_tokens INT NOT NULL DEFAULT 0,output_tokens INT NOT NULL DEFAULT 0,voice_chars INT NOT NULL DEFAULT 0,note VARCHAR(255) NOT NULL DEFAULT '',created_at VARCHAR(40) NOT NULL,INDEX idx_token_user_created(user_id,created_at),CONSTRAINT fk_ledger_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS user_subscriptions (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL UNIQUE,package_id BIGINT UNSIGNED NULL,status VARCHAR(32) NOT NULL,trial_started_at VARCHAR(40) NULL,trial_ends_at VARCHAR(40) NULL,current_period_start VARCHAR(40) NULL,current_period_end VARCHAR(40) NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,CONSTRAINT fk_sub_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_sub_package FOREIGN KEY(package_id) REFERENCES subscription_packages(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS user_trial_history (user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,first_trial_package_id BIGINT UNSIGNED NULL,first_trial_started_at VARCHAR(40) NOT NULL,CONSTRAINT fk_trial_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_trial_package FOREIGN KEY(first_trial_package_id) REFERENCES subscription_packages(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS agent_conversations (id VARCHAR(80) PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,title VARCHAR(160) NOT NULL DEFAULT '',created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,INDEX idx_conv_user(user_id,updated_at),CONSTRAINT fk_conv_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS agent_messages (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,conversation_id VARCHAR(80) NOT NULL,user_id BIGINT UNSIGNED NOT NULL,role VARCHAR(20) NOT NULL,content LONGTEXT NOT NULL,provider VARCHAR(40) NOT NULL DEFAULT '',model VARCHAR(160) NOT NULL DEFAULT '',input_tokens INT NOT NULL DEFAULT 0,output_tokens INT NOT NULL DEFAULT 0,created_at VARCHAR(40) NOT NULL,INDEX idx_msg_conv(conversation_id,id),CONSTRAINT fk_msg_conv FOREIGN KEY(conversation_id) REFERENCES agent_conversations(id) ON DELETE CASCADE,CONSTRAINT fk_msg_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS agent_brain_decisions (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,conversation_id VARCHAR(80) NOT NULL,phase VARCHAR(32) NOT NULL,route VARCHAR(80) NOT NULL DEFAULT '',action VARCHAR(80) NOT NULL DEFAULT '',context_profile VARCHAR(40) NOT NULL DEFAULT '',needs_llm TINYINT(1) NOT NULL DEFAULT 0,requires_confirmation TINYINT(1) NOT NULL DEFAULT 0,request_excerpt VARCHAR(500) NOT NULL DEFAULT '',response_excerpt VARCHAR(500) NOT NULL DEFAULT '',provider_run_id VARCHAR(160) NOT NULL DEFAULT '',provider_status VARCHAR(40) NOT NULL DEFAULT '',input_tokens INT NOT NULL DEFAULT 0,output_tokens INT NOT NULL DEFAULT 0,details_json LONGTEXT NOT NULL,created_at VARCHAR(40) NOT NULL,INDEX idx_brain_created(created_at),INDEX idx_brain_user(user_id,created_at),CONSTRAINT fk_brain_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    }
    // Preserve one-trial-per-account semantics for accounts that already used a trial before v1.1.
    if($driver==='sqlite'){
        $pdo->exec("INSERT OR IGNORE INTO user_trial_history(user_id,first_trial_package_id,first_trial_started_at) SELECT user_id,package_id,trial_started_at FROM user_subscriptions WHERE trial_started_at IS NOT NULL");
    }else{
        $pdo->exec("INSERT IGNORE INTO user_trial_history(user_id,first_trial_package_id,first_trial_started_at) SELECT user_id,package_id,trial_started_at FROM user_subscriptions WHERE trial_started_at IS NOT NULL");
    }
    sf_entitlements_seed_trial();
}

function sf_entitlements_seed_trial(): void {
    $pdo=sf_db();$count=(int)$pdo->query('SELECT COUNT(*) FROM subscription_packages')->fetchColumn();if($count>0)return;
    $now=gmdate('c');$q=$pdo->prepare('INSERT INTO subscription_packages(name,slug,description,monthly_price_cents,monthly_tokens,trial_days,trial_tokens,is_public,is_active,is_featured,sort_order,features_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
    $q->execute(['Free Trial','free-trial','Try the Stonefellow agent, explore the catalog, and build a custom record before choosing a monthly package.',0,0,7,10000,1,1,1,0,json_encode(['10,000 Active Tokens','7-day trial','Catalog + Knowledge agent','Voice when enabled']),$now,$now]);
}
function sf_package_public(array $p): array {if(function_exists('sf_billing_ensure_schema'))sf_billing_ensure_schema();if(function_exists('sf_membership_ensure_schema'))sf_membership_ensure_schema();$membership=function_exists('sf_membership_package')?sf_membership_package($p):['enabled'=>false,'rank'=>0,'badge'=>'','benefits'=>[]];return ['id'=>(int)$p['id'],'name'=>$p['name'],'slug'=>$p['slug'],'description'=>$p['description'],'monthly_price_cents'=>(int)$p['monthly_price_cents'],'monthly_tokens'=>(int)$p['monthly_tokens'],'trial_days'=>(int)$p['trial_days'],'trial_tokens'=>(int)$p['trial_tokens'],'is_featured'=>(bool)$p['is_featured'],'provider_price_id'=>(string)($p['provider_price_id']??''),'features'=>json_decode((string)$p['features_json'],true)?:[],'membership'=>$membership];}
function sf_packages(bool $publicOnly=true): array {sf_entitlements_ensure_schema();if(function_exists('sf_billing_ensure_schema'))sf_billing_ensure_schema();if(function_exists('sf_membership_ensure_schema'))sf_membership_ensure_schema();$sql='SELECT * FROM subscription_packages'.($publicOnly?' WHERE is_active=1 AND is_public=1':'').' ORDER BY sort_order ASC, monthly_price_cents ASC, id ASC';return sf_db()->query($sql)->fetchAll();}
function sf_package(int $id): ?array {sf_entitlements_ensure_schema();if(function_exists('sf_billing_ensure_schema'))sf_billing_ensure_schema();if(function_exists('sf_membership_ensure_schema'))sf_membership_ensure_schema();$q=sf_db()->prepare('SELECT * FROM subscription_packages WHERE id=? LIMIT 1');$q->execute([$id]);$r=$q->fetch();return $r?:null;}
function sf_token_balance(int $userId): int {sf_entitlements_ensure_schema();$q=sf_db()->prepare('SELECT balance FROM user_token_balances WHERE user_id=?');$q->execute([$userId]);$v=$q->fetchColumn();return $v===false?0:(int)$v;}
function sf_token_source_exists(int $userId,string $type,string $source): bool {
    sf_entitlements_ensure_schema();$q=sf_db()->prepare('SELECT id FROM token_ledger WHERE user_id=? AND entry_type=? AND source=? LIMIT 1');$q->execute([$userId,$type,$source]);return $q->fetchColumn()!==false;
}
function sf_token_adjust(int $userId,int $delta,string $type,string $source='',array $usage=[],string $note=''): int {
    sf_entitlements_ensure_schema();$pdo=sf_db();$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT balance FROM user_token_balances WHERE user_id=?');$q->execute([$userId]);$v=$q->fetchColumn();$before=$v===false?0:(int)$v;$after=max(0,$before+$delta);$now=gmdate('c');if($v===false){$u=$pdo->prepare('INSERT INTO user_token_balances(user_id,balance,updated_at) VALUES(?,?,?)');$u->execute([$userId,$after,$now]);}else{$u=$pdo->prepare('UPDATE user_token_balances SET balance=?,updated_at=? WHERE user_id=?');$u->execute([$after,$now,$userId]);}$l=$pdo->prepare('INSERT INTO token_ledger(user_id,delta,balance_after,entry_type,source,provider,model,input_tokens,output_tokens,voice_chars,note,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');$l->execute([$userId,$after-$before,$after,$type,$source,(string)($usage['provider']??''),(string)($usage['model']??''),(int)($usage['input_tokens']??0),(int)($usage['output_tokens']??0),(int)($usage['voice_chars']??0),sf_clean_text($note,255),$now]);$pdo->commit();return $after;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
function sf_enroll_user(int $userId,?int $packageId=null): array {
    sf_entitlements_ensure_schema();$pdo=sf_db();$p=$packageId?sf_package($packageId):null;if(!$p){$rows=sf_packages(true);$p=$rows[0]??null;}if(!$p)throw new RuntimeException('No active subscription package is available.');if(empty($p['is_active'])||empty($p['is_public']))throw new InvalidArgumentException('Selected package is not available.');
    $now=gmdate('c');$requestedTrialDays=max(0,(int)$p['trial_days']);$trialTokens=max(0,(int)$p['trial_tokens']);$price=(int)$p['monthly_price_cents'];
    $t=$pdo->prepare('SELECT user_id FROM user_trial_history WHERE user_id=? LIMIT 1');$t->execute([$userId]);$trialRedeemed=$t->fetchColumn()!==false;
    $trialDays=$trialRedeemed?0:$requestedTrialDays;
    $status=$trialDays>0?'trialing':($price===0?'active':'pending_payment');$trialEnd=$trialDays>0?gmdate('c',time()+$trialDays*86400):null;$periodEnd=$status==='active'?gmdate('c',strtotime('+1 month')):null;
    if($trialDays>0){$mark=$pdo->prepare('INSERT INTO user_trial_history(user_id,first_trial_package_id,first_trial_started_at) VALUES(?,?,?)');$mark->execute([$userId,(int)$p['id'],$now]);}
    $q=$pdo->prepare('SELECT id FROM user_subscriptions WHERE user_id=?');$q->execute([$userId]);if($q->fetchColumn()!==false){$u=$pdo->prepare("UPDATE user_subscriptions SET package_id=?,status=?,trial_started_at=?,trial_ends_at=?,current_period_start=?,current_period_end=?,provider='local',cancel_at_period_end=0,canceled_at=NULL,grace_ends_at=NULL,updated_at=? WHERE user_id=?");$u->execute([(int)$p['id'],$status,$trialDays?$now:null,$trialEnd,$status==='active'?$now:null,$periodEnd,$now,$userId]);}else{$u=$pdo->prepare("INSERT INTO user_subscriptions(user_id,package_id,status,trial_started_at,trial_ends_at,current_period_start,current_period_end,created_at,updated_at,provider,cancel_at_period_end) VALUES(?,?,?,?,?,?,?,?,?,'local',0)");$u->execute([$userId,(int)$p['id'],$status,$trialDays?$now:null,$trialEnd,$status==='active'?$now:null,$periodEnd,$now,$now]);}
    $grant=$trialDays>0?$trialTokens:($status==='active'?(int)$p['monthly_tokens']:0);if($grant>0)sf_token_adjust($userId,$grant,$trialDays>0?'trial_grant':'monthly_grant','package:'.$p['slug'],[],($trialDays>0?'Free trial':'Monthly').' allocation');return sf_entitlement_state($userId);
}
function sf_entitlement_state(int $userId): array {
    sf_entitlements_ensure_schema();if(function_exists('sf_billing_ensure_schema'))sf_billing_ensure_schema();$q=sf_db()->prepare('SELECT s.*,p.name package_name,p.slug package_slug,p.monthly_price_cents,p.monthly_tokens,p.trial_days,p.trial_tokens,p.provider_price_id FROM user_subscriptions s LEFT JOIN subscription_packages p ON p.id=s.package_id WHERE s.user_id=? LIMIT 1');$q->execute([$userId]);$s=$q->fetch()?:null;if($s&&$s['status']==='trialing'&&!empty($s['trial_ends_at'])&&strtotime((string)$s['trial_ends_at'])<time()){$status=((int)$s['monthly_price_cents']===0)?'active':'trial_expired';$now=gmdate('c');$u=sf_db()->prepare('UPDATE user_subscriptions SET status=?,updated_at=? WHERE user_id=?');$u->execute([$status,$now,$userId]);if($status==='active'&&(int)$s['monthly_tokens']>0)sf_token_adjust($userId,(int)$s['monthly_tokens'],'monthly_grant','package:'.$s['package_slug'],[],'First monthly allocation after trial');$s['status']=$status;}
    if($s&&$s['status']==='active'&&($s['provider']??'local')!=='stripe'&&!empty($s['current_period_end'])&&strtotime((string)$s['current_period_end'])<=time()){
        $now=gmdate('c');
        if(!empty($s['cancel_at_period_end'])){
            sf_db()->prepare("UPDATE user_subscriptions SET status='canceled',canceled_at=?,updated_at=? WHERE user_id=?")->execute([$now,$now,$userId]);$s['status']='canceled';$s['canceled_at']=$now;
        }else{
            $monthly=max(0,(int)($s['monthly_tokens']??0));$oldPeriodEnd=(string)$s['current_period_end'];$start=$now;$end=gmdate('c',strtotime('+1 month'));$u=sf_db()->prepare('UPDATE user_subscriptions SET current_period_start=?,current_period_end=?,updated_at=? WHERE user_id=?');$u->execute([$start,$end,$start,$userId]);$renewalSource='local_renewal:'.$oldPeriodEnd;if($monthly>0&&!sf_token_source_exists($userId,'monthly_grant',$renewalSource))sf_token_adjust($userId,$monthly,'monthly_grant',$renewalSource,[],'Monthly package renewal');$s['current_period_start']=$start;$s['current_period_end']=$end;
        }
    }
    $ledger=sf_db()->prepare('SELECT delta,balance_after,entry_type,source,provider,model,input_tokens,output_tokens,voice_chars,note,created_at FROM token_ledger WHERE user_id=? ORDER BY id DESC LIMIT 20');$ledger->execute([$userId]);$out=['balance'=>sf_token_balance($userId),'subscription'=>$s,'ledger'=>$ledger->fetchAll()];if(function_exists('sf_membership_state'))$out['membership']=sf_membership_state($userId,true);return $out;
}
function sf_can_use_ai(array $user,int $estimated=1): array {if(($user['role']??'')==='admin')return ['ok'=>true,'unlimited'=>true,'balance'=>PHP_INT_MAX];$state=sf_entitlement_state((int)$user['id']);if(!$state['subscription'])$state=sf_enroll_user((int)$user['id'],null);return ['ok'=>$state['balance']>=$estimated,'unlimited'=>false,'balance'=>$state['balance'],'state'=>$state];}
function sf_consume_ai(array $user,int $amount,array $usage,string $source='agent'): int {if(($user['role']??'')==='admin')return PHP_INT_MAX;return sf_token_adjust((int)$user['id'],-max(0,$amount),'usage',$source,$usage,'AI interaction');}

function sf_activate_package(int $userId,int $packageId,string $source='admin'): array {
    sf_entitlements_ensure_schema();
    $p=sf_package($packageId);if(!$p||empty($p['is_active']))throw new InvalidArgumentException('Package is unavailable.');
    $pdo=sf_db();$now=gmdate('c');$end=gmdate('c',strtotime('+1 month'));
    $q=$pdo->prepare('SELECT id,package_id,status,current_period_end FROM user_subscriptions WHERE user_id=? LIMIT 1');$q->execute([$userId]);$existing=$q->fetch()?:null;
    // Re-selecting the same already-active package inside its current billing period is idempotent.
    // This prevents duplicate monthly Active Token grants from double-clicks/retries/Admin reassignment.
    if($existing&&(int)$existing['package_id']===$packageId&&($existing['status']??'')==='active'&&!empty($existing['current_period_end'])&&strtotime((string)$existing['current_period_end'])>time()) return sf_entitlement_state($userId);
    if($existing){$u=$pdo->prepare("UPDATE user_subscriptions SET package_id=?,status='active',trial_started_at=NULL,trial_ends_at=NULL,current_period_start=?,current_period_end=?,provider='local',provider_customer_id='',provider_subscription_id='',cancel_at_period_end=0,canceled_at=NULL,grace_ends_at=NULL,updated_at=? WHERE user_id=?");$u->execute([$packageId,$now,$end,$now,$userId]);}
    else{$u=$pdo->prepare("INSERT INTO user_subscriptions(user_id,package_id,status,trial_started_at,trial_ends_at,current_period_start,current_period_end,created_at,updated_at,provider,provider_customer_id,provider_subscription_id,cancel_at_period_end) VALUES(?,?,'active',NULL,NULL,?,?,?,?,'local','','',0)");$u->execute([$userId,$packageId,$now,$end,$now,$now]);}
    $tokens=max(0,(int)$p['monthly_tokens']);if($tokens>0)sf_token_adjust($userId,$tokens,'monthly_grant',$source.':'.$p['slug'],[],'Monthly package activation');
    return sf_entitlement_state($userId);
}
