<?php
declare(strict_types=1);

function sf_fulfillment_json(array $v): string {return json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?:'{}';}
function sf_fulfillment_decode(mixed $v,array $fallback=[]): array {$d=is_array($v)?$v:json_decode((string)$v,true);return is_array($d)?$d:$fallback;}
function sf_fulfillment_case_key(): string {return 'CARE-'.gmdate('ymd').'-'.strtoupper(bin2hex(random_bytes(3)));}
function sf_fulfillment_request_key(string $prefix='op'): string {return $prefix.':'.bin2hex(random_bytes(12));}

function sf_fulfillment_ensure_schema(): void {
    static $done=false;if($done)return;$pdo=sf_db();$driver=(string)(sf_db_config()['driver']??'');
    if($driver==='sqlite'){
        $pdo->exec("CREATE TABLE IF NOT EXISTS order_shipments (id INTEGER PRIMARY KEY AUTOINCREMENT,order_id TEXT NOT NULL,request_key TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'label_created',carrier TEXT NOT NULL DEFAULT '',service TEXT NOT NULL DEFAULT '',tracking_number TEXT NOT NULL DEFAULT '',tracking_url TEXT NOT NULL DEFAULT '',estimated_delivery_at TEXT NULL,shipped_at TEXT NULL,delivered_at TEXT NULL,note TEXT NOT NULL DEFAULT '',created_by INTEGER NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_order_shipments_order ON order_shipments(order_id,status,created_at)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS order_refunds (id INTEGER PRIMARY KEY AUTOINCREMENT,order_id TEXT NOT NULL,request_key TEXT NOT NULL UNIQUE,amount_cents INTEGER NOT NULL DEFAULT 0,reason TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'requested',provider_reference TEXT NOT NULL DEFAULT '',restock_status TEXT NOT NULL DEFAULT 'not_requested',created_by INTEGER NULL,requested_at TEXT NOT NULL,confirmed_at TEXT NULL,rejected_at TEXT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_order_refunds_order ON order_refunds(order_id,status,requested_at)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS support_cases (id INTEGER PRIMARY KEY AUTOINCREMENT,case_key TEXT NOT NULL UNIQUE,order_id TEXT NOT NULL DEFAULT '',user_id INTEGER NULL,contact_id INTEGER NULL,email TEXT NOT NULL DEFAULT '',subject TEXT NOT NULL,issue_type TEXT NOT NULL DEFAULT 'other',priority TEXT NOT NULL DEFAULT 'normal',status TEXT NOT NULL DEFAULT 'open',source TEXT NOT NULL DEFAULT 'fan',assigned_to INTEGER NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,closed_at TEXT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(contact_id) REFERENCES fan_contacts(id) ON DELETE SET NULL,FOREIGN KEY(assigned_to) REFERENCES users(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_support_cases_status ON support_cases(status,priority,updated_at)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_support_cases_order ON support_cases(order_id,updated_at)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS support_messages (id INTEGER PRIMARY KEY AUTOINCREMENT,case_id INTEGER NOT NULL,request_key TEXT NOT NULL UNIQUE,actor_type TEXT NOT NULL,actor_user_id INTEGER NULL,message TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(case_id) REFERENCES support_cases(id) ON DELETE CASCADE,FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_support_messages_case ON support_messages(case_id,id)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS order_ops_events (id INTEGER PRIMARY KEY AUTOINCREMENT,order_id TEXT NOT NULL DEFAULT '',case_id INTEGER NULL,event_type TEXT NOT NULL,external_key TEXT NOT NULL UNIQUE,actor_user_id INTEGER NULL,metadata_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,FOREIGN KEY(case_id) REFERENCES support_cases(id) ON DELETE SET NULL,FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_order_ops_events_order ON order_ops_events(order_id,created_at)");
    }else{
        $pdo->exec("CREATE TABLE IF NOT EXISTS order_shipments (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,order_id VARCHAR(100) NOT NULL,request_key VARCHAR(190) NOT NULL UNIQUE,status VARCHAR(32) NOT NULL DEFAULT 'label_created',carrier VARCHAR(100) NOT NULL DEFAULT '',service VARCHAR(100) NOT NULL DEFAULT '',tracking_number VARCHAR(160) NOT NULL DEFAULT '',tracking_url VARCHAR(700) NOT NULL DEFAULT '',estimated_delivery_at VARCHAR(40) NULL,shipped_at VARCHAR(40) NULL,delivered_at VARCHAR(40) NULL,note TEXT NOT NULL,created_by BIGINT UNSIGNED NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,INDEX idx_order_shipments_order(order_id,status,created_at),CONSTRAINT fk_order_shipment_admin FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS order_refunds (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,order_id VARCHAR(100) NOT NULL,request_key VARCHAR(190) NOT NULL UNIQUE,amount_cents INT NOT NULL DEFAULT 0,reason TEXT NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'requested',provider_reference VARCHAR(255) NOT NULL DEFAULT '',restock_status VARCHAR(32) NOT NULL DEFAULT 'not_requested',created_by BIGINT UNSIGNED NULL,requested_at VARCHAR(40) NOT NULL,confirmed_at VARCHAR(40) NULL,rejected_at VARCHAR(40) NULL,updated_at VARCHAR(40) NOT NULL,INDEX idx_order_refunds_order(order_id,status,requested_at),CONSTRAINT fk_order_refund_admin FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS support_cases (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,case_key VARCHAR(64) NOT NULL UNIQUE,order_id VARCHAR(100) NOT NULL DEFAULT '',user_id BIGINT UNSIGNED NULL,contact_id BIGINT UNSIGNED NULL,email VARCHAR(190) NOT NULL DEFAULT '',subject VARCHAR(255) NOT NULL,issue_type VARCHAR(60) NOT NULL DEFAULT 'other',priority VARCHAR(20) NOT NULL DEFAULT 'normal',status VARCHAR(32) NOT NULL DEFAULT 'open',source VARCHAR(40) NOT NULL DEFAULT 'fan',assigned_to BIGINT UNSIGNED NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,closed_at VARCHAR(40) NULL,INDEX idx_support_cases_status(status,priority,updated_at),INDEX idx_support_cases_order(order_id,updated_at),CONSTRAINT fk_support_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,CONSTRAINT fk_support_contact FOREIGN KEY(contact_id) REFERENCES fan_contacts(id) ON DELETE SET NULL,CONSTRAINT fk_support_assignee FOREIGN KEY(assigned_to) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS support_messages (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,case_id BIGINT UNSIGNED NOT NULL,request_key VARCHAR(190) NOT NULL UNIQUE,actor_type VARCHAR(20) NOT NULL,actor_user_id BIGINT UNSIGNED NULL,message TEXT NOT NULL,created_at VARCHAR(40) NOT NULL,INDEX idx_support_messages_case(case_id,id),CONSTRAINT fk_support_message_case FOREIGN KEY(case_id) REFERENCES support_cases(id) ON DELETE CASCADE,CONSTRAINT fk_support_message_user FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS order_ops_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,order_id VARCHAR(100) NOT NULL DEFAULT '',case_id BIGINT UNSIGNED NULL,event_type VARCHAR(80) NOT NULL,external_key VARCHAR(190) NOT NULL UNIQUE,actor_user_id BIGINT UNSIGNED NULL,metadata_json LONGTEXT NOT NULL,created_at VARCHAR(40) NOT NULL,INDEX idx_order_ops_events_order(order_id,created_at),CONSTRAINT fk_order_ops_case FOREIGN KEY(case_id) REFERENCES support_cases(id) ON DELETE SET NULL,CONSTRAINT fk_order_ops_actor FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    }$done=true;
}
function sf_fulfillment_write_order(array $order): void {
    $id=(string)($order['id']??'');if(!preg_match('/^SF-[A-Z0-9-]+$/',$id))throw new InvalidArgumentException('Invalid order.');
    sf_write_json(SF_ROOT.'/storage/orders/'.$id.'.json',$order);
}
function sf_fulfillment_event(string $orderId,string $eventType,array $meta=[],?int $actorId=null,?int $caseId=null,string $externalKey=''): void {
    sf_fulfillment_ensure_schema();$externalKey=$externalKey!==''?$externalKey:sf_fulfillment_request_key($eventType);$q=sf_db()->prepare('INSERT INTO order_ops_events(order_id,case_id,event_type,external_key,actor_user_id,metadata_json,created_at) VALUES(?,?,?,?,?,?,?)');
    try{$q->execute([$orderId,$caseId,$eventType,$externalKey,$actorId?:null,sf_fulfillment_json($meta),gmdate('c')]);}catch(PDOException $e){if(!in_array((string)$e->getCode(),['23000','19'],true))throw $e;}
}
function sf_fulfillment_contact_for_order(array $order): ?array {
    $email=strtolower(trim((string)($order['customer']['email']??'')));if($email==='')return null;try{return sf_crm_upsert_contact($email,(string)($order['customer']['name']??''),'order_care',!empty($order['user_id'])?(int)$order['user_id']:null,null,'customer');}catch(Throwable $e){return null;}
}
function sf_fulfillment_shipments(string $orderId): array {sf_fulfillment_ensure_schema();$q=sf_db()->prepare('SELECT * FROM order_shipments WHERE order_id=? ORDER BY id DESC');$q->execute([$orderId]);return $q->fetchAll();}
function sf_fulfillment_refunds(string $orderId): array {sf_fulfillment_ensure_schema();$q=sf_db()->prepare('SELECT * FROM order_refunds WHERE order_id=? ORDER BY id DESC');$q->execute([$orderId]);return $q->fetchAll();}
function sf_fulfillment_case_messages(int $caseId): array {sf_fulfillment_ensure_schema();$q=sf_db()->prepare('SELECT * FROM support_messages WHERE case_id=? ORDER BY id');$q->execute([$caseId]);return $q->fetchAll();}
function sf_fulfillment_cases(string $orderId='',?int $userId=null,int $limit=100): array {
    sf_fulfillment_ensure_schema();$where=[];$args=[];if($orderId!==''){$where[]='order_id=?';$args[]=$orderId;}if($userId){$where[]='user_id=?';$args[]=$userId;}$sql='SELECT * FROM support_cases'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY CASE priority WHEN "urgent" THEN 0 WHEN "high" THEN 1 WHEN "normal" THEN 2 ELSE 3 END,updated_at DESC LIMIT '.max(1,min(500,$limit));$q=sf_db()->prepare($sql);$q->execute($args);$rows=$q->fetchAll();foreach($rows as &$r)$r['messages']=sf_fulfillment_case_messages((int)$r['id']);unset($r);return $rows;
}
function sf_fulfillment_order_snapshot(string $orderId): array {
    $o=sf_read_order($orderId);if(!$o)throw new InvalidArgumentException('Order not found.');unset($o['confirmation_token_hash']);return ['order'=>$o,'shipments'=>sf_fulfillment_shipments($orderId),'refunds'=>sf_fulfillment_refunds($orderId),'cases'=>sf_fulfillment_cases($orderId,null,50)];
}
function sf_fulfillment_update_summary(array &$order,string $status,string $carrier='',string $tracking='',string $trackingUrl='',string $note='',?int $adminId=null): void {
    $allowed=['pending','preparing','in_production','packed','shipped','delivered','exception','returned','canceled'];if(!in_array($status,$allowed,true))throw new InvalidArgumentException('Invalid fulfillment status.');$now=gmdate('c');$previous=(string)($order['fulfillment']['status']??(!empty($order['quote']['physical'])?'pending':'not_required'));
    $order['fulfillment']=array_merge((array)($order['fulfillment']??[]),['status'=>$status,'carrier'=>$carrier,'tracking_number'=>$tracking,'tracking_url'=>$trackingUrl,'note'=>$note,'updated_at'=>$now,'updated_by'=>$adminId]);
    $order['timeline']=is_array($order['timeline']??null)?$order['timeline']:[];$order['timeline'][]=['type'=>'fulfillment','status'=>$status,'label'=>'Fulfillment '.ucwords(str_replace('_',' ',$status)),'created_at'=>$now];
    if(in_array($status,['shipped','delivered'],true))sf_commerce_mark_order_sold((string)$order['id']);
    if($status==='canceled'&&!in_array($previous,['shipped','delivered'],true))sf_commerce_release_order_inventory((string)$order['id'],'fulfillment_canceled',$adminId);
}
function sf_fulfillment_save_shipment(string $orderId,array $raw,int $adminId): array {
    sf_fulfillment_ensure_schema();$order=sf_read_order($orderId);if(!$order)throw new InvalidArgumentException('Order not found.');if(empty($order['quote']['physical']))throw new InvalidArgumentException('This order does not require physical fulfillment.');
    $id=max(0,(int)($raw['id']??0));$requestKey=sf_clean_text($raw['request_key']??'',190);if($requestKey==='')$requestKey=sf_fulfillment_request_key('shipment');$status=(string)($raw['status']??'label_created');$allowed=['label_created','in_transit','out_for_delivery','delivered','exception','returned','canceled'];if(!in_array($status,$allowed,true))throw new InvalidArgumentException('Invalid shipment status.');
    $carrier=sf_clean_text($raw['carrier']??'',100);$service=sf_clean_text($raw['service']??'',100);$tracking=sf_clean_text($raw['tracking_number']??'',160);$trackingUrl=trim((string)($raw['tracking_url']??''));if($trackingUrl!==''&&!filter_var($trackingUrl,FILTER_VALIDATE_URL))throw new InvalidArgumentException('Tracking URL is invalid.');$eta=sf_clean_text($raw['estimated_delivery_at']??'',40);$note=sf_clean_text($raw['note']??'',2000);$now=gmdate('c');
    if($id){$q=sf_db()->prepare('SELECT * FROM order_shipments WHERE id=? AND order_id=?');$q->execute([$id,$orderId]);$existing=$q->fetch();if(!$existing)throw new InvalidArgumentException('Shipment not found.');$shipped=$existing['shipped_at'];$delivered=$existing['delivered_at'];if(in_array($status,['in_transit','out_for_delivery','delivered'],true)&&!$shipped)$shipped=$now;if($status==='delivered'&&!$delivered)$delivered=$now;$q=sf_db()->prepare('UPDATE order_shipments SET status=?,carrier=?,service=?,tracking_number=?,tracking_url=?,estimated_delivery_at=?,shipped_at=?,delivered_at=?,note=?,updated_at=? WHERE id=?');$q->execute([$status,$carrier,$service,$tracking,$trackingUrl,$eta?:null,$shipped,$delivered,$note,$now,$id]);}
    else{$shipped=in_array($status,['in_transit','out_for_delivery','delivered'],true)?$now:null;$delivered=$status==='delivered'?$now:null;$q=sf_db()->prepare('INSERT INTO order_shipments(order_id,request_key,status,carrier,service,tracking_number,tracking_url,estimated_delivery_at,shipped_at,delivered_at,note,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');try{$q->execute([$orderId,$requestKey,$status,$carrier,$service,$tracking,$trackingUrl,$eta?:null,$shipped,$delivered,$note,$adminId?:null,$now,$now]);$id=(int)sf_db()->lastInsertId();}catch(PDOException $e){if(in_array((string)$e->getCode(),['23000','19'],true)){$q=sf_db()->prepare('SELECT id FROM order_shipments WHERE request_key=?');$q->execute([$requestKey]);$id=(int)$q->fetchColumn();}else throw $e;}}
    $summaryStatus=$status==='label_created'?'packed':($status==='in_transit'?'shipped':($status==='out_for_delivery'?'shipped':$status));sf_fulfillment_update_summary($order,$summaryStatus,$carrier,$tracking,$trackingUrl,$note,$adminId);sf_fulfillment_write_order($order);sf_fulfillment_event($orderId,'shipment_'.$status,['shipment_id'=>$id,'carrier'=>$carrier,'tracking_number'=>$tracking],$adminId,null,'shipment-event:'.$id.':'.$status);
    $contact=sf_fulfillment_contact_for_order($order);if($contact)sf_crm_log_event((int)$contact['id'],!empty($order['user_id'])?(int)$order['user_id']:null,'order_'.$summaryStatus,'Order '.$orderId.' '.str_replace('_',' ',$summaryStatus),'order',$orderId,['shipment_id'=>$id,'carrier'=>$carrier,'tracking_number'=>$tracking]);
    $uid=(int)($order['user_id']??0);$msg='Order '.$orderId.' is '.ucwords(str_replace('_',' ',$summaryStatus)).'.';if($tracking!=='')$msg.=' Tracking: '.$tracking.'.';if($uid>0){sf_notify_user($uid,'fulfillment','Order '.$orderId.' updated',$msg,'?view=order&id='.rawurlencode($orderId));sf_log_user_activity($uid,'order_fulfillment',$msg,'order',$orderId,['status'=>$summaryStatus,'shipment_id'=>$id]);}
    $email=(string)($order['customer']['email']??'');if(filter_var($email,FILTER_VALIDATE_EMAIL)&&in_array($status,['in_transit','out_for_delivery','delivered','exception'],true)){try{sf_transactional_email($uid,$email,'Stonefellow order '.$orderId.' update',$msg.($trackingUrl!==''?"\n".$trackingUrl:'').($note!==''?"\n\n".$note:''),'order_fulfillment');}catch(Throwable $e){}}
    $q=sf_db()->prepare('SELECT * FROM order_shipments WHERE id=?');$q->execute([$id]);return $q->fetch()?:[];
}
function sf_fulfillment_request_refund(string $orderId,array $raw,int $adminId=0): array {
    sf_fulfillment_ensure_schema();$order=sf_read_order($orderId);if(!$order)throw new InvalidArgumentException('Order not found.');$total=max(0,(int)($order['quote']['total_cents']??0));$amount=max(1,min($total,(int)($raw['amount_cents']??$total)));$reason=sf_clean_text($raw['reason']??'',2000);if($reason==='')throw new InvalidArgumentException('Refund reason is required.');$key=sf_clean_text($raw['request_key']??'',190);if($key==='')$key=sf_fulfillment_request_key('refund');$now=gmdate('c');
    $q=sf_db()->prepare('INSERT INTO order_refunds(order_id,request_key,amount_cents,reason,status,provider_reference,restock_status,created_by,requested_at,confirmed_at,rejected_at,updated_at) VALUES(?,?,?,?,"requested","","not_requested",?,?,NULL,NULL,?)');try{$q->execute([$orderId,$key,$amount,$reason,$adminId?:null,$now,$now]);$id=(int)sf_db()->lastInsertId();}catch(PDOException $e){if(in_array((string)$e->getCode(),['23000','19'],true)){$q=sf_db()->prepare('SELECT id FROM order_refunds WHERE request_key=?');$q->execute([$key]);$id=(int)$q->fetchColumn();}else throw $e;}
    sf_fulfillment_event($orderId,'refund_requested',['refund_id'=>$id,'amount_cents'=>$amount,'reason'=>$reason],$adminId,null,'refund-request:'.$id);$contact=sf_fulfillment_contact_for_order($order);if($contact)sf_crm_log_event((int)$contact['id'],!empty($order['user_id'])?(int)$order['user_id']:null,'refund_requested','Refund requested for order '.$orderId,'order',$orderId,['refund_id'=>$id,'amount_cents'=>$amount]);$q=sf_db()->prepare('SELECT * FROM order_refunds WHERE id=?');$q->execute([$id]);return $q->fetch()?:[];
}
function sf_fulfillment_confirm_refund(int $refundId,int $adminId,string $providerReference='',bool $restock=false): array {
    sf_fulfillment_ensure_schema();$q=sf_db()->prepare('SELECT * FROM order_refunds WHERE id=?');$q->execute([$refundId]);$r=$q->fetch();if(!$r)throw new InvalidArgumentException('Refund not found.');if($r['status']==='confirmed')return $r;if($r['status']==='rejected')throw new RuntimeException('Rejected refund cannot be confirmed.');$order=sf_read_order((string)$r['order_id']);if(!$order)throw new InvalidArgumentException('Order not found.');$now=gmdate('c');$restockStatus='not_requested';
    if($restock){$ful=(string)($order['fulfillment']['status']??'');if(in_array($ful,['shipped','delivered'],true))throw new RuntimeException('Shipped merchandise may only be restocked after a returned shipment is recorded.');$released=sf_commerce_release_order_inventory((string)$r['order_id'],'refund_restock',$adminId);$restockStatus=$released>0?'restocked':'not_applicable';}
    $q=sf_db()->prepare("UPDATE order_refunds SET status='confirmed',provider_reference=?,restock_status=?,confirmed_at=?,updated_at=? WHERE id=?");$q->execute([sf_clean_text($providerReference,255),$restockStatus,$now,$now,$refundId]);
    $confirmedTotal=0;$q=sf_db()->prepare("SELECT COALESCE(SUM(amount_cents),0) FROM order_refunds WHERE order_id=? AND status='confirmed'");$q->execute([(string)$r['order_id']]);$confirmedTotal=(int)$q->fetchColumn();$orderTotal=(int)($order['quote']['total_cents']??0);$order['status']=$confirmedTotal>=$orderTotal?'refunded':'partially_refunded';$order['payment']['status']=$order['status'];$order['timeline']=is_array($order['timeline']??null)?$order['timeline']:[];$order['timeline'][]=['type'=>'refund','status'=>'confirmed','label'=>'Refund confirmed · '.sf_money((int)$r['amount_cents']),'created_at'=>$now];sf_fulfillment_write_order($order);
    sf_fulfillment_event((string)$r['order_id'],'refund_confirmed',['refund_id'=>$refundId,'amount_cents'=>(int)$r['amount_cents'],'provider_reference'=>$providerReference,'restock_status'=>$restockStatus],$adminId,null,'refund-confirm:'.$refundId);$contact=sf_fulfillment_contact_for_order($order);if($contact)sf_crm_log_event((int)$contact['id'],!empty($order['user_id'])?(int)$order['user_id']:null,'refund_confirmed','Refund confirmed for order '.$r['order_id'],'order',(string)$r['order_id'],['refund_id'=>$refundId,'amount_cents'=>(int)$r['amount_cents']]);$uid=(int)($order['user_id']??0);if($uid>0)sf_notify_user($uid,'order','Refund confirmed','A refund of '.sf_money((int)$r['amount_cents']).' was confirmed for order '.$r['order_id'].'.','?view=order&id='.rawurlencode((string)$r['order_id']));
    $q=sf_db()->prepare('SELECT * FROM order_refunds WHERE id=?');$q->execute([$refundId]);return $q->fetch()?:[];
}
function sf_fulfillment_reject_refund(int $refundId,int $adminId,string $reason=''): array {
    sf_fulfillment_ensure_schema();$q=sf_db()->prepare('SELECT * FROM order_refunds WHERE id=?');$q->execute([$refundId]);$r=$q->fetch();if(!$r)throw new InvalidArgumentException('Refund not found.');if($r['status']==='confirmed')throw new RuntimeException('Confirmed refund cannot be rejected.');$now=gmdate('c');$q=sf_db()->prepare("UPDATE order_refunds SET status='rejected',provider_reference=?,rejected_at=?,updated_at=? WHERE id=?");$q->execute([sf_clean_text($reason,255),$now,$now,$refundId]);sf_fulfillment_event((string)$r['order_id'],'refund_rejected',['refund_id'=>$refundId,'reason'=>$reason],$adminId,null,'refund-reject:'.$refundId);$q=sf_db()->prepare('SELECT * FROM order_refunds WHERE id=?');$q->execute([$refundId]);return $q->fetch()?:[];
}
function sf_fulfillment_restock_return(string $orderId,int $adminId,string $reason='return_received'): int {
    sf_fulfillment_ensure_schema();$pdo=sf_db();$q=$pdo->prepare("SELECT * FROM store_order_items WHERE order_id=? AND inventory_status='sold'");$q->execute([$orderId]);$rows=$q->fetchAll();if(!$rows)return 0;$count=0;$now=gmdate('c');$pdo->beginTransaction();try{foreach($rows as $r){$qty=(int)$r['quantity'];$source=(string)$r['inventory_source'];$before=null;$after=null;if($source==='variant'&&!empty($r['variant_id'])){$q=$pdo->prepare('SELECT inventory_qty FROM store_variants WHERE id=?');$q->execute([(int)$r['variant_id']]);$before=(int)$q->fetchColumn();$pdo->prepare('UPDATE store_variants SET inventory_qty=inventory_qty+?,updated_at=? WHERE id=?')->execute([$qty,$now,(int)$r['variant_id']]);$after=$before+$qty;}elseif($source==='product'){$q=$pdo->prepare('SELECT inventory_qty FROM store_products WHERE id=?');$q->execute([(string)$r['product_id']]);$before=(int)$q->fetchColumn();$pdo->prepare('UPDATE store_products SET inventory_qty=inventory_qty+?,updated_at=? WHERE id=?')->execute([$qty,$now,(string)$r['product_id']]);$after=$before+$qty;}if($source!=='unlimited'){$key='return:'.$orderId.':'.$r['line_index'];try{$pdo->prepare('INSERT INTO store_inventory_events(product_id,variant_id,order_id,external_key,delta,before_qty,after_qty,reason,actor_user_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([(string)$r['product_id'],!empty($r['variant_id'])?(int)$r['variant_id']:null,$orderId,$key,$qty,$before,$after,$reason,$adminId?:null,$now]);}catch(PDOException $e){if(!in_array((string)$e->getCode(),['23000','19'],true))throw $e;continue;}$count+=$qty;}$pdo->prepare("UPDATE store_order_items SET inventory_status='returned',updated_at=? WHERE id=?")->execute([$now,(int)$r['id']]);}$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}if($count>0)sf_fulfillment_event($orderId,'return_restocked',['units'=>$count,'reason'=>$reason],$adminId,null,'return-restock:'.$orderId);return $count;
}
function sf_fulfillment_open_case(array $user,array $raw,string $source='fan'): array {
    sf_fulfillment_ensure_schema();$orderId=sf_clean_text($raw['order_id']??'',100);$subject=sf_clean_text($raw['subject']??'',255);$message=sf_clean_text($raw['message']??'',8000);$issue=(string)($raw['issue_type']??'other');if(!in_array($issue,['order_status','shipping','damaged','wrong_item','refund','download','billing','other'],true))$issue='other';if($subject===''||$message==='')throw new InvalidArgumentException('Subject and message are required.');$order=$orderId!==''?sf_read_order($orderId):null;if($orderId!==''&&!$order)throw new InvalidArgumentException('Order not found.');if($order){$uid=(int)($order['user_id']??0);$email=strtolower((string)($order['customer']['email']??''));if($uid!==(int)$user['id']&&!($uid===0&&$email===strtolower((string)$user['email'])))throw new RuntimeException('You cannot open a case for this order.');}
    $contact=null;try{$contact=sf_crm_upsert_contact((string)$user['email'],(string)$user['display_name'],'support',(int)$user['id'],null,'customer');}catch(Throwable $e){}$now=gmdate('c');$caseKey=sf_fulfillment_case_key();$q=sf_db()->prepare('INSERT INTO support_cases(case_key,order_id,user_id,contact_id,email,subject,issue_type,priority,status,source,assigned_to,created_at,updated_at,closed_at) VALUES(?,?,?,?,?,?,?,"normal","open",?,NULL,?,?,NULL)');$q->execute([$caseKey,$orderId,(int)$user['id'],!empty($contact['id'])?(int)$contact['id']:null,strtolower((string)$user['email']),$subject,$issue,$source,$now,$now]);$id=(int)sf_db()->lastInsertId();sf_fulfillment_add_case_message($id,'fan',(int)$user['id'],$message,sf_fulfillment_request_key('case-open'));sf_fulfillment_event($orderId,'support_case_opened',['case_key'=>$caseKey,'issue_type'=>$issue],(int)$user['id'],$id,'case-open:'.$caseKey);if($contact)sf_crm_log_event((int)$contact['id'],(int)$user['id'],'support_case_opened','Opened support case '.$caseKey,$orderId!==''?'order':'support',$orderId!==''?$orderId:$caseKey,['issue_type'=>$issue,'subject'=>$subject]);return sf_fulfillment_case((int)$id)?:[];
}
function sf_fulfillment_case(int $id): ?array {sf_fulfillment_ensure_schema();$q=sf_db()->prepare('SELECT * FROM support_cases WHERE id=?');$q->execute([$id]);$r=$q->fetch();if(!$r)return null;$r['messages']=sf_fulfillment_case_messages($id);return $r;}
function sf_fulfillment_add_case_message(int $caseId,string $actorType,?int $actorUserId,string $message,string $requestKey=''): array {
    sf_fulfillment_ensure_schema();$case=sf_fulfillment_case($caseId);if(!$case)throw new InvalidArgumentException('Support case not found.');$message=sf_clean_text($message,8000);if($message==='')throw new InvalidArgumentException('Message is required.');if(!in_array($actorType,['fan','admin','agent','system'],true))throw new InvalidArgumentException('Invalid support actor.');$requestKey=$requestKey!==''?$requestKey:sf_fulfillment_request_key('case-message');$now=gmdate('c');$q=sf_db()->prepare('INSERT INTO support_messages(case_id,request_key,actor_type,actor_user_id,message,created_at) VALUES(?,?,?,?,?,?)');try{$q->execute([$caseId,$requestKey,$actorType,$actorUserId?:null,$message,$now]);}catch(PDOException $e){if(!in_array((string)$e->getCode(),['23000','19'],true))throw $e;}$next=$actorType==='admin'?'waiting_on_fan':'waiting_on_admin';sf_db()->prepare('UPDATE support_cases SET status=?,updated_at=? WHERE id=? AND status NOT IN ("resolved","closed")')->execute([$next,$now,$caseId]);sf_fulfillment_event((string)$case['order_id'],'support_message',['case_key'=>$case['case_key'],'actor_type'=>$actorType],$actorUserId,$caseId,$requestKey.':event');
    if($actorType==='admin'&&!empty($case['user_id'])){$uid=(int)$case['user_id'];sf_notify_user($uid,'support','Support reply · '.$case['case_key'],$message,$case['order_id']!==''?'?view=order&id='.rawurlencode((string)$case['order_id']):'?view=account');try{sf_transactional_email($uid,(string)$case['email'],'Stonefellow support · '.$case['case_key'],$message,'support_reply');}catch(Throwable $e){}}
    return sf_fulfillment_case($caseId)?:[];
}
function sf_fulfillment_update_case(int $caseId,array $raw,int $adminId): array {
    sf_fulfillment_ensure_schema();$case=sf_fulfillment_case($caseId);if(!$case)throw new InvalidArgumentException('Support case not found.');$status=(string)($raw['status']??$case['status']);$priority=(string)($raw['priority']??$case['priority']);if(!in_array($status,['open','waiting_on_fan','waiting_on_admin','resolved','closed'],true))throw new InvalidArgumentException('Invalid case status.');if(!in_array($priority,['low','normal','high','urgent'],true))throw new InvalidArgumentException('Invalid case priority.');$assigned=array_key_exists('assigned_to',$raw)?max(0,(int)$raw['assigned_to']):(int)($case['assigned_to']??0);$now=gmdate('c');$closed=in_array($status,['resolved','closed'],true)?($case['closed_at']?:$now):null;sf_db()->prepare('UPDATE support_cases SET status=?,priority=?,assigned_to=?,updated_at=?,closed_at=? WHERE id=?')->execute([$status,$priority,$assigned?:null,$now,$closed,$caseId]);sf_fulfillment_event((string)$case['order_id'],'support_case_'.$status,['case_key'=>$case['case_key'],'priority'=>$priority],$adminId,$caseId,'case-state:'.$caseId.':'.$status.':'.substr(hash('sha256',$priority),0,8));return sf_fulfillment_case($caseId)?:[];
}
function sf_fulfillment_summary(): array {
    sf_fulfillment_ensure_schema();$pdo=sf_db();$open=(int)$pdo->query("SELECT COUNT(*) FROM support_cases WHERE status NOT IN ('resolved','closed')")->fetchColumn();$urgent=(int)$pdo->query("SELECT COUNT(*) FROM support_cases WHERE status NOT IN ('resolved','closed') AND priority IN ('high','urgent')")->fetchColumn();$shipments=(int)$pdo->query("SELECT COUNT(*) FROM order_shipments WHERE status NOT IN ('delivered','returned','canceled')")->fetchColumn();$refunds=(int)$pdo->query("SELECT COUNT(*) FROM order_refunds WHERE status='requested'")->fetchColumn();$delivered=(int)$pdo->query("SELECT COUNT(*) FROM order_shipments WHERE status='delivered'")->fetchColumn();return ['open_cases'=>$open,'high_priority_cases'=>$urgent,'active_shipments'=>$shipments,'refund_requests'=>$refunds,'delivered_shipments'=>$delivered];
}
function sf_fulfillment_recent_orders(int $limit=100): array {
    $rows=[];foreach(sf_admin_orders() as $o){$rows[]=['id'=>(string)($o['id']??''),'status'=>(string)($o['status']??''),'created_at'=>(string)($o['created_at']??''),'customer_name'=>(string)($o['customer']['name']??''),'customer_email'=>(string)($o['customer']['email']??''),'total_cents'=>(int)($o['quote']['total_cents']??0),'physical'=>!empty($o['quote']['physical']),'fulfillment_status'=>(string)($o['fulfillment']['status']??(!empty($o['quote']['physical'])?'pending':'not_required')),'tracking_number'=>(string)($o['fulfillment']['tracking_number']??'')];if(count($rows)>=$limit)break;}return $rows;
}
function sf_fulfillment_agent_context(int $userId): string {
    if($userId<=0)return '';$out=[];foreach(sf_fulfillment_recent_orders(120) as $o){$full=sf_read_order((string)$o['id']);if(!$full)continue;$owner=(int)($full['user_id']??0);if($owner!==$userId)continue;$ships=sf_fulfillment_shipments((string)$o['id']);$refunds=sf_fulfillment_refunds((string)$o['id']);$cases=sf_fulfillment_cases((string)$o['id'],$userId,10);$out[]='- order '.$o['id'].' | order '.$o['status'].' | fulfillment '.$o['fulfillment_status'].' | tracking '.($o['tracking_number']?:'none').' | shipments '.count($ships).' | refunds '.count($refunds).' | support cases '.count($cases);if(count($out)>=8)break;}return $out?"YOUR ORDER + SUPPORT STATUS\n".implode("\n",$out):'';
}
