<?php
declare(strict_types=1);

function sf_growth_percent(int|float $n,int|float $d): float {return $d>0?round(((float)$n/(float)$d)*100,1):0.0;}
function sf_growth_since(int $days): string {$days=max(1,min(3650,$days));return gmdate('c',time()-$days*86400);}
function sf_growth_safe(callable $fn,mixed $fallback=[]): mixed {try{return $fn();}catch(Throwable $e){return $fallback;}}

function sf_growth_orders(int $days): array {
    $since=sf_growth_since($days);$rows=function_exists('sf_analytics_order_rows')?sf_analytics_order_rows($since,null):[];$paid=[];$revenue=0;$byType=['merch'=>0,'custom_media'=>0,'digital_music'=>0,'other'=>0];$daily=[];$supporters=[];
    foreach($rows as $o){
        if(function_exists('sf_analytics_paid_order')&&!sf_analytics_paid_order($o))continue;
        $paid[]=$o;$total=(int)($o['quote']['total_cents']??0);$revenue+=$total;$day=substr((string)($o['created_at']??''),0,10);if($day!==''){$daily[$day]??=['orders'=>0,'revenue_cents'=>0];$daily[$day]['orders']++;$daily[$day]['revenue_cents']+=$total;}
        $uid=(int)($o['user_id']??0);$email=strtolower((string)($o['customer']['email']??''));$key=$uid>0?'u:'.$uid:'e:'.$email;if($key!=='e:'){$supporters[$key]??=['user_id'=>$uid,'email'=>$email,'name'=>(string)($o['customer']['name']??''),'order_revenue_cents'=>0,'orders'=>0];$supporters[$key]['order_revenue_cents']+=$total;$supporters[$key]['orders']++;}
        foreach((array)($o['quote']['items']??[]) as $item){$type=(string)($item['type']??'');$amount=(int)($item['price_cents']??($item['subtotal_cents']??0));if($type==='merch')$byType['merch']+=$amount;elseif($type==='custom_media')$byType['custom_media']+=$amount;elseif(in_array($type,['track','release','digital'],true))$byType['digital_music']+=$amount;else $byType['other']+=$amount;}
    }
    return ['orders'=>$paid,'paid_orders'=>count($paid),'revenue_cents'=>$revenue,'by_type'=>$byType,'daily'=>$daily,'supporters'=>$supporters];
}
function sf_growth_refunds(int $days): array {
    $since=sf_growth_since($days);return sf_growth_safe(function()use($since){sf_fulfillment_ensure_schema();$q=sf_db()->prepare("SELECT COUNT(DISTINCT order_id) c,COALESCE(SUM(amount_cents),0) amount FROM order_refunds WHERE status='confirmed' AND confirmed_at>=?");$q->execute([$since]);$r=$q->fetch()?:[];return ['confirmed'=>(int)($r['c']??0),'amount_cents'=>(int)($r['amount']??0)];},['confirmed'=>0,'amount_cents'=>0]);
}
function sf_growth_membership(int $days): array {
    $since=sf_growth_since($days);$summary=function_exists('sf_membership_summary')?sf_membership_summary():['active_members'=>0,'tiers'=>[]];$billing=sf_growth_safe(function()use($since){sf_billing_ensure_schema();$q=sf_db()->prepare("SELECT COUNT(*) invoices,COALESCE(SUM(amount_paid_cents),0) revenue FROM billing_invoices WHERE status IN ('paid','succeeded') AND COALESCE(paid_at,created_at)>=?");$q->execute([$since]);$r=$q->fetch()?:[];$q=sf_db()->prepare("SELECT b.user_id,COALESCE(SUM(b.amount_paid_cents),0) revenue,COUNT(*) invoices,u.email,u.display_name FROM billing_invoices b LEFT JOIN users u ON u.id=b.user_id WHERE b.status IN ('paid','succeeded') AND COALESCE(b.paid_at,b.created_at)>=? GROUP BY b.user_id,u.email,u.display_name ORDER BY revenue DESC");$q->execute([$since]);return ['invoices'=>(int)($r['invoices']??0),'revenue_cents'=>(int)($r['revenue']??0),'supporters'=>$q->fetchAll()];},['invoices'=>0,'revenue_cents'=>0,'supporters'=>[]]);
    $canceling=sf_growth_safe(function(){sf_billing_ensure_schema();return (int)sf_db()->query("SELECT COUNT(*) FROM user_subscriptions WHERE cancel_at_period_end=1 AND status IN ('active','trialing')")->fetchColumn();},0);
    return ['active_members'=>(int)($summary['active_members']??0),'tiers'=>$summary['tiers']??[],'published_content'=>(int)($summary['published_content']??0),'invoices'=>$billing['invoices'],'revenue_cents'=>$billing['revenue_cents'],'supporters'=>$billing['supporters'],'cancel_at_period_end'=>$canceling];
}
function sf_growth_crm(int $days): array {
    $since=sf_growth_since($days);return sf_growth_safe(function()use($since){sf_crm_ensure_schema();$pdo=sf_db();$q=$pdo->prepare('SELECT COUNT(*) FROM fan_contacts WHERE created_at>=?');$q->execute([$since]);$new=(int)$q->fetchColumn();$q=$pdo->prepare('SELECT COUNT(*) FROM fan_contacts WHERE marketing_opt_in=1 AND marketing_opt_in_at IS NOT NULL AND marketing_opt_in_at>=?');$q->execute([$since]);$newsletterNew=(int)$q->fetchColumn();$total=(int)$pdo->query('SELECT COUNT(*) FROM fan_contacts')->fetchColumn();$newsletter=(int)$pdo->query('SELECT COUNT(*) FROM fan_contacts WHERE marketing_opt_in=1')->fetchColumn();$stages=[];foreach($pdo->query('SELECT status,COUNT(*) c FROM fan_contacts GROUP BY status ORDER BY c DESC')->fetchAll() as $r)$stages[(string)$r['status']]=(int)$r['c'];$sources=[];$q=$pdo->prepare('SELECT source,COUNT(*) c FROM fan_contacts WHERE created_at>=? GROUP BY source ORDER BY c DESC');$q->execute([$since]);foreach($q->fetchAll() as $r)$sources[]=['source'=>(string)$r['source'],'count'=>(int)$r['c']];$weekly=[];$q=$pdo->prepare('SELECT created_at,status,marketing_opt_in FROM fan_contacts WHERE created_at>=? ORDER BY created_at');$q->execute([$since]);foreach($q->fetchAll() as $r){$ts=strtotime((string)$r['created_at'])?:time();$week=gmdate('o-\WW',$ts);$weekly[$week]??=['week'=>$week,'contacts'=>0,'newsletter'=>0,'customer_or_member'=>0];$weekly[$week]['contacts']++;if(!empty($r['marketing_opt_in']))$weekly[$week]['newsletter']++;if(in_array((string)$r['status'],['customer','member'],true))$weekly[$week]['customer_or_member']++;}return ['contacts'=>$total,'new_contacts'=>$new,'newsletter'=>$newsletter,'new_newsletter'=>$newsletterNew,'stages'=>$stages,'sources'=>$sources,'cohorts'=>array_values($weekly)];},['contacts'=>0,'new_contacts'=>0,'newsletter'=>0,'new_newsletter'=>0,'stages'=>[],'sources'=>[],'cohorts'=>[]]);
}
function sf_growth_campaigns(int $days): array {
    $since=sf_growth_since($days);return sf_growth_safe(function()use($since){sf_campaign_ensure_schema();$pdo=sf_db();$q=$pdo->prepare("SELECT c.id,c.name,c.goal,c.status,COUNT(DISTINCT p.id) participants,SUM(CASE WHEN p.converted_at IS NOT NULL THEN 1 ELSE 0 END) converted FROM campaigns c LEFT JOIN campaign_participants p ON p.campaign_id=c.id AND p.entered_at>=? GROUP BY c.id,c.name,c.goal,c.status ORDER BY participants DESC,c.id DESC");$q->execute([$since]);$rows=[];$attributedRevenue=0;$attributedOrders=0;$participants=0;$converted=0;
    foreach($q->fetchAll() as $r){$cid=(int)$r['id'];$eq=$pdo->prepare("SELECT metadata_json FROM campaign_events WHERE campaign_id=? AND created_at>=? AND event_type IN ('purchase_attributed','offer_redeemed')");$eq->execute([$cid,$since]);$orders=[];$revenue=0;foreach($eq->fetchAll(PDO::FETCH_COLUMN) as $meta){$m=sf_campaign_decode($meta,[]);$oid=(string)($m['order_id']??'');if($oid!==''&&!isset($orders[$oid])){$orders[$oid]=true;$revenue+=(int)($m['total_cents']??0);}}
      $row=['id'=>$cid,'name'=>(string)$r['name'],'goal'=>(string)$r['goal'],'status'=>(string)$r['status'],'participants'=>(int)$r['participants'],'converted'=>(int)$r['converted'],'conversion_rate'=>sf_growth_percent((int)$r['converted'],(int)$r['participants']),'attributed_orders'=>count($orders),'attributed_revenue_cents'=>$revenue];$rows[]=$row;$participants+=$row['participants'];$converted+=$row['converted'];$attributedOrders+=$row['attributed_orders'];$attributedRevenue+=$row['attributed_revenue_cents'];}
    return ['campaigns'=>$rows,'participants'=>$participants,'converted'=>$converted,'conversion_rate'=>sf_growth_percent($converted,$participants),'attributed_orders'=>$attributedOrders,'attributed_revenue_cents'=>$attributedRevenue];},['campaigns'=>[],'participants'=>0,'converted'=>0,'conversion_rate'=>0,'attributed_orders'=>0,'attributed_revenue_cents'=>0]);
}
function sf_growth_automation(int $days): array {
    $since=sf_growth_since($days);return sf_growth_safe(function()use($since){sf_automation_ensure_schema();$pdo=sf_db();$q=$pdo->prepare("SELECT a.id,a.name,COUNT(r.id) runs,SUM(CASE WHEN r.status='completed' THEN 1 ELSE 0 END) completed,SUM(CASE WHEN r.status='failed' THEN 1 ELSE 0 END) failed,SUM(CASE WHEN r.status='waiting' THEN 1 ELSE 0 END) waiting FROM lifecycle_automations a LEFT JOIN lifecycle_automation_runs r ON r.automation_id=a.id AND r.created_at>=? GROUP BY a.id,a.name ORDER BY runs DESC,a.id DESC");$q->execute([$since]);$rows=[];$runs=$done=$failed=$waiting=0;foreach($q->fetchAll() as $r){$row=['id'=>(int)$r['id'],'name'=>(string)$r['name'],'runs'=>(int)$r['runs'],'completed'=>(int)$r['completed'],'failed'=>(int)$r['failed'],'waiting'=>(int)$r['waiting']];$row['completion_rate']=sf_growth_percent($row['completed'],$row['runs']);$rows[]=$row;$runs+=$row['runs'];$done+=$row['completed'];$failed+=$row['failed'];$waiting+=$row['waiting'];}return ['automations'=>$rows,'runs'=>$runs,'completed'=>$done,'failed'=>$failed,'waiting'=>$waiting,'completion_rate'=>sf_growth_percent($done,$runs)];},['automations'=>[],'runs'=>0,'completed'=>0,'failed'=>0,'waiting'=>0,'completion_rate'=>0]);
}
function sf_growth_ticketing(int $days): array {
    $since=sf_growth_since($days);return sf_growth_safe(function()use($since){sf_ticketing_ensure_schema();$pdo=sf_db();$q=$pdo->prepare("SELECT COUNT(*) reservations,COALESCE(SUM(CASE WHEN status IN ('reserved','checked_in') THEN quantity ELSE 0 END),0) reserved_qty,COALESCE(SUM(CASE WHEN status='checked_in' THEN quantity ELSE 0 END),0) checked_in_qty,COALESCE(SUM(CASE WHEN status='cancelled' THEN quantity ELSE 0 END),0) cancelled_qty FROM ticket_reservations WHERE reserved_at>=?");$q->execute([$since]);$r=$q->fetch()?:[];$offers=[];$q=$pdo->query("SELECT id,show_id,title,offer_type,status,capacity,claimed_qty FROM ticket_offers WHERE status IN ('published','paused','closed') ORDER BY claimed_qty DESC,id DESC LIMIT 100");foreach($q->fetchAll() as $o){$cap=(int)$o['capacity'];$claimed=(int)$o['claimed_qty'];$offers[]=['id'=>(int)$o['id'],'show_id'=>(string)$o['show_id'],'title'=>(string)$o['title'],'offer_type'=>(string)$o['offer_type'],'status'=>(string)$o['status'],'capacity'=>$cap,'claimed_qty'=>$claimed,'fill_rate'=>$cap>0?sf_growth_percent($claimed,$cap):0];}return ['reservations'=>(int)($r['reservations']??0),'reserved_qty'=>(int)($r['reserved_qty']??0),'checked_in_qty'=>(int)($r['checked_in_qty']??0),'cancelled_qty'=>(int)($r['cancelled_qty']??0),'checkin_rate'=>sf_growth_percent((int)($r['checked_in_qty']??0),(int)($r['reserved_qty']??0)),'offers'=>$offers];},['reservations'=>0,'reserved_qty'=>0,'checked_in_qty'=>0,'cancelled_qty'=>0,'checkin_rate'=>0,'offers'=>[]]);
}
function sf_growth_merch(int $days): array {
    $since=sf_growth_since($days);return sf_growth_safe(function()use($since){sf_commerce_ensure_schema();$pdo=sf_db();$q=$pdo->prepare("SELECT product_id,title,SUM(quantity) units,SUM(subtotal_cents) revenue_cents,COUNT(DISTINCT order_id) orders FROM store_order_items WHERE inventory_status='sold' AND created_at>=? GROUP BY product_id,title ORDER BY revenue_cents DESC,units DESC LIMIT 50");$q->execute([$since]);$products=$q->fetchAll();$units=0;$revenue=0;foreach($products as &$p){$p['units']=(int)$p['units'];$p['revenue_cents']=(int)$p['revenue_cents'];$p['orders']=(int)$p['orders'];$units+=$p['units'];$revenue+=$p['revenue_cents'];}unset($p);$low=[];foreach(sf_commerce_products(false) as $p)if(!empty($p['low_stock'])&&($p['status']??'')==='active')$low[]=['id'=>$p['id'],'title'=>$p['title'],'inventory_qty'=>$p['inventory_qty']??null];return ['units'=>$units,'revenue_cents'=>$revenue,'products'=>$products,'low_stock'=>$low];},['units'=>0,'revenue_cents'=>0,'products'=>[],'low_stock'=>[]]);
}
function sf_growth_care(int $days): array {
    $since=sf_growth_since($days);return sf_growth_safe(function()use($since){sf_fulfillment_ensure_schema();$pdo=sf_db();$summary=sf_fulfillment_summary();$q=$pdo->prepare("SELECT COUNT(*) FROM support_cases WHERE created_at>=?");$q->execute([$since]);$opened=(int)$q->fetchColumn();$q=$pdo->prepare("SELECT COUNT(*) FROM support_cases WHERE closed_at IS NOT NULL AND closed_at>=?");$q->execute([$since]);$closed=(int)$q->fetchColumn();$q=$pdo->prepare("SELECT COALESCE(SUM(amount_cents),0) FROM order_refunds WHERE status='confirmed' AND confirmed_at>=?");$q->execute([$since]);$refund=(int)$q->fetchColumn();return ['opened_cases'=>$opened,'closed_cases'=>$closed,'resolution_rate'=>sf_growth_percent($closed,$opened),'refund_cents'=>$refund]+$summary;},['opened_cases'=>0,'closed_cases'=>0,'resolution_rate'=>0,'refund_cents'=>0,'open_cases'=>0,'high_priority_cases'=>0,'active_shipments'=>0,'refund_requests'=>0,'delivered_shipments'=>0]);
}
function sf_growth_top_supporters(array $orders,array $membership,int $days,int $limit=25): array {
    $map=$orders['supporters']??[];foreach((array)($membership['supporters']??[]) as $r){$uid=(int)($r['user_id']??0);$email=strtolower((string)($r['email']??''));$key=$uid>0?'u:'.$uid:'e:'.$email;if($key==='e:')continue;$map[$key]??=['user_id'=>$uid,'email'=>$email,'name'=>(string)($r['display_name']??''),'order_revenue_cents'=>0,'orders'=>0];$map[$key]['membership_revenue_cents']=($map[$key]['membership_revenue_cents']??0)+(int)($r['revenue']??0);$map[$key]['membership_invoices']=($map[$key]['membership_invoices']??0)+(int)($r['invoices']??0);}
    $since=sf_growth_since($days);$ticketByUser=sf_growth_safe(function()use($since){sf_ticketing_ensure_schema();$q=sf_db()->prepare("SELECT user_id,SUM(quantity) qty FROM ticket_reservations WHERE status IN ('reserved','checked_in') AND reserved_at>=? GROUP BY user_id");$q->execute([$since]);$out=[];foreach($q->fetchAll() as $r)$out[(int)$r['user_id']]=(int)$r['qty'];return $out;},[]);
    foreach($map as &$r){$r['membership_revenue_cents']=(int)($r['membership_revenue_cents']??0);$r['recorded_value_cents']=(int)$r['order_revenue_cents']+$r['membership_revenue_cents'];$r['ticket_qty']=$ticketByUser[(int)$r['user_id']]??0;if((int)$r['user_id']>0){$m=sf_growth_safe(fn()=>sf_membership_state((int)$r['user_id'],false),[]);$r['membership_tier']=(string)($m['package_name']??'');}}unset($r);$rows=array_values($map);usort($rows,fn($a,$b)=>($b['recorded_value_cents']<=>$a['recorded_value_cents'])?:($b['orders']<=>$a['orders']));return array_slice($rows,0,max(1,min(100,$limit)));
}
function sf_growth_daily(int $days,array $orders): array {
    $since=sf_growth_since($days);$daily=[];$touch=function(string $day)use(&$daily){if($day==='')return;$daily[$day]??=['day'=>$day,'orders'=>0,'order_revenue_cents'=>0,'new_contacts'=>0,'newsletter_optins'=>0,'ticket_qty'=>0,'campaign_entries'=>0];};
    foreach((array)($orders['daily']??[]) as $day=>$r){$touch($day);$daily[$day]['orders']=(int)$r['orders'];$daily[$day]['order_revenue_cents']=(int)$r['revenue_cents'];}
    sf_growth_safe(function()use($since,&$daily,$touch){$pdo=sf_db();$q=$pdo->prepare('SELECT created_at,marketing_opt_in_at FROM fan_contacts WHERE created_at>=? OR marketing_opt_in_at>=?');$q->execute([$since,$since]);foreach($q->fetchAll() as $r){$d=substr((string)$r['created_at'],0,10);if($d!==''){$touch($d);$daily[$d]['new_contacts']++;}$d=substr((string)($r['marketing_opt_in_at']??''),0,10);if($d!==''){$touch($d);$daily[$d]['newsletter_optins']++;}}$q=$pdo->prepare("SELECT reserved_at,quantity FROM ticket_reservations WHERE reserved_at>=? AND status IN ('reserved','checked_in')");$q->execute([$since]);foreach($q->fetchAll() as $r){$d=substr((string)$r['reserved_at'],0,10);$touch($d);$daily[$d]['ticket_qty']+=(int)$r['quantity'];}$q=$pdo->prepare('SELECT entered_at FROM campaign_participants WHERE entered_at>=?');$q->execute([$since]);foreach($q->fetchAll(PDO::FETCH_COLUMN) as $v){$d=substr((string)$v,0,10);$touch($d);$daily[$d]['campaign_entries']++;}},null);
    ksort($daily);return array_values($daily);
}
function sf_growth_opportunities(array $g): array {
    $out=[];$orders=$g['orders'];$refunds=$g['refunds'];$campaigns=$g['campaigns'];$automation=$g['automation'];$ticket=$g['ticketing'];$care=$g['care'];$membership=$g['membership'];$merch=$g['merch'];
    if($orders['paid_orders']>0&&sf_growth_percent($refunds['confirmed'],$orders['paid_orders'])>=10)$out[]=['severity'=>'warning','area'=>'Commerce','title'=>'Refund rate needs attention','detail'=>$refunds['confirmed'].' confirmed refunds across '.$orders['paid_orders'].' paid orders in this window.'];
    if(($care['high_priority_cases']??0)>0)$out[]=['severity'=>'warning','area'=>'Customer care','title'=>'High-priority fan cases are open','detail'=>(int)$care['high_priority_cases'].' high/urgent support cases need attention.'];
    if(($automation['failed']??0)>0)$out[]=['severity'=>'warning','area'=>'Automation','title'=>'Lifecycle automation failures','detail'=>(int)$automation['failed'].' automation runs failed in this window.'];
    foreach((array)($campaigns['campaigns']??[]) as $c)if($c['participants']>=10&&$c['conversion_rate']<5)$out[]=['severity'=>'watch','area'=>'Campaigns','title'=>'Low-converting campaign: '.$c['name'],'detail'=>$c['participants'].' participants · '.$c['conversion_rate'].'% converted.'];
    foreach((array)($ticket['offers']??[]) as $o)if($o['status']==='published'&&$o['capacity']>0&&$o['fill_rate']>=90)$out[]=['severity'=>'info','area'=>'Tickets','title'=>'Ticket offer nearly full: '.$o['title'],'detail'=>$o['claimed_qty'].' of '.$o['capacity'].' claimed.'];
    if(($membership['cancel_at_period_end']??0)>0)$out[]=['severity'=>'watch','area'=>'Membership','title'=>'Members scheduled to cancel','detail'=>(int)$membership['cancel_at_period_end'].' active memberships are set to cancel at period end.'];
    if(count($merch['low_stock']??[])>0)$out[]=['severity'=>'warning','area'=>'Merch','title'=>'Low-stock products','detail'=>count($merch['low_stock']).' active products or variants are at/below their stock threshold.'];
    if(!$out)$out[]=['severity'=>'good','area'=>'Operations','title'=>'No material growth warnings detected','detail'=>'Current cross-system thresholds are clear for this reporting window.'];
    return array_slice($out,0,20);
}
function sf_growth_analytics(int $days=30): array {
    $days=max(1,min(3650,$days));$orders=sf_growth_orders($days);$refunds=sf_growth_refunds($days);$membership=sf_growth_membership($days);$crm=sf_growth_crm($days);$campaigns=sf_growth_campaigns($days);$automation=sf_growth_automation($days);$ticket=sf_growth_ticketing($days);$merch=sf_growth_merch($days);$care=sf_growth_care($days);
    $recordedGross=$orders['revenue_cents']+$membership['revenue_cents'];$net=max(0,$recordedGross-$refunds['amount_cents']);$supporters=sf_growth_top_supporters($orders,$membership,$days);
    $g=['days'=>$days,'recorded_revenue'=>['order_revenue_cents'=>$orders['revenue_cents'],'membership_revenue_cents'=>$membership['revenue_cents'],'gross_cents'=>$recordedGross,'refund_cents'=>$refunds['amount_cents'],'net_cents'=>$net,'paid_orders'=>$orders['paid_orders'],'membership_invoices'=>$membership['invoices'],'order_item_mix'=>$orders['by_type']],'crm'=>$crm,'campaigns'=>$campaigns,'merch'=>$merch,'membership'=>$membership,'ticketing'=>$ticket,'automation'=>$automation,'care'=>$care,'top_supporters'=>$supporters,'daily'=>sf_growth_daily($days,$orders)];
    $g['opportunities']=sf_growth_opportunities(['orders'=>$orders,'refunds'=>$refunds,'membership'=>$membership,'crm'=>$crm,'campaigns'=>$campaigns,'automation'=>$automation,'ticketing'=>$ticket,'merch'=>$merch,'care'=>$care]);
    return $g;
}
function sf_growth_agent_context_from(array $g,int $days=30): string {
    $r=$g['recorded_revenue'];$c=$g['crm'];$ca=$g['campaigns'];$t=$g['ticketing'];$a=$g['automation'];$lines=['BUSINESS + FAN INTELLIGENCE','- window '.$days.' days | recorded gross '.number_format($r['gross_cents']/100,2).' USD | refunds '.number_format($r['refund_cents']/100,2).' | net '.number_format($r['net_cents']/100,2),'- paid orders '.$r['paid_orders'].' | active members '.$g['membership']['active_members'].' | new CRM contacts '.$c['new_contacts'].' | new newsletter opt-ins '.$c['new_newsletter'],'- campaign participants '.$ca['participants'].' | campaign conversion '.$ca['conversion_rate'].'% | attributed campaign revenue '.number_format($ca['attributed_revenue_cents']/100,2),'- ticket reservations '.$t['reserved_qty'].' | checked in '.$t['checked_in_qty'].' | automation completion '.$a['completion_rate'].'%'];
    foreach(array_slice($g['opportunities'],0,5) as $o)$lines[]='- '.$o['area'].' | '.$o['title'].' | '.$o['detail'];return implode("\n",$lines);
}
function sf_growth_agent_context(int $days=30): string {$g=sf_growth_analytics($days);return sf_growth_agent_context_from($g,$days);}
