<?php
declare(strict_types=1);

const SF_LIFECYCLE_TRIGGERS=['segment_entry','daily','newsletter_signup','merch_purchase','campaign_converted','inactivity','manual'];
const SF_LIFECYCLE_ACTIONS=['wait','crm_tag','crm_stage','notification','agent_message','email','exit'];

function sf_lifecycle_auto_json(array $v): string {return json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?:'{}';}
function sf_lifecycle_auto_decode(mixed $v,array $fallback=[]): array {$d=is_array($v)?$v:json_decode((string)$v,true);return is_array($d)?$d:$fallback;}
function sf_lifecycle_auto_table_exists(string $table): bool {
    try{$pdo=sf_db();$driver=(string)(sf_db_config()['driver']??'');if($driver==='sqlite'){$q=$pdo->prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?");$q->execute([$table]);return (bool)$q->fetchColumn();}$q=$pdo->prepare('SHOW TABLES LIKE ?');$q->execute([$table]);return (bool)$q->fetchColumn();}catch(Throwable $e){return false;}
}
function sf_lifecycle_automation_ensure_schema(): void {
    static $done=false;if($done)return;$pdo=sf_db();$driver=(string)(sf_db_config()['driver']??'');
    if($driver==='sqlite'){
        $pdo->exec("CREATE TABLE IF NOT EXISTS fan_segments (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'active',match_mode TEXT NOT NULL DEFAULT 'all',rules_json TEXT NOT NULL DEFAULT '{}',revision INTEGER NOT NULL DEFAULT 1,created_by INTEGER NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_fan_segments_status_name ON fan_segments(status,name)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS lifecycle_automations (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'draft',trigger_type TEXT NOT NULL,trigger_config_json TEXT NOT NULL DEFAULT '{}',segment_id INTEGER NULL,cooldown_hours INTEGER NOT NULL DEFAULT 168,max_per_contact INTEGER NOT NULL DEFAULT 1,actions_json TEXT NOT NULL DEFAULT '[]',version INTEGER NOT NULL DEFAULT 1,created_by INTEGER NULL,activated_at TEXT NULL,last_run_at TEXT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(segment_id) REFERENCES fan_segments(id) ON DELETE SET NULL,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_lifecycle_automations_status ON lifecycle_automations(status,trigger_type)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS lifecycle_enrollments (id INTEGER PRIMARY KEY AUTOINCREMENT,automation_id INTEGER NOT NULL,contact_id INTEGER NOT NULL,trigger_key TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',current_step INTEGER NOT NULL DEFAULT 0,next_run_at TEXT NOT NULL,last_action_at TEXT NULL,completed_at TEXT NULL,metadata_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(automation_id,contact_id,trigger_key),FOREIGN KEY(automation_id) REFERENCES lifecycle_automations(id) ON DELETE CASCADE,FOREIGN KEY(contact_id) REFERENCES fan_contacts(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_lifecycle_enrollments_due ON lifecycle_enrollments(automation_id,status,next_run_at)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS lifecycle_action_log (id INTEGER PRIMARY KEY AUTOINCREMENT,automation_id INTEGER NOT NULL,enrollment_id INTEGER NOT NULL,contact_id INTEGER NOT NULL,action_index INTEGER NOT NULL,action_type TEXT NOT NULL,dedupe_key TEXT NOT NULL UNIQUE,status TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 1,details_json TEXT NOT NULL DEFAULT '{}',error_text TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,executed_at TEXT NULL,FOREIGN KEY(automation_id) REFERENCES lifecycle_automations(id) ON DELETE CASCADE,FOREIGN KEY(enrollment_id) REFERENCES lifecycle_enrollments(id) ON DELETE CASCADE,FOREIGN KEY(contact_id) REFERENCES fan_contacts(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_lifecycle_action_log_contact ON lifecycle_action_log(contact_id,created_at)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS lifecycle_runs (id INTEGER PRIMARY KEY AUTOINCREMENT,automation_id INTEGER NULL,source TEXT NOT NULL,status TEXT NOT NULL,contacts_evaluated INTEGER NOT NULL DEFAULT 0,enrolled_count INTEGER NOT NULL DEFAULT 0,actions_executed INTEGER NOT NULL DEFAULT 0,actions_skipped INTEGER NOT NULL DEFAULT 0,error_count INTEGER NOT NULL DEFAULT 0,error_text TEXT NOT NULL DEFAULT '',started_at TEXT NOT NULL,completed_at TEXT NULL,FOREIGN KEY(automation_id) REFERENCES lifecycle_automations(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_lifecycle_runs_started ON lifecycle_runs(started_at)");
    }else{
        $pdo->exec("CREATE TABLE IF NOT EXISTS fan_segments (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,name VARCHAR(180) NOT NULL,description TEXT NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'active',match_mode VARCHAR(12) NOT NULL DEFAULT 'all',rules_json LONGTEXT NOT NULL,revision INT NOT NULL DEFAULT 1,created_by BIGINT UNSIGNED NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,INDEX idx_fan_segments_status_name(status,name),CONSTRAINT fk_fan_segment_admin FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS lifecycle_automations (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,name VARCHAR(180) NOT NULL,description TEXT NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'draft',trigger_type VARCHAR(60) NOT NULL,trigger_config_json LONGTEXT NOT NULL,segment_id BIGINT UNSIGNED NULL,cooldown_hours INT NOT NULL DEFAULT 168,max_per_contact INT NOT NULL DEFAULT 1,actions_json LONGTEXT NOT NULL,version INT NOT NULL DEFAULT 1,created_by BIGINT UNSIGNED NULL,activated_at VARCHAR(40) NULL,last_run_at VARCHAR(40) NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,INDEX idx_lifecycle_automations_status(status,trigger_type),CONSTRAINT fk_lifecycle_segment FOREIGN KEY(segment_id) REFERENCES fan_segments(id) ON DELETE SET NULL,CONSTRAINT fk_lifecycle_admin FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS lifecycle_enrollments (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,automation_id BIGINT UNSIGNED NOT NULL,contact_id BIGINT UNSIGNED NOT NULL,trigger_key VARCHAR(220) NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'active',current_step INT NOT NULL DEFAULT 0,next_run_at VARCHAR(40) NOT NULL,last_action_at VARCHAR(40) NULL,completed_at VARCHAR(40) NULL,metadata_json LONGTEXT NOT NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,UNIQUE KEY uq_lifecycle_enrollment(automation_id,contact_id,trigger_key),INDEX idx_lifecycle_enrollments_due(automation_id,status,next_run_at),CONSTRAINT fk_lifecycle_enrollment_auto FOREIGN KEY(automation_id) REFERENCES lifecycle_automations(id) ON DELETE CASCADE,CONSTRAINT fk_lifecycle_enrollment_contact FOREIGN KEY(contact_id) REFERENCES fan_contacts(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS lifecycle_action_log (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,automation_id BIGINT UNSIGNED NOT NULL,enrollment_id BIGINT UNSIGNED NOT NULL,contact_id BIGINT UNSIGNED NOT NULL,action_index INT NOT NULL,action_type VARCHAR(60) NOT NULL,dedupe_key VARCHAR(255) NOT NULL UNIQUE,status VARCHAR(32) NOT NULL,attempts INT NOT NULL DEFAULT 1,details_json LONGTEXT NOT NULL,error_text TEXT NOT NULL,created_at VARCHAR(40) NOT NULL,executed_at VARCHAR(40) NULL,INDEX idx_lifecycle_action_log_contact(contact_id,created_at),CONSTRAINT fk_lifecycle_action_auto FOREIGN KEY(automation_id) REFERENCES lifecycle_automations(id) ON DELETE CASCADE,CONSTRAINT fk_lifecycle_action_enrollment FOREIGN KEY(enrollment_id) REFERENCES lifecycle_enrollments(id) ON DELETE CASCADE,CONSTRAINT fk_lifecycle_action_contact FOREIGN KEY(contact_id) REFERENCES fan_contacts(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS lifecycle_runs (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,automation_id BIGINT UNSIGNED NULL,source VARCHAR(32) NOT NULL,status VARCHAR(32) NOT NULL,contacts_evaluated INT NOT NULL DEFAULT 0,enrolled_count INT NOT NULL DEFAULT 0,actions_executed INT NOT NULL DEFAULT 0,actions_skipped INT NOT NULL DEFAULT 0,error_count INT NOT NULL DEFAULT 0,error_text TEXT NOT NULL,started_at VARCHAR(40) NOT NULL,completed_at VARCHAR(40) NULL,INDEX idx_lifecycle_runs_started(started_at),CONSTRAINT fk_lifecycle_run_auto FOREIGN KEY(automation_id) REFERENCES lifecycle_automations(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    }
    $done=true;
}
function sf_lifecycle_segment_normalize_rules(array $raw): array {
    $mode=(string)($raw['mode']??'all');if(!in_array($mode,['all','any'],true))$mode='all';$allowedFields=['status','marketing_opt_in','agent_auto_engage','linked_account','tag','source','contact_age_days','last_engaged_days','crm_event','merch_product','merch_spend_cents','merch_units','listen_count','last_listen_days'];$allowedOps=['equals','not_equals','contains','not_contains','in','not_in','gte','lte','gt','lt','exists','not_exists'];$conditions=[];
    foreach((array)($raw['conditions']??[]) as $r){if(!is_array($r))continue;$field=sf_clean_text($r['field']??'',60);$op=sf_clean_text($r['operator']??'equals',30);if(!in_array($field,$allowedFields,true)||!in_array($op,$allowedOps,true))continue;$value=$r['value']??'';if(is_array($value))$value=array_values(array_filter(array_map(fn($x)=>sf_clean_text($x,180),$value),fn($x)=>$x!==''));else $value=sf_clean_text($value,500);$conditions[]=['field'=>$field,'operator'=>$op,'value'=>$value];}
    return ['mode'=>$mode,'conditions'=>$conditions];
}
function sf_lifecycle_segment_save(array $raw,int $adminId): array {
    sf_lifecycle_automation_ensure_schema();$id=max(0,(int)($raw['id']??0));$name=sf_clean_text($raw['name']??'',180);if($name==='')throw new InvalidArgumentException('Segment name is required.');$description=sf_clean_text($raw['description']??'',2000);$status=(string)($raw['status']??'active');if(!in_array($status,['active','archived'],true))$status='active';$rules=sf_lifecycle_segment_normalize_rules((array)($raw['rules']??[]));$now=gmdate('c');
    if($id){$q=sf_db()->prepare('SELECT revision FROM fan_segments WHERE id=?');$q->execute([$id]);$rev=$q->fetchColumn();if($rev===false)throw new InvalidArgumentException('Segment not found.');$rev=(int)$rev+1;sf_db()->prepare('UPDATE fan_segments SET name=?,description=?,status=?,match_mode=?,rules_json=?,revision=?,updated_at=? WHERE id=?')->execute([$name,$description,$status,$rules['mode'],sf_lifecycle_auto_json($rules),$rev,$now,$id]);}
    else{$q=sf_db()->prepare('INSERT INTO fan_segments(name,description,status,match_mode,rules_json,revision,created_by,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?,?)');$q->execute([$name,$description,$status,$rules['mode'],sf_lifecycle_auto_json($rules),$adminId?:null,$now,$now]);$id=(int)sf_db()->lastInsertId();}
    return sf_lifecycle_segment($id)?:[];
}
function sf_lifecycle_segment(int $id): ?array {
    sf_lifecycle_automation_ensure_schema();$q=sf_db()->prepare('SELECT * FROM fan_segments WHERE id=?');$q->execute([$id]);$r=$q->fetch();if(!$r)return null;$r['rules']=sf_lifecycle_auto_decode($r['rules_json']??'',[]);return $r;
}
function sf_lifecycle_segments(bool $activeOnly=false): array {
    sf_lifecycle_automation_ensure_schema();$rows=sf_db()->query('SELECT * FROM fan_segments'.($activeOnly?" WHERE status='active'":'').' ORDER BY status,name,id')->fetchAll();foreach($rows as &$r)$r['rules']=sf_lifecycle_auto_decode($r['rules_json']??'',[]);unset($r);return $rows;
}
function sf_lifecycle_days_since(?string $date,int $empty=99999): int {if(!$date)return $empty;$ts=strtotime($date);if(!$ts)return $empty;return max(0,(int)floor((time()-$ts)/86400));}
function sf_lifecycle_contact_metric(array $c,string $field): mixed {
    $pdo=sf_db();$uid=(int)($c['user_id']??0);$contactId=(int)$c['id'];$email=strtolower((string)($c['email']??''));
    if($field==='status')return (string)$c['status'];
    if($field==='marketing_opt_in')return !empty($c['marketing_opt_in']);
    if($field==='agent_auto_engage')return !empty($c['agent_auto_engage']);
    if($field==='linked_account')return $uid>0;
    if($field==='tag')return array_map('strtolower',sf_lifecycle_auto_decode($c['tags_json']??'[]',[]));
    if($field==='source')return (string)$c['source'];
    if($field==='contact_age_days')return sf_lifecycle_days_since((string)($c['created_at']??''),0);
    if($field==='last_engaged_days')return sf_lifecycle_days_since((string)($c['last_engaged_at']??$c['updated_at']??''),99999);
    if($field==='crm_event'){$q=$pdo->prepare('SELECT DISTINCT event_type FROM fan_crm_events WHERE contact_id=? ORDER BY id DESC LIMIT 100');$q->execute([$contactId]);return array_map('strval',$q->fetchAll(PDO::FETCH_COLUMN));}
    if(in_array($field,['merch_product','merch_spend_cents','merch_units'],true)&&sf_lifecycle_auto_table_exists('store_order_items')){$where='contact_id=?';$args=[$contactId];if(!$contactId&&$uid){$where='user_id=?';$args=[$uid];}elseif(!$contactId&&$email!==''){$where='customer_email=?';$args=[$email];}if($field==='merch_product'){$q=$pdo->prepare("SELECT DISTINCT product_id FROM store_order_items WHERE $where AND inventory_status<>'released'");$q->execute($args);return array_map('strval',$q->fetchAll(PDO::FETCH_COLUMN));}$col=$field==='merch_spend_cents'?'subtotal_cents':'quantity';$q=$pdo->prepare("SELECT COALESCE(SUM($col),0) FROM store_order_items WHERE $where AND inventory_status<>'released'");$q->execute($args);return (int)$q->fetchColumn();}
    if(in_array($field,['listen_count','last_listen_days'],true)&&$uid&&sf_lifecycle_auto_table_exists('listening_events')){if($field==='listen_count'){$q=$pdo->prepare("SELECT COUNT(*) FROM listening_events WHERE user_id=? AND event_type IN ('start','resume','complete')");$q->execute([$uid]);return (int)$q->fetchColumn();}$q=$pdo->prepare("SELECT MAX(created_at) FROM listening_events WHERE user_id=? AND event_type IN ('start','resume','complete')");$q->execute([$uid]);return sf_lifecycle_days_since((string)($q->fetchColumn()?:''),99999);}
    return null;
}
function sf_lifecycle_compare(mixed $actual,string $op,mixed $wanted): bool {
    if($op==='exists')return is_array($actual)?count($actual)>0:!($actual===null||$actual===''||$actual===false);
    if($op==='not_exists')return !sf_lifecycle_compare($actual,'exists',$wanted);
    if(is_bool($actual)){$w=in_array(strtolower((string)$wanted),['1','true','yes','on'],true);return $op==='not_equals'?$actual!==$w:$actual===$w;}
    if(is_array($actual)){$a=array_map(fn($x)=>strtolower((string)$x),$actual);$w=is_array($wanted)?array_map(fn($x)=>strtolower((string)$x),$wanted):[strtolower((string)$wanted)];if($op==='contains'||$op==='equals')return !array_diff($w,$a);if($op==='not_contains'||$op==='not_equals')return (bool)array_diff($w,$a);if($op==='in')return (bool)array_intersect($a,$w);if($op==='not_in')return !array_intersect($a,$w);return false;}
    if(in_array($op,['gte','lte','gt','lt'],true)){if(!is_numeric($actual)||!is_numeric($wanted))return false;$a=(float)$actual;$w=(float)$wanted;return $op==='gte'?$a>=$w:($op==='lte'?$a<=$w:($op==='gt'?$a>$w:$a<$w));}
    $a=strtolower(trim((string)$actual));$vals=is_array($wanted)?array_map(fn($x)=>strtolower(trim((string)$x)),$wanted):array_map('trim',explode(',',strtolower((string)$wanted)));if($op==='contains')return str_contains($a,(string)($vals[0]??''));if($op==='not_contains')return !str_contains($a,(string)($vals[0]??''));if($op==='in')return in_array($a,$vals,true);if($op==='not_in')return !in_array($a,$vals,true);if($op==='not_equals')return $a!==(string)($vals[0]??'');return $a===(string)($vals[0]??'');
}
function sf_lifecycle_segment_matches(array $contact,array $segment): bool {
    $rules=is_array($segment['rules']??null)?$segment['rules']:sf_lifecycle_auto_decode($segment['rules_json']??'',[]);$conditions=(array)($rules['conditions']??[]);if(!$conditions)return true;$results=[];foreach($conditions as $r){$results[]=sf_lifecycle_compare(sf_lifecycle_contact_metric($contact,(string)$r['field']),(string)$r['operator'],$r['value']??'');}return ($rules['mode']??'all')==='any'?in_array(true,$results,true):!in_array(false,$results,true);
}
function sf_lifecycle_segment_contacts(array $segment,int $limit=500): array {
    sf_lifecycle_automation_ensure_schema();$limit=max(1,min(5000,$limit));$rows=sf_db()->query('SELECT * FROM fan_contacts ORDER BY id ASC LIMIT '.$limit)->fetchAll();return array_values(array_filter($rows,fn($c)=>sf_lifecycle_segment_matches($c,$segment)));
}
function sf_lifecycle_segment_preview(int $id,int $limit=100): array {$s=sf_lifecycle_segment($id);if(!$s)throw new InvalidArgumentException('Segment not found.');$all=sf_lifecycle_segment_contacts($s,5000);return ['count'=>count($all),'contacts'=>array_slice(array_map(fn($c)=>['id'=>(int)$c['id'],'email'=>$c['email'],'display_name'=>$c['display_name'],'status'=>$c['status']],$all),0,max(1,min(500,$limit)))];}

function sf_lifecycle_normalize_actions(array $rows): array {
    $out=[];foreach($rows as $a){if(!is_array($a))continue;$type=sf_clean_text($a['type']??'',60);if(!in_array($type,SF_LIFECYCLE_ACTIONS,true))continue;$cfg=(array)($a['config']??[]);
        if($type==='wait')$cfg=['hours'=>max(0,min(8760,(int)($cfg['hours']??24)))];
        elseif($type==='crm_tag')$cfg=['tag'=>sf_clean_text($cfg['tag']??'',60)];
        elseif($type==='crm_stage'){$stage=(string)($cfg['stage']??'fan');if(!in_array($stage,['lead','fan','customer','member','inactive'],true))$stage='fan';$cfg=['stage'=>$stage];}
        elseif($type==='notification')$cfg=['title'=>sf_clean_text($cfg['title']??'Stonefellow',180),'body'=>sf_clean_text($cfg['body']??'',1200),'link'=>sf_clean_text($cfg['link']??'?view=home',500)];
        elseif($type==='agent_message')$cfg=['message'=>sf_clean_text($cfg['message']??'',1200),'link'=>sf_clean_text($cfg['link']??'?view=home',500)];
        elseif($type==='email')$cfg=['subject'=>sf_clean_text($cfg['subject']??'',255),'body'=>sf_clean_text($cfg['body']??'',20000)];
        else $cfg=[];
        $out[]=['type'=>$type,'config'=>$cfg];
    }return $out;
}
function sf_lifecycle_automation(int $id): ?array {
    sf_lifecycle_automation_ensure_schema();$q=sf_db()->prepare('SELECT * FROM lifecycle_automations WHERE id=?');$q->execute([$id]);$r=$q->fetch();if(!$r)return null;$r['trigger_config']=sf_lifecycle_auto_decode($r['trigger_config_json']??'',[]);$r['actions']=sf_lifecycle_auto_decode($r['actions_json']??'[]',[]);return $r;
}
function sf_lifecycle_automations(): array {
    sf_lifecycle_automation_ensure_schema();$rows=sf_db()->query('SELECT a.*,s.name segment_name FROM lifecycle_automations a LEFT JOIN fan_segments s ON s.id=a.segment_id ORDER BY CASE a.status WHEN "active" THEN 0 WHEN "paused" THEN 1 WHEN "draft" THEN 2 ELSE 3 END,a.id DESC')->fetchAll();foreach($rows as &$r){$r['trigger_config']=sf_lifecycle_auto_decode($r['trigger_config_json']??'',[]);$r['actions']=sf_lifecycle_auto_decode($r['actions_json']??'[]',[]);}unset($r);return $rows;
}
function sf_lifecycle_automation_save(array $raw,int $adminId): array {
    sf_lifecycle_automation_ensure_schema();$id=max(0,(int)($raw['id']??0));$name=sf_clean_text($raw['name']??'',180);if($name==='')throw new InvalidArgumentException('Automation name is required.');$trigger=(string)($raw['trigger_type']??'segment_entry');if(!in_array($trigger,SF_LIFECYCLE_TRIGGERS,true))throw new InvalidArgumentException('Unsupported automation trigger.');$segmentId=max(0,(int)($raw['segment_id']??0));if($segmentId&&!sf_lifecycle_segment($segmentId))throw new InvalidArgumentException('Selected segment does not exist.');$actions=sf_lifecycle_normalize_actions((array)($raw['actions']??[]));if(!$actions)throw new InvalidArgumentException('Add at least one lifecycle action.');$cfg=(array)($raw['trigger_config']??[]);if($trigger==='inactivity')$cfg=['days'=>max(1,min(3650,(int)($cfg['days']??30)))];else $cfg=[];$cool=max(0,min(8760,(int)($raw['cooldown_hours']??168)));$max=max(0,min(1000,(int)($raw['max_per_contact']??1)));$desc=sf_clean_text($raw['description']??'',3000);$now=gmdate('c');
    if($id){$existing=sf_lifecycle_automation($id);if(!$existing)throw new InvalidArgumentException('Automation not found.');$version=(int)$existing['version']+1;$status=($existing['status']??'draft')==='active'?'paused':(string)$existing['status'];sf_db()->prepare('UPDATE lifecycle_automations SET name=?,description=?,status=?,trigger_type=?,trigger_config_json=?,segment_id=?,cooldown_hours=?,max_per_contact=?,actions_json=?,version=?,updated_at=? WHERE id=?')->execute([$name,$desc,$status,$trigger,sf_lifecycle_auto_json($cfg),$segmentId?:null,$cool,$max,sf_lifecycle_auto_json($actions),$version,$now,$id]);}
    else{$q=sf_db()->prepare('INSERT INTO lifecycle_automations(name,description,status,trigger_type,trigger_config_json,segment_id,cooldown_hours,max_per_contact,actions_json,version,created_by,activated_at,last_run_at,created_at,updated_at) VALUES(?,?,"draft",?,?,?,?,?,?,1,?,NULL,NULL,?,?)');$q->execute([$name,$desc,$trigger,sf_lifecycle_auto_json($cfg),$segmentId?:null,$cool,$max,sf_lifecycle_auto_json($actions),$adminId?:null,$now,$now]);$id=(int)sf_db()->lastInsertId();}
    return sf_lifecycle_automation($id)?:[];
}
function sf_lifecycle_automation_status(int $id,string $status,int $adminId,bool $confirmed=false): array {
    $a=sf_lifecycle_automation($id);if(!$a)throw new InvalidArgumentException('Automation not found.');if(!in_array($status,['active','paused','archived'],true))throw new InvalidArgumentException('Invalid automation status.');if($status==='active'&&!$confirmed)throw new RuntimeException('Activating a lifecycle automation requires explicit Admin confirmation.');$now=gmdate('c');sf_db()->prepare('UPDATE lifecycle_automations SET status=?,activated_at=CASE WHEN ?="active" THEN ? ELSE activated_at END,updated_at=? WHERE id=?')->execute([$status,$status,$now,$now,$id]);return sf_lifecycle_automation($id)?:[];
}
function sf_lifecycle_contact_enrollment_count(int $automationId,int $contactId): int {$q=sf_db()->prepare('SELECT COUNT(*) FROM lifecycle_enrollments WHERE automation_id=? AND contact_id=?');$q->execute([$automationId,$contactId]);return (int)$q->fetchColumn();}
function sf_lifecycle_enroll(array $automation,array $contact,string $triggerKey,array $meta=[]): array {
    $aid=(int)$automation['id'];$cid=(int)$contact['id'];$max=(int)($automation['max_per_contact']??1);if($max>0&&sf_lifecycle_contact_enrollment_count($aid,$cid)>=$max)return ['created'=>false,'reason'=>'max_per_contact'];
    $cool=(int)($automation['cooldown_hours']??0);if($cool>0){$q=sf_db()->prepare('SELECT created_at FROM lifecycle_enrollments WHERE automation_id=? AND contact_id=? ORDER BY id DESC LIMIT 1');$q->execute([$aid,$cid]);$last=$q->fetchColumn();if($last!==false&&strtotime((string)$last)>time()-$cool*3600)return ['created'=>false,'reason'=>'cooldown'];}
    $now=gmdate('c');try{$q=sf_db()->prepare('INSERT INTO lifecycle_enrollments(automation_id,contact_id,trigger_key,status,current_step,next_run_at,last_action_at,completed_at,metadata_json,created_at,updated_at) VALUES(?,?,?,"active",0,?,NULL,NULL,?,?,?)');$q->execute([$aid,$cid,sf_clean_text($triggerKey,220),$now,sf_lifecycle_auto_json($meta),$now,$now]);return ['created'=>true,'enrollment_id'=>(int)sf_db()->lastInsertId()];}catch(PDOException $e){if(in_array((string)$e->getCode(),['23000','19'],true))return ['created'=>false,'reason'=>'duplicate'];throw $e;}
}
function sf_lifecycle_trigger_event_type(string $trigger): string {return match($trigger){'newsletter_signup'=>'newsletter_signup','merch_purchase'=>'merch_purchase','campaign_converted'=>'campaign_converted',default=>''};}
function sf_lifecycle_trigger_candidates(array $a,int $limit=500,string $manualKey=''): array {
    $segment=!empty($a['segment_id'])?sf_lifecycle_segment((int)$a['segment_id']):null;$limit=max(1,min(5000,$limit));$trigger=(string)$a['trigger_type'];$out=[];
    if(in_array($trigger,['newsletter_signup','merch_purchase','campaign_converted'],true)){$event=sf_lifecycle_trigger_event_type($trigger);$floor=(string)($a['activated_at']??$a['created_at']??'1970-01-01T00:00:00Z');$q=sf_db()->prepare('SELECT e.id event_id,c.* FROM fan_crm_events e JOIN fan_contacts c ON c.id=e.contact_id WHERE e.event_type=? AND e.created_at>=? ORDER BY e.id ASC LIMIT '.$limit);$q->execute([$event,$floor]);foreach($q->fetchAll() as $c){if($segment&&!sf_lifecycle_segment_matches($c,$segment))continue;$out[]=['contact'=>$c,'trigger_key'=>'event:'.$c['event_id'],'meta'=>['event_id'=>(int)$c['event_id'],'event_type'=>$event]];}return $out;}
    $contacts=$segment?sf_lifecycle_segment_contacts($segment,$limit):sf_db()->query('SELECT * FROM fan_contacts ORDER BY id ASC LIMIT '.$limit)->fetchAll();foreach($contacts as $c){$key='';$meta=[];if($trigger==='segment_entry')$key='segment:v'.(int)$a['version'];elseif($trigger==='daily')$key='daily:'.gmdate('Y-m-d');elseif($trigger==='inactivity'){$days=max(1,(int)($a['trigger_config']['days']??30));if(sf_lifecycle_contact_metric($c,'last_engaged_days')<$days)continue;$key='inactive:'.$days.':v'.(int)$a['version'];$meta=['days'=>$days];}elseif($trigger==='manual'){$key=$manualKey;if($key==='')continue;}if($key!=='')$out[]=['contact'=>$c,'trigger_key'=>$key,'meta'=>$meta];}return $out;
}
function sf_lifecycle_action_log_row(string $dedupe): ?array {$q=sf_db()->prepare('SELECT * FROM lifecycle_action_log WHERE dedupe_key=?');$q->execute([$dedupe]);$r=$q->fetch();return $r?:null;}
function sf_lifecycle_action_log_start(array $a,array $e,int $index,string $type,string $dedupe): array {
    $old=sf_lifecycle_action_log_row($dedupe);$now=gmdate('c');if($old){if(in_array((string)$old['status'],['success','skipped'],true))return $old;if((int)$old['attempts']>=3)return $old;sf_db()->prepare('UPDATE lifecycle_action_log SET status="running",attempts=attempts+1,error_text="",executed_at=NULL WHERE id=?')->execute([(int)$old['id']]);return sf_lifecycle_action_log_row($dedupe)?:$old;}
    $q=sf_db()->prepare('INSERT INTO lifecycle_action_log(automation_id,enrollment_id,contact_id,action_index,action_type,dedupe_key,status,attempts,details_json,error_text,created_at,executed_at) VALUES(?,?,?,?,?,?,"running",1,"{}","",?,NULL)');$q->execute([(int)$a['id'],(int)$e['id'],(int)$e['contact_id'],$index,$type,$dedupe,$now]);return sf_lifecycle_action_log_row($dedupe)?:[];
}
function sf_lifecycle_action_finish(int $logId,string $status,array $details=[],string $error=''): void {sf_db()->prepare('UPDATE lifecycle_action_log SET status=?,details_json=?,error_text=?,executed_at=? WHERE id=?')->execute([$status,sf_lifecycle_auto_json($details),sf_clean_text($error,2000),gmdate('c'),$logId]);}
function sf_lifecycle_update_tags(array $c,string $tag): void {$tag=sf_clean_text($tag,60);if($tag==='')return;$tags=sf_lifecycle_auto_decode($c['tags_json']??'[]',[]);if(!in_array($tag,$tags,true)){$tags[]=$tag;sf_db()->prepare('UPDATE fan_contacts SET tags_json=?,updated_at=? WHERE id=?')->execute([sf_lifecycle_auto_json(array_values($tags)),gmdate('c'),(int)$c['id']]);}}
function sf_lifecycle_execute_action(array $a,array $e,array $contact,int $index,array $action): array {
    $type=(string)$action['type'];$cfg=(array)($action['config']??[]);$dedupe='lifecycle:'.$a['id'].':'.$e['id'].':'.$index;$log=sf_lifecycle_action_log_start($a,$e,$index,$type,$dedupe);if(in_array((string)($log['status']??''),['success','skipped'],true))return ['status'=>$log['status'],'stop'=>false,'deduped'=>true];if((int)($log['attempts']??1)>3||((int)($log['attempts']??1)>=3&&($log['status']??'')==='failed'))return ['status'=>'failed','stop'=>true,'error'=>'Action retry limit reached.'];$logId=(int)$log['id'];$uid=(int)($contact['user_id']??0);$now=gmdate('c');
    try{
        if($type==='wait'){$hours=max(0,(int)($cfg['hours']??24));$due=gmdate('c',time()+$hours*3600);sf_lifecycle_action_finish($logId,'success',['hours'=>$hours,'due_at'=>$due]);sf_db()->prepare('UPDATE lifecycle_enrollments SET current_step=?,next_run_at=?,last_action_at=?,updated_at=? WHERE id=?')->execute([$index+1,$due,$now,$now,(int)$e['id']]);return ['status'=>'success','stop'=>true,'wait'=>true];}
        if($type==='crm_tag'){$tag=(string)($cfg['tag']??'');sf_lifecycle_update_tags($contact,$tag);if(function_exists('sf_crm_log_event'))sf_crm_log_event((int)$contact['id'],$uid?:null,'lifecycle_tagged','Lifecycle added CRM tag '.$tag,'lifecycle_automation',(string)$a['id'],['automation'=>$a['name'],'action_index'=>$index]);}
        elseif($type==='crm_stage'){$stage=(string)($cfg['stage']??'fan');sf_db()->prepare('UPDATE fan_contacts SET status=?,updated_at=? WHERE id=?')->execute([$stage,$now,(int)$contact['id']]);if(function_exists('sf_crm_log_event'))sf_crm_log_event((int)$contact['id'],$uid?:null,'lifecycle_stage','Lifecycle changed CRM stage to '.$stage,'lifecycle_automation',(string)$a['id'],['automation'=>$a['name']]);}
        elseif($type==='notification'){if(!$uid){sf_lifecycle_action_finish($logId,'skipped',['reason'=>'no_linked_account']);return ['status'=>'skipped','stop'=>false];}$prefs=function_exists('sf_notification_preferences_map')?sf_notification_preferences_map($uid):[];$pref=$prefs['lifecycle']??['in_app_enabled'=>true];if(empty($pref['in_app_enabled'])){sf_lifecycle_action_finish($logId,'skipped',['reason'=>'notification_preference_disabled']);return ['status'=>'skipped','stop'=>false];}$nid=sf_notify_user($uid,'lifecycle',(string)($cfg['title']??'Stonefellow'),(string)($cfg['body']??''),(string)($cfg['link']??'?view=home'));if(function_exists('sf_notification_event'))sf_notification_event($uid,$nid,'delivered',['category'=>'lifecycle','automation_id'=>(int)$a['id']]);}
        elseif($type==='agent_message'){if(!$uid||empty($contact['agent_auto_engage'])){sf_lifecycle_action_finish($logId,'skipped',['reason'=>$uid?'proactive_agent_disabled':'no_linked_account']);return ['status'=>'skipped','stop'=>false];}$message=(string)($cfg['message']??'');if($message===''){sf_lifecycle_action_finish($logId,'skipped',['reason'=>'empty_message']);return ['status'=>'skipped','stop'=>false];}sf_notify_user($uid,'agent','Stonefellow Agent',$message,(string)($cfg['link']??'?view=home'));if(function_exists('sf_crm_agent_log'))sf_crm_agent_log((int)$contact['id'],$uid,'in_app','lifecycle',$dedupe,$message,'Lifecycle automation: '.$a['name'],['automation_id'=>(int)$a['id'],'enrollment_id'=>(int)$e['id']]);}
        elseif($type==='email'){if(empty($contact['marketing_opt_in'])){sf_lifecycle_action_finish($logId,'skipped',['reason'=>'marketing_opt_out']);return ['status'=>'skipped','stop'=>false];}$subject=(string)($cfg['subject']??'');$body=(string)($cfg['body']??'');if($subject===''||$body===''){sf_lifecycle_action_finish($logId,'skipped',['reason'=>'empty_email']);return ['status'=>'skipped','stop'=>false];}$unsubscribe=function_exists('sf_campaign_marketing_unsubscribe_link')?sf_campaign_marketing_unsubscribe_link($contact):'';$full=$body.($unsubscribe!==''?"\n\nUnsubscribe: ".$unsubscribe:'');$mail=sf_transactional_email($uid,(string)$contact['email'],$subject,$full,'lifecycle_marketing');if(($mail['status']??'')==='failed')throw new RuntimeException('Lifecycle email delivery failed.');if(function_exists('sf_crm_log_event'))sf_crm_log_event((int)$contact['id'],$uid?:null,'lifecycle_email','Lifecycle email: '.$subject,'lifecycle_automation',(string)$a['id'],['status'=>$mail['status']??'']);}
        elseif($type==='exit'){sf_lifecycle_action_finish($logId,'success',['exit'=>true]);sf_db()->prepare('UPDATE lifecycle_enrollments SET status="completed",current_step=?,last_action_at=?,completed_at=?,updated_at=? WHERE id=?')->execute([$index+1,$now,$now,$now,(int)$e['id']]);return ['status'=>'success','stop'=>true,'complete'=>true];}
        sf_lifecycle_action_finish($logId,'success',['automation'=>(int)$a['id']]);sf_db()->prepare('UPDATE lifecycle_enrollments SET current_step=?,next_run_at=?,last_action_at=?,updated_at=? WHERE id=?')->execute([$index+1,$now,$now,$now,(int)$e['id']]);return ['status'=>'success','stop'=>false];
    }catch(Throwable $x){sf_lifecycle_action_finish($logId,'failed',[],$x->getMessage());$latest=sf_lifecycle_action_log_row($dedupe);if((int)($latest['attempts']??1)>=3)sf_db()->prepare('UPDATE lifecycle_enrollments SET status="failed",updated_at=? WHERE id=?')->execute([$now,(int)$e['id']]);return ['status'=>'failed','stop'=>true,'error'=>$x->getMessage()];}
}
function sf_lifecycle_process_enrollment(int $id,int $maxSteps=20): array {
    sf_lifecycle_automation_ensure_schema();$q=sf_db()->prepare('SELECT * FROM lifecycle_enrollments WHERE id=?');$q->execute([$id]);$e=$q->fetch();if(!$e||$e['status']!=='active')return ['executed'=>0,'skipped'=>0,'errors'=>0,'status'=>$e['status']??'missing'];if(strtotime((string)$e['next_run_at'])>time())return ['executed'=>0,'skipped'=>0,'errors'=>0,'status'=>'waiting'];$a=sf_lifecycle_automation((int)$e['automation_id']);$contact=sf_crm_contact_by_id((int)$e['contact_id']);if(!$a||!$contact){sf_db()->prepare('UPDATE lifecycle_enrollments SET status="failed",updated_at=? WHERE id=?')->execute([gmdate('c'),$id]);return ['executed'=>0,'skipped'=>0,'errors'=>1,'status'=>'failed'];}$actions=(array)$a['actions'];$executed=0;$skipped=0;$errors=0;$step=(int)$e['current_step'];
    for($n=0;$n<$maxSteps&&$step<count($actions);$n++,$step++){ $q=sf_db()->prepare('SELECT * FROM lifecycle_enrollments WHERE id=?');$q->execute([$id]);$e=$q->fetch();$r=sf_lifecycle_execute_action($a,$e,$contact,$step,$actions[$step]);if($r['status']==='success')$executed++;elseif($r['status']==='skipped')$skipped++;else $errors++;if(!empty($r['stop']))return ['executed'=>$executed,'skipped'=>$skipped,'errors'=>$errors,'status'=>$r['complete']??false?'completed':($r['wait']??false?'waiting':'failed')];if(in_array($r['status'],['success','skipped'],true))sf_db()->prepare('UPDATE lifecycle_enrollments SET current_step=?,next_run_at=?,last_action_at=?,updated_at=? WHERE id=?')->execute([$step+1,gmdate('c'),gmdate('c'),gmdate('c'),$id]);$contact=sf_crm_contact_by_id((int)$e['contact_id'])?:$contact;}
    $q=sf_db()->prepare('SELECT current_step,status FROM lifecycle_enrollments WHERE id=?');$q->execute([$id]);$latest=$q->fetch()?:[];if(($latest['status']??'')==='active'&&(int)($latest['current_step']??0)>=count($actions))sf_db()->prepare('UPDATE lifecycle_enrollments SET status="completed",completed_at=?,updated_at=? WHERE id=?')->execute([gmdate('c'),gmdate('c'),$id]);return ['executed'=>$executed,'skipped'=>$skipped,'errors'=>$errors,'status'=>'completed'];
}
function sf_lifecycle_run_automation(int $automationId,string $source='cron',int $limit=500,bool $confirmed=false): array {
    sf_lifecycle_automation_ensure_schema();$a=sf_lifecycle_automation($automationId);if(!$a)throw new InvalidArgumentException('Automation not found.');if($a['status']!=='active')throw new RuntimeException('Automation must be active before it can run.');if($source==='manual'&&!$confirmed)throw new RuntimeException('Manual automation runs require explicit Admin confirmation.');$now=gmdate('c');$q=sf_db()->prepare('INSERT INTO lifecycle_runs(automation_id,source,status,contacts_evaluated,enrolled_count,actions_executed,actions_skipped,error_count,error_text,started_at,completed_at) VALUES(?,?,"running",0,0,0,0,0,"",?,NULL)');$q->execute([$automationId,$source,$now]);$runId=(int)sf_db()->lastInsertId();$evaluated=0;$enrolled=0;$executed=0;$skipped=0;$errors=0;$errorText='';
    try{$manualKey=$source==='manual'?'manual:'.$runId:'';$candidates=sf_lifecycle_trigger_candidates($a,$limit,$manualKey);$evaluated=count($candidates);foreach($candidates as $row){$en=sf_lifecycle_enroll($a,$row['contact'],$row['trigger_key'],$row['meta']);if(!empty($en['created']))$enrolled++;}
        $q=sf_db()->prepare("SELECT id FROM lifecycle_enrollments WHERE automation_id=? AND status='active' AND next_run_at<=? ORDER BY id ASC LIMIT ".max(1,min(5000,$limit)));$q->execute([$automationId,$now]);foreach($q->fetchAll(PDO::FETCH_COLUMN) as $eid){$r=sf_lifecycle_process_enrollment((int)$eid,20);$executed+=(int)$r['executed'];$skipped+=(int)$r['skipped'];$errors+=(int)$r['errors'];}
        sf_db()->prepare('UPDATE lifecycle_automations SET last_run_at=?,updated_at=? WHERE id=?')->execute([gmdate('c'),gmdate('c'),$automationId]);
    }catch(Throwable $x){$errors++;$errorText=$x->getMessage();}
    $status=$errors?'completed_with_errors':'completed';$done=gmdate('c');sf_db()->prepare('UPDATE lifecycle_runs SET status=?,contacts_evaluated=?,enrolled_count=?,actions_executed=?,actions_skipped=?,error_count=?,error_text=?,completed_at=? WHERE id=?')->execute([$status,$evaluated,$enrolled,$executed,$skipped,$errors,sf_clean_text($errorText,2000),$done,$runId]);return ['run_id'=>$runId,'status'=>$status,'contacts_evaluated'=>$evaluated,'enrolled'=>$enrolled,'actions_executed'=>$executed,'actions_skipped'=>$skipped,'errors'=>$errors,'ran_at'=>$done];
}
function sf_lifecycle_run_all(int $limitPerAutomation=500): array {
    sf_lifecycle_automation_ensure_schema();$ids=sf_db()->query("SELECT id FROM lifecycle_automations WHERE status='active' ORDER BY id")->fetchAll(PDO::FETCH_COLUMN);$runs=[];$totals=['automations'=>0,'contacts_evaluated'=>0,'enrolled'=>0,'actions_executed'=>0,'actions_skipped'=>0,'errors'=>0];foreach($ids as $id){$r=sf_lifecycle_run_automation((int)$id,'cron',$limitPerAutomation,true);$runs[]=$r;$totals['automations']++;foreach(['contacts_evaluated','enrolled','actions_executed','actions_skipped','errors'] as $k)$totals[$k]+=(int)$r[$k];}$totals['runs']=$runs;$totals['ran_at']=gmdate('c');return $totals;
}
function sf_lifecycle_summary(): array {
    sf_lifecycle_automation_ensure_schema();$pdo=sf_db();return ['segments'=>(int)$pdo->query("SELECT COUNT(*) FROM fan_segments WHERE status='active'")->fetchColumn(),'automations'=>(int)$pdo->query('SELECT COUNT(*) FROM lifecycle_automations')->fetchColumn(),'active'=>(int)$pdo->query("SELECT COUNT(*) FROM lifecycle_automations WHERE status='active'")->fetchColumn(),'active_enrollments'=>(int)$pdo->query("SELECT COUNT(*) FROM lifecycle_enrollments WHERE status='active'")->fetchColumn(),'completed'=>(int)$pdo->query("SELECT COUNT(*) FROM lifecycle_enrollments WHERE status='completed'")->fetchColumn(),'actions'=>(int)$pdo->query("SELECT COUNT(*) FROM lifecycle_action_log WHERE status='success'")->fetchColumn(),'skipped'=>(int)$pdo->query("SELECT COUNT(*) FROM lifecycle_action_log WHERE status='skipped'")->fetchColumn(),'errors'=>(int)$pdo->query("SELECT COUNT(*) FROM lifecycle_action_log WHERE status='failed'")->fetchColumn()];}
function sf_lifecycle_runs(int $limit=100): array {sf_lifecycle_automation_ensure_schema();$limit=max(1,min(500,$limit));return sf_db()->query('SELECT r.*,a.name automation_name FROM lifecycle_runs r LEFT JOIN lifecycle_automations a ON a.id=r.automation_id ORDER BY r.id DESC LIMIT '.$limit)->fetchAll();}
function sf_lifecycle_enrollments(int $automationId,int $limit=150): array {$limit=max(1,min(500,$limit));$q=sf_db()->prepare('SELECT e.*,c.email,c.display_name,c.status contact_status FROM lifecycle_enrollments e JOIN fan_contacts c ON c.id=e.contact_id WHERE e.automation_id=? ORDER BY e.id DESC LIMIT '.$limit);$q->execute([$automationId]);return $q->fetchAll();}
