<?php
declare(strict_types=1);

function sf_media_json(array $v): string {return json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?:'{}';}
function sf_media_decode(mixed $v,array $fallback=[]): array {$d=is_array($v)?$v:json_decode((string)$v,true);return is_array($d)?$d:$fallback;}
function sf_media_uuid(): string {return 'M'.strtoupper(bin2hex(random_bytes(10)));}
function sf_media_ensure_schema(): void {
    static $done=false;if($done)return;$pdo=sf_db();$driver=(string)(sf_db_config()['driver']??'');
    if($driver==='sqlite'){
        $pdo->exec("CREATE TABLE IF NOT EXISTS media_assets (id INTEGER PRIMARY KEY AUTOINCREMENT,uuid TEXT NOT NULL UNIQUE,category TEXT NOT NULL,mime_type TEXT NOT NULL,extension TEXT NOT NULL,original_name TEXT NOT NULL,stored_path TEXT NOT NULL,sha256 TEXT NOT NULL,size_bytes INTEGER NOT NULL DEFAULT 0,width INTEGER NOT NULL DEFAULT 0,height INTEGER NOT NULL DEFAULT 0,duration_seconds REAL NOT NULL DEFAULT 0,bitrate_bps INTEGER NOT NULL DEFAULT 0,sample_rate_hz INTEGER NOT NULL DEFAULT 0,channels INTEGER NOT NULL DEFAULT 0,bits_per_sample INTEGER NOT NULL DEFAULT 0,codec TEXT NOT NULL DEFAULT '',title TEXT NOT NULL DEFAULT '',caption TEXT NOT NULL DEFAULT '',alt_text TEXT NOT NULL DEFAULT '',credit TEXT NOT NULL DEFAULT '',copyright_text TEXT NOT NULL DEFAULT '',technical_json TEXT NOT NULL DEFAULT '{}',variants_json TEXT NOT NULL DEFAULT '{}',created_by INTEGER NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(sha256,size_bytes),FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_media_assets_category_created ON media_assets(category,created_at)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS media_links (id INTEGER PRIMARY KEY AUTOINCREMENT,asset_id INTEGER NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,role TEXT NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,featured INTEGER NOT NULL DEFAULT 0,public_visible INTEGER NOT NULL DEFAULT 0,download_allowed INTEGER NOT NULL DEFAULT 0,link_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(asset_id,entity_type,entity_id,role),FOREIGN KEY(asset_id) REFERENCES media_assets(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_media_links_entity ON media_links(entity_type,entity_id,role,sort_order)");
    }else{
        $pdo->exec("CREATE TABLE IF NOT EXISTS media_assets (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,uuid VARCHAR(48) NOT NULL UNIQUE,category VARCHAR(40) NOT NULL,mime_type VARCHAR(120) NOT NULL,extension VARCHAR(16) NOT NULL,original_name VARCHAR(255) NOT NULL,stored_path VARCHAR(700) NOT NULL,sha256 CHAR(64) NOT NULL,size_bytes BIGINT NOT NULL DEFAULT 0,width INT NOT NULL DEFAULT 0,height INT NOT NULL DEFAULT 0,duration_seconds DECIMAL(12,3) NOT NULL DEFAULT 0,bitrate_bps BIGINT NOT NULL DEFAULT 0,sample_rate_hz INT NOT NULL DEFAULT 0,channels INT NOT NULL DEFAULT 0,bits_per_sample INT NOT NULL DEFAULT 0,codec VARCHAR(120) NOT NULL DEFAULT '',title VARCHAR(255) NOT NULL DEFAULT '',caption TEXT NOT NULL,alt_text VARCHAR(500) NOT NULL DEFAULT '',credit VARCHAR(255) NOT NULL DEFAULT '',copyright_text VARCHAR(500) NOT NULL DEFAULT '',technical_json LONGTEXT NOT NULL,variants_json LONGTEXT NOT NULL,created_by BIGINT UNSIGNED NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,UNIQUE KEY uq_media_hash_size(sha256,size_bytes),INDEX idx_media_assets_category_created(category,created_at),CONSTRAINT fk_media_created_by FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS media_links (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,asset_id BIGINT UNSIGNED NOT NULL,entity_type VARCHAR(40) NOT NULL,entity_id VARCHAR(160) NOT NULL,role VARCHAR(60) NOT NULL,sort_order INT NOT NULL DEFAULT 0,featured TINYINT(1) NOT NULL DEFAULT 0,public_visible TINYINT(1) NOT NULL DEFAULT 0,download_allowed TINYINT(1) NOT NULL DEFAULT 0,link_json LONGTEXT NOT NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,UNIQUE KEY uq_media_link(asset_id,entity_type,entity_id,role),INDEX idx_media_links_entity(entity_type,entity_id,role,sort_order),CONSTRAINT fk_media_link_asset FOREIGN KEY(asset_id) REFERENCES media_assets(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    }$done=true;
}
function sf_media_ini_bytes(string $value): int {$value=trim($value);if($value==='')return 0;$n=(float)$value;$u=strtolower(substr($value,-1));return (int)round($n*($u==='g'?1073741824:($u==='m'?1048576:($u==='k'?1024:1))));}
function sf_media_capabilities(): array {$upload=sf_media_ini_bytes((string)ini_get('upload_max_filesize'));$post=sf_media_ini_bytes((string)ini_get('post_max_size'));$effective=min(array_filter([$upload,$post,1073741824],fn($x)=>$x>0)?:[1073741824]);return ['ffprobe'=>sf_media_ffprobe_path()!=='','gd'=>extension_loaded('gd'),'upload_max_bytes'=>$effective,'upload_max_label'=>round($effective/1048576,1).' MB','audio_fallbacks'=>['wav_riff'=>true,'mp3_frame_id3'=>true]];}
function sf_media_allowed(): array {
    return [
      'audio'=>['audio/mpeg'=>['mp3'],'audio/mp3'=>['mp3'],'audio/wav'=>['wav'],'audio/x-wav'=>['wav'],'audio/wave'=>['wav'],'audio/vnd.wave'=>['wav']],
      'image'=>['image/jpeg'=>['jpg','jpeg'],'image/png'=>['png'],'image/webp'=>['webp'],'image/gif'=>['gif']],
      'video'=>['video/mp4'=>['mp4'],'video/webm'=>['webm'],'video/quicktime'=>['mov']],
      'document'=>['application/pdf'=>['pdf'],'text/plain'=>['txt'],'text/markdown'=>['md'],'application/rtf'=>['rtf']]
    ];
}
function sf_media_detect_type(string $tmp,string $name): array {
    $ext=strtolower(pathinfo($name,PATHINFO_EXTENSION));$mime='';
    if(class_exists('finfo')){$fi=new finfo(FILEINFO_MIME_TYPE);$mime=(string)$fi->file($tmp);}elseif(function_exists('mime_content_type'))$mime=(string)@mime_content_type($tmp);
    foreach(sf_media_allowed() as $cat=>$map)foreach($map as $m=>$exts)if($mime===$m&&in_array($ext,$exts,true))return ['category'=>$cat,'mime'=>$mime,'extension'=>$ext==='jpeg'?'jpg':$ext];
    $head=(string)@file_get_contents($tmp,false,null,0,16);
    if($ext==='wav'&&strlen($head)>=12&&substr($head,0,4)==='RIFF'&&substr($head,8,4)==='WAVE')return ['category'=>'audio','mime'=>'audio/wav','extension'=>'wav'];
    if($ext==='mp3'&&(substr($head,0,3)==='ID3'||(strlen($head)>=2&&ord($head[0])===0xFF&&(ord($head[1])&0xE0)===0xE0)))return ['category'=>'audio','mime'=>'audio/mpeg','extension'=>'mp3'];
    if($ext==='pdf'&&substr($head,0,4)==='%PDF')return ['category'=>'document','mime'=>'application/pdf','extension'=>'pdf'];
    throw new InvalidArgumentException('Unsupported media type or file signature. Allowed: MP3, WAV, JPG, PNG, WebP, GIF, MP4, WebM, MOV, PDF, TXT, MD, RTF.');
}
function sf_media_shell_available(string $fn='shell_exec'): bool {
    if(!function_exists($fn))return false;$disabled=array_map('trim',explode(',',(string)ini_get('disable_functions')));return !in_array($fn,$disabled,true);
}
function sf_media_ffprobe_path(): string {
    static $cached=null;if($cached!==null)return $cached;if(!sf_media_shell_available())return $cached='';
    $out=trim((string)@shell_exec('command -v ffprobe 2>/dev/null'));return $cached=(is_file($out)&&is_executable($out)?$out:'');
}
function sf_media_ffprobe(string $path): array {
    $bin=sf_media_ffprobe_path();if($bin==='')return [];$cmd=escapeshellarg($bin).' -v quiet -print_format json -show_format -show_streams '.escapeshellarg($path).' 2>/dev/null';$raw=(string)@shell_exec($cmd);$j=json_decode($raw,true);if(!is_array($j))return [];
    $tech=['source'=>'ffprobe','format_name'=>(string)($j['format']['format_name']??''),'format_long_name'=>(string)($j['format']['format_long_name']??''),'tags'=>(array)($j['format']['tags']??[]),'streams'=>[],'embedded_artwork'=>false];
    $duration=(float)($j['format']['duration']??0);$bitrate=(int)($j['format']['bit_rate']??0);$width=0;$height=0;$sr=0;$channels=0;$bits=0;$codec='';
    foreach((array)($j['streams']??[]) as $s){$type=(string)($s['codec_type']??'');$tech['streams'][]=['type'=>$type,'codec'=>(string)($s['codec_name']??''),'profile'=>(string)($s['profile']??''),'duration'=>(float)($s['duration']??0),'bit_rate'=>(int)($s['bit_rate']??0),'sample_rate'=>(int)($s['sample_rate']??0),'channels'=>(int)($s['channels']??0),'width'=>(int)($s['width']??0),'height'=>(int)($s['height']??0),'bits_per_sample'=>(int)($s['bits_per_sample']??($s['bits_per_raw_sample']??0)),'tags'=>(array)($s['tags']??[])];if($type==='audio'){$codec=$codec?:((string)($s['codec_name']??''));$duration=max($duration,(float)($s['duration']??0));$bitrate=max($bitrate,(int)($s['bit_rate']??0));$sr=max($sr,(int)($s['sample_rate']??0));$channels=max($channels,(int)($s['channels']??0));$bits=max($bits,(int)($s['bits_per_sample']??($s['bits_per_raw_sample']??0)));}if($type==='video'){$width=max($width,(int)($s['width']??0));$height=max($height,(int)($s['height']??0));if(!empty($s['disposition']['attached_pic']))$tech['embedded_artwork']=true;if($codec==='')$codec=(string)($s['codec_name']??'');}}
    $tags=array_change_key_case((array)($j['format']['tags']??[]),CASE_LOWER);$tech['normalized_tags']=['title'=>(string)($tags['title']??''),'artist'=>(string)($tags['artist']??''),'album'=>(string)($tags['album']??''),'year'=>(string)($tags['date']??($tags['year']??'')),'track'=>(string)($tags['track']??''),'genre'=>(string)($tags['genre']??''),'comment'=>(string)($tags['comment']??'')];
    return ['duration'=>$duration,'bitrate'=>$bitrate,'sample_rate'=>$sr,'channels'=>$channels,'bits'=>$bits,'codec'=>$codec,'width'=>$width,'height'=>$height,'technical'=>$tech];
}
function sf_media_wav_fallback(string $path): array {
    $fh=@fopen($path,'rb');if(!$fh)return [];$head=fread($fh,12);if(strlen($head)!==12||substr($head,0,4)!=='RIFF'||substr($head,8,4)!=='WAVE'){fclose($fh);return [];}
    $fmt=[];$dataSize=0;$info=[];while(!feof($fh)){ $h=fread($fh,8);if(strlen($h)<8)break;$id=substr($h,0,4);$len=unpack('V',substr($h,4,4))[1]??0;if($len<0||$len>1024*1024*1024)break;$chunk=fread($fh,$len+($len%2));$payload=substr($chunk,0,$len);
      if($id==='fmt '&&$len>=16){$u=unpack('vformat/vchannels/Vsample_rate/Vbyte_rate/vblock_align/vbits',$payload);$fmt=$u?:[];}
      elseif($id==='data')$dataSize=$len;
      elseif($id==='LIST'&&substr($payload,0,4)==='INFO'){$p=4;while($p+8<=strlen($payload)){$iid=substr($payload,$p,4);$ilen=unpack('V',substr($payload,$p+4,4))[1]??0;$val=trim(substr($payload,$p+8,$ilen),"\0 \r\n\t");if($val!=='')$info[$iid]=$val;$p+=8+$ilen+($ilen%2);}}
    }fclose($fh);$byteRate=(int)($fmt['byte_rate']??0);$duration=$byteRate>0?$dataSize/$byteRate:0;$formats=[1=>'pcm',3=>'ieee_float',6=>'alaw',7=>'mulaw',65534=>'extensible'];
    return ['duration'=>$duration,'bitrate'=>$byteRate*8,'sample_rate'=>(int)($fmt['sample_rate']??0),'channels'=>(int)($fmt['channels']??0),'bits'=>(int)($fmt['bits']??0),'codec'=>$formats[(int)($fmt['format']??0)]??('wav_'.(int)($fmt['format']??0)),'width'=>0,'height'=>0,'technical'=>['source'=>'wav_riff','audio_format'=>(int)($fmt['format']??0),'byte_rate'=>$byteRate,'block_align'=>(int)($fmt['block_align']??0),'data_bytes'=>$dataSize,'info'=>$info,'normalized_tags'=>['title'=>(string)($info['INAM']??''),'artist'=>(string)($info['IART']??''),'album'=>(string)($info['IPRD']??''),'year'=>(string)($info['ICRD']??''),'track'=>'','genre'=>(string)($info['IGNR']??''),'comment'=>(string)($info['ICMT']??'')]]];
}
function sf_media_syncsafe(string $b): int {if(strlen($b)<4)return 0;return (ord($b[0])<<21)|(ord($b[1])<<14)|(ord($b[2])<<7)|ord($b[3]);}
function sf_media_id3_text(string $payload): string {if($payload==='')return '';$enc=ord($payload[0]);$s=substr($payload,1);if($enc===0)return trim($s,"\0 \r\n\t");if($enc===3)return trim($s,"\0 \r\n\t");if(function_exists('mb_convert_encoding')){if($enc===1)return trim((string)@mb_convert_encoding($s,'UTF-8','UTF-16'));if($enc===2)return trim((string)@mb_convert_encoding($s,'UTF-8','UTF-16BE'));}return trim($s,"\0 \r\n\t");}
function sf_media_mp3_fallback(string $path): array {
    $size=filesize($path)?:0;$fh=@fopen($path,'rb');if(!$fh)return [];$start=0;$tags=[];$art=false;$h=fread($fh,10);
    if(substr($h,0,3)==='ID3'){$ver=ord($h[3]);$tagSize=sf_media_syncsafe(substr($h,6,4));$start=10+$tagSize;$payload=fread($fh,min($tagSize,16*1024*1024));$p=0;while($p+10<=strlen($payload)){ $id=substr($payload,$p,4);if(!preg_match('/^[A-Z0-9]{4}$/',$id))break;$len=$ver===4?sf_media_syncsafe(substr($payload,$p+4,4)):(unpack('N',substr($payload,$p+4,4))[1]??0);if($len<=0||$p+10+$len>strlen($payload))break;$v=substr($payload,$p+10,$len);if(in_array($id,['TIT2','TPE1','TALB','TDRC','TYER','TRCK','TCON'],true))$tags[$id]=sf_media_id3_text($v);elseif($id==='COMM')$tags[$id]=sf_media_id3_text(substr($v,4));elseif($id==='APIC')$art=true;$p+=10+$len;}}
    if($size>=128){fseek($fh,-128,SEEK_END);$v=fread($fh,128);if(substr($v,0,3)==='TAG'){$tags['TIT2']=$tags['TIT2']??trim(substr($v,3,30));$tags['TPE1']=$tags['TPE1']??trim(substr($v,33,30));$tags['TALB']=$tags['TALB']??trim(substr($v,63,30));$tags['TYER']=$tags['TYER']??trim(substr($v,93,4));$tags['COMM']=$tags['COMM']??trim(substr($v,97,30));}}
    fseek($fh,$start);$buf=fread($fh,min(max(0,$size-$start),1024*1024));fclose($fh);$bitrate=0;$sample=0;$channels=0;$codec='mp3';
    $bitrates=[1=>[1=>[32,40,48,56,64,80,96,112,128,160,192,224,256,320],2=>[32,48,56,64,80,96,112,128,160,192,224,256,320,384],3=>[32,40,48,56,64,80,96,112,128,160,192,224,256]],2=>[1=>[32,48,56,64,80,96,112,128,144,160,176,192,224,256],2=>[8,16,24,32,40,48,56,64,80,96,112,128,144,160],3=>[8,16,24,32,40,48,56,64,80,96,112,128,144,160]]];$samples=[1=>[44100,48000,32000],2=>[22050,24000,16000],25=>[11025,12000,8000]];
    for($i=0,$n=strlen($buf)-4;$i<$n;$i++){if(ord($buf[$i])!==0xFF||(ord($buf[$i+1])&0xE0)!==0xE0)continue;$b2=ord($buf[$i+1]);$b3=ord($buf[$i+2]);$b4=ord($buf[$i+3]);$verBits=($b2>>3)&3;$layerBits=($b2>>1)&3;$ver=$verBits===3?1:($verBits===2?2:($verBits===0?25:0));$layer=$layerBits===3?1:($layerBits===2?2:($layerBits===1?3:0));$bi=($b3>>4)&15;$si=($b3>>2)&3;if(!$ver||!$layer||$bi===0||$bi===15||$si===3)continue;$vkey=$ver===1?1:2;$kbps=$bitrates[$vkey][$layer][$bi-1]??0;$sr=$samples[$ver][$si]??0;if($kbps&&$sr){$bitrate=$kbps*1000;$sample=$sr;$channels=(($b4>>6)&3)===3?1:2;$codec='mpeg'.($ver===25?'2.5':$ver).'_layer'.$layer;break;}}
    $audioBytes=max(0,$size-$start-($size>=128?128:0));$duration=$bitrate>0?($audioBytes*8/$bitrate):0;
    return ['duration'=>$duration,'bitrate'=>$bitrate,'sample_rate'=>$sample,'channels'=>$channels,'bits'=>0,'codec'=>$codec,'width'=>0,'height'=>0,'technical'=>['source'=>'mp3_frame','id3'=>$tags,'embedded_artwork'=>$art,'normalized_tags'=>['title'=>(string)($tags['TIT2']??''),'artist'=>(string)($tags['TPE1']??''),'album'=>(string)($tags['TALB']??''),'year'=>(string)($tags['TDRC']??($tags['TYER']??'')),'track'=>(string)($tags['TRCK']??''),'genre'=>(string)($tags['TCON']??''),'comment'=>(string)($tags['COMM']??'')]]];
}
function sf_media_analyze(string $path,string $category,string $ext): array {
    $a=sf_media_ffprobe($path);
    if(!$a&&$category==='audio'&&$ext==='wav')$a=sf_media_wav_fallback($path);
    if(!$a&&$category==='audio'&&$ext==='mp3')$a=sf_media_mp3_fallback($path);
    if($category==='image'){[$w,$h]=@getimagesize($path)?:[0,0];$a=array_merge(['duration'=>0,'bitrate'=>0,'sample_rate'=>0,'channels'=>0,'bits'=>0,'codec'=>$ext,'technical'=>['source'=>'php_image']],$a,['width'=>$w,'height'=>$h]);}
    return array_merge(['duration'=>0,'bitrate'=>0,'sample_rate'=>0,'channels'=>0,'bits'=>0,'codec'=>'','width'=>0,'height'=>0,'technical'=>['source'=>'basic']],$a);
}
function sf_media_safe_ext(string $ext): string {return preg_replace('/[^a-z0-9]/','',strtolower($ext))?:'bin';}
function sf_media_asset(int|string $id): ?array {
    sf_media_ensure_schema();$col=is_int($id)||ctype_digit((string)$id)?'id':'uuid';$q=sf_db()->prepare("SELECT * FROM media_assets WHERE $col=? LIMIT 1");$q->execute([$id]);$r=$q->fetch();if(!$r)return null;$r['technical']=sf_media_decode($r['technical_json']??'',[]);$r['variants']=sf_media_decode($r['variants_json']??'',[]);return $r;
}
function sf_media_generate_variants(array $asset): array {
    if(($asset['category']??'')!=='image'||!extension_loaded('gd'))return [];$src=SF_ROOT.'/'.ltrim((string)$asset['stored_path'],'/');if(!is_file($src))return [];if((int)($asset['width']??0)*(int)($asset['height']??0)>60000000)return [];$mime=(string)$asset['mime_type'];$create=$mime==='image/jpeg'?'imagecreatefromjpeg':($mime==='image/png'?'imagecreatefrompng':($mime==='image/webp'?'imagecreatefromwebp':($mime==='image/gif'?'imagecreatefromgif':'')));if($create===''||!function_exists($create))return [];$im=@$create($src);if(!$im)return [];$sw=imagesx($im);$sh=imagesy($im);$dir=SF_ROOT.'/storage/media/variants/'.$asset['uuid'];if(!is_dir($dir)&&!mkdir($dir,0770,true)&&!is_dir($dir)){imagedestroy($im);return [];}
    $out=[];foreach(['large'=>1600,'medium'=>800,'thumb'=>320] as $name=>$max){$scale=min(1,$max/max($sw,$sh));$w=max(1,(int)round($sw*$scale));$h=max(1,(int)round($sh*$scale));$dst=imagecreatetruecolor($w,$h);if(in_array($mime,['image/png','image/webp','image/gif'],true)){imagealphablending($dst,false);imagesavealpha($dst,true);}$bg=imagecolorallocatealpha($dst,0,0,0,127);imagefill($dst,0,0,$bg);imagecopyresampled($dst,$im,0,0,0,0,$w,$h,$sw,$sh);$rel='storage/media/variants/'.$asset['uuid'].'/'.$name.'.webp';$ok=function_exists('imagewebp')?imagewebp($dst,SF_ROOT.'/'.$rel,86):false;if(!$ok){$rel='storage/media/variants/'.$asset['uuid'].'/'.$name.'.jpg';$ok=imagejpeg($dst,SF_ROOT.'/'.$rel,88);}imagedestroy($dst);if($ok)$out[$name]=['path'=>$rel,'width'=>$w,'height'=>$h];}imagedestroy($im);return $out;
}
function sf_media_register_existing_file(string $storedPath,string $originalName,int $adminId=0): array {
    sf_media_ensure_schema();$root=realpath(SF_ROOT.'/storage/media');$abs=realpath(SF_ROOT.'/'.ltrim($storedPath,'/'));if(!$root||!$abs||!str_starts_with($abs,$root.DIRECTORY_SEPARATOR)||!is_file($abs))throw new InvalidArgumentException('Existing media file is outside managed media storage.');$size=filesize($abs)?:0;$type=sf_media_detect_type($abs,$originalName);$sha=hash_file('sha256',$abs);if(!$sha)throw new RuntimeException('Could not hash existing media.');$q=sf_db()->prepare('SELECT id FROM media_assets WHERE sha256=? AND size_bytes=? LIMIT 1');$q->execute([$sha,$size]);$existing=(int)($q->fetchColumn()?:0);if($existing)return sf_media_asset($existing)?:[];
    $a=sf_media_analyze($abs,$type['category'],sf_media_safe_ext($type['extension']));$tags=(array)($a['technical']['normalized_tags']??[]);$uuid=sf_media_uuid();$now=gmdate('c');$title=sf_clean_text($tags['title']??pathinfo($originalName,PATHINFO_FILENAME),255);$q=sf_db()->prepare('INSERT INTO media_assets(uuid,category,mime_type,extension,original_name,stored_path,sha256,size_bytes,width,height,duration_seconds,bitrate_bps,sample_rate_hz,channels,bits_per_sample,codec,title,caption,alt_text,credit,copyright_text,technical_json,variants_json,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$q->execute([$uuid,$type['category'],$type['mime'],sf_media_safe_ext($type['extension']),sf_clean_text($originalName,255),ltrim($storedPath,'/'),$sha,$size,(int)$a['width'],(int)$a['height'],round((float)$a['duration'],3),(int)$a['bitrate'],(int)$a['sample_rate'],(int)$a['channels'],(int)$a['bits'],sf_clean_text($a['codec'],120),$title,'','','','',sf_media_json($a['technical']),sf_media_json([]),$adminId?:null,$now,$now]);return sf_media_asset((int)sf_db()->lastInsertId())?:[];
}
function sf_media_register_local_copy(string $sourcePath,string $originalName,int $adminId=0): array {
    sf_media_ensure_schema();$root=realpath(SF_ROOT);$src=realpath($sourcePath);if(!$root||!$src||!str_starts_with($src,$root.DIRECTORY_SEPARATOR)||!is_file($src))throw new InvalidArgumentException('Legacy media source is unavailable.');$size=filesize($src)?:0;$type=sf_media_detect_type($src,$originalName);$sha=hash_file('sha256',$src);if(!$sha)throw new RuntimeException('Could not hash legacy media.');$q=sf_db()->prepare('SELECT id FROM media_assets WHERE sha256=? AND size_bytes=? LIMIT 1');$q->execute([$sha,$size]);$existing=(int)($q->fetchColumn()?:0);if($existing)return sf_media_asset($existing)?:[];
    $dir='storage/media/library/'.$type['category'].'/'.substr($sha,0,2);$absDir=SF_ROOT.'/'.$dir;if(!is_dir($absDir)&&!mkdir($absDir,0770,true)&&!is_dir($absDir))throw new RuntimeException('Could not create media library storage.');$rel=$dir.'/legacy-'.substr($sha,0,16).'.'.sf_media_safe_ext($type['extension']);$dest=SF_ROOT.'/'.$rel;if(!is_file($dest)&&!copy($src,$dest))throw new RuntimeException('Could not copy legacy media into managed storage.');try{return sf_media_register_existing_file($rel,$originalName,$adminId);}catch(Throwable $e){@unlink($dest);throw $e;}
}
function sf_media_backfill_catalog(): array {
    sf_media_ensure_schema();$catalog=sf_catalog();$index=[];$indexPath=SF_ROOT.'/storage/media/index.json';if(is_file($indexPath)){$j=json_decode((string)file_get_contents($indexPath),true);if(is_array($j))$index=(array)($j['files']??[]);}$counts=['tracks'=>0,'audio'=>0,'artwork'=>0,'archive'=>0,'skipped'=>0];
    foreach($catalog as $t){$trackId=sf_clean_text($t['id']??'',160);if($trackId==='')continue;$counts['tracks']++;$source=(array)($t['metadata']['source']??[]);
      foreach([['master_sha256','master_audio',false],['preview_sha256','primary_audio',true]] as [$key,$role,$public]){$hash=(string)($source[$key]??'');$row=$hash!==''?($index[$hash]??null):null;if(is_array($row)&&!empty($row['stored_path'])){try{$a=sf_media_register_existing_file((string)$row['stored_path'],basename((string)$row['stored_path']),0);sf_media_attach((int)$a['id'],'track',$trackId,$role,['public_visible'=>$public,'download_allowed'=>false]);$counts['audio']++;}catch(Throwable $e){$counts['skipped']++;}}}
      $hasPreview=(string)($source['preview_sha256']??'')!=='';if(!$hasPreview){$audio=(string)($t['audio']??'');if($audio!==''&&!preg_match('#^(?:https?:)?//#i',$audio)&&!str_starts_with($audio,'api/')){try{$a=sf_media_register_local_copy(SF_ROOT.'/'.ltrim($audio,'/'),basename($audio),0);sf_media_attach((int)$a['id'],'track',$trackId,'primary_audio',['public_visible'=>true,'download_allowed'=>false]);$counts['audio']++;}catch(Throwable $e){$counts['skipped']++;}}}
      $art=(string)($t['artwork']??'');if($art!==''&&!preg_match('#^(?:https?:)?//#i',$art)&&!str_starts_with($art,'api/')){try{$a=sf_media_register_local_copy(SF_ROOT.'/'.ltrim($art,'/'),basename($art),0);sf_media_attach((int)$a['id'],'track',$trackId,'primary_artwork',['public_visible'=>true,'featured'=>true]);$counts['artwork']++;}catch(Throwable $e){$counts['skipped']++;}}
      foreach((array)($t['archive']['media']??[]) as $m){$url=(string)($m['url']??'');if($url===''||preg_match('#^(?:https?:)?//#i',$url)||str_starts_with($url,'api/'))continue;try{$a=sf_media_register_local_copy(SF_ROOT.'/'.ltrim($url,'/'),basename($url),0);sf_media_attach((int)$a['id'],'track',$trackId,'archive',['public_visible'=>true,'download_allowed'=>false,'link'=>['legacy_title'=>$m['title']??'','legacy_caption'=>$m['caption']??'']]);$counts['archive']++;}catch(Throwable $e){$counts['skipped']++;}}
    }return $counts;
}
function sf_media_ingest_upload(array $file,int $adminId): array {
    sf_media_ensure_schema();if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('Upload failed with PHP code '.(int)($file['error']??-1).'.');$tmp=(string)($file['tmp_name']??'');if(!is_uploaded_file($tmp))throw new RuntimeException('Invalid uploaded file.');$size=(int)($file['size']??0);if($size<=0)throw new InvalidArgumentException('The uploaded file is empty.');if($size>1024*1024*1024)throw new InvalidArgumentException('Media file exceeds the 1 GB application limit.');
    $type=sf_media_detect_type($tmp,(string)($file['name']??'media'));$sha=hash_file('sha256',$tmp);if(!$sha)throw new RuntimeException('Could not hash uploaded file.');$q=sf_db()->prepare('SELECT id FROM media_assets WHERE sha256=? AND size_bytes=? LIMIT 1');$q->execute([$sha,$size]);$existing=(int)($q->fetchColumn()?:0);if($existing)return sf_media_asset($existing)?:[];
    $uuid=sf_media_uuid();$ext=sf_media_safe_ext($type['extension']);$dir='storage/media/library/'.$type['category'].'/'.substr($sha,0,2);$absDir=SF_ROOT.'/'.$dir;if(!is_dir($absDir)&&!mkdir($absDir,0770,true)&&!is_dir($absDir))throw new RuntimeException('Could not create media storage.');$rel=$dir.'/'.$uuid.'.'.$ext;$abs=SF_ROOT.'/'.$rel;if(!move_uploaded_file($tmp,$abs))throw new RuntimeException('Could not store uploaded media.');
    try{$a=sf_media_analyze($abs,$type['category'],$ext);$tags=(array)($a['technical']['normalized_tags']??[]);$title=sf_clean_text($tags['title']??pathinfo((string)$file['name'],PATHINFO_FILENAME),255);$now=gmdate('c');$q=sf_db()->prepare('INSERT INTO media_assets(uuid,category,mime_type,extension,original_name,stored_path,sha256,size_bytes,width,height,duration_seconds,bitrate_bps,sample_rate_hz,channels,bits_per_sample,codec,title,caption,alt_text,credit,copyright_text,technical_json,variants_json,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$q->execute([$uuid,$type['category'],$type['mime'],$ext,sf_clean_text($file['name']??'media',255),$rel,$sha,$size,(int)$a['width'],(int)$a['height'],round((float)$a['duration'],3),(int)$a['bitrate'],(int)$a['sample_rate'],(int)$a['channels'],(int)$a['bits'],sf_clean_text($a['codec'],120),$title,'','','','',sf_media_json($a['technical']),sf_media_json([]),$adminId?:null,$now,$now]);$id=(int)sf_db()->lastInsertId();$asset=sf_media_asset($id)?:[];$variants=sf_media_generate_variants($asset);if($variants){sf_db()->prepare('UPDATE media_assets SET variants_json=?,updated_at=? WHERE id=?')->execute([sf_media_json($variants),gmdate('c'),$id]);$asset=sf_media_asset($id)?:$asset;}return $asset;}catch(Throwable $e){@unlink($abs);throw $e;}
}
function sf_media_links(string $entityType,string $entityId): array {
    sf_media_ensure_schema();$q=sf_db()->prepare('SELECT l.*,a.uuid,a.category,a.mime_type,a.extension,a.original_name,a.size_bytes,a.width,a.height,a.duration_seconds,a.bitrate_bps,a.sample_rate_hz,a.channels,a.bits_per_sample,a.codec,a.title,a.caption,a.alt_text,a.credit,a.copyright_text,a.technical_json,a.variants_json FROM media_links l JOIN media_assets a ON a.id=l.asset_id WHERE l.entity_type=? AND l.entity_id=? ORDER BY l.role,l.sort_order,l.id');$q->execute([$entityType,$entityId]);$rows=$q->fetchAll();foreach($rows as &$r){$r['technical']=sf_media_decode($r['technical_json']??'',[]);$r['variants']=sf_media_decode($r['variants_json']??'',[]);$r['link']=sf_media_decode($r['link_json']??'',[]);}unset($r);return $rows;
}
function sf_media_attach(int $assetId,string $entityType,string $entityId,string $role,array $opts=[]): array {
    sf_media_ensure_schema();$asset=sf_media_asset($assetId);if(!$asset)throw new InvalidArgumentException('Media asset not found.');$allowedEntities=['track','release','show','campaign','site','store','member_content'];if(!in_array($entityType,$allowedEntities,true))throw new InvalidArgumentException('Unsupported media entity.');$entityId=sf_clean_text($entityId,160);$role=sf_clean_text($role,60);if($entityId===''||$role==='')throw new InvalidArgumentException('Media entity and role are required.');$now=gmdate('c');$q=sf_db()->prepare('SELECT COALESCE(MAX(sort_order),-1)+1 FROM media_links WHERE entity_type=? AND entity_id=? AND role=?');$q->execute([$entityType,$entityId,$role]);$sort=(int)$q->fetchColumn();
    try{$q=sf_db()->prepare('INSERT INTO media_links(asset_id,entity_type,entity_id,role,sort_order,featured,public_visible,download_allowed,link_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$q->execute([$assetId,$entityType,$entityId,$role,$sort,!empty($opts['featured'])?1:0,!empty($opts['public_visible'])?1:0,!empty($opts['download_allowed'])?1:0,sf_media_json((array)($opts['link']??[])),$now,$now]);}catch(PDOException $e){if(!in_array((string)$e->getCode(),['23000','19'],true))throw $e;}
    return sf_media_links($entityType,$entityId);
}
function sf_media_detach(int $linkId): bool {$q=sf_db()->prepare('DELETE FROM media_links WHERE id=?');$q->execute([$linkId]);return $q->rowCount()>0;}
function sf_media_update_asset(int $id,array $p): array {$allowed=['title'=>255,'caption'=>4000,'alt_text'=>500,'credit'=>255,'copyright_text'=>500];$sets=[];$args=[];foreach($allowed as $k=>$max)if(array_key_exists($k,$p)){$sets[]="$k=?";$args[]=sf_clean_text($p[$k],$max);}if($sets){$sets[]='updated_at=?';$args[]=gmdate('c');$args[]=$id;sf_db()->prepare('UPDATE media_assets SET '.implode(',',$sets).' WHERE id=?')->execute($args);}return sf_media_asset($id)?:[];}
function sf_media_update_link(int $id,array $p): void {$sets=[];$args=[];foreach(['featured','public_visible','download_allowed'] as $k)if(array_key_exists($k,$p)){$sets[]="$k=?";$args[]=!empty($p[$k])?1:0;}if(array_key_exists('role',$p)){$sets[]='role=?';$args[]=sf_clean_text($p['role'],60);}if(array_key_exists('sort_order',$p)){$sets[]='sort_order=?';$args[]=(int)$p['sort_order'];}if(!$sets)return;$sets[]='updated_at=?';$args[]=gmdate('c');$args[]=$id;sf_db()->prepare('UPDATE media_links SET '.implode(',',$sets).' WHERE id=?')->execute($args);}
function sf_media_delete_asset(int $id): bool {$asset=sf_media_asset($id);if(!$asset)return false;$q=sf_db()->prepare('SELECT COUNT(*) FROM media_links WHERE asset_id=?');$q->execute([$id]);if((int)$q->fetchColumn()>0)throw new RuntimeException('Detach this asset everywhere before deleting it.');$paths=[(string)$asset['stored_path']];foreach((array)$asset['variants'] as $v)if(!empty($v['path']))$paths[]=(string)$v['path'];$q=sf_db()->prepare('DELETE FROM media_assets WHERE id=?');$q->execute([$id]);if($q->rowCount())foreach($paths as $p){$abs=realpath(SF_ROOT.'/'.ltrim($p,'/'));$root=realpath(SF_ROOT.'/storage/media');if($abs&&$root&&str_starts_with($abs,$root.DIRECTORY_SEPARATOR))@unlink($abs);}return $q->rowCount()>0;}
function sf_media_list(string $category='',string $q='',int $limit=300): array {sf_media_ensure_schema();$where=['1=1'];$args=[];if($category!==''){$where[]='category=?';$args[]=$category;}if($q!==''){$where[]='(title LIKE ? OR original_name LIKE ? OR caption LIKE ?)';$like='%'.$q.'%';array_push($args,$like,$like,$like);}$sql='SELECT a.*,(SELECT COUNT(*) FROM media_links l WHERE l.asset_id=a.id) link_count FROM media_assets a WHERE '.implode(' AND ',$where).' ORDER BY a.id DESC LIMIT '.max(1,min(1000,$limit));$st=sf_db()->prepare($sql);$st->execute($args);$rows=$st->fetchAll();foreach($rows as &$r){$r['technical']=sf_media_decode($r['technical_json']??'',[]);$r['variants']=sf_media_decode($r['variants_json']??'',[]);}unset($r);return $rows;}
function sf_media_public_links(string $entityType,string $entityId): array {
    $rows=sf_media_links($entityType,$entityId);$out=[];
    foreach($rows as $r)if(!empty($r['public_visible']))$out[]=[
        'uuid'=>(string)$r['uuid'],'category'=>(string)$r['category'],'role'=>(string)$r['role'],'title'=>(string)$r['title'],'caption'=>(string)$r['caption'],'alt_text'=>(string)$r['alt_text'],'credit'=>(string)$r['credit'],'copyright'=>(string)$r['copyright_text'],'featured'=>!empty($r['featured']),'download_allowed'=>!empty($r['download_allowed']),'duration'=>(float)$r['duration_seconds'],'width'=>(int)$r['width'],'height'=>(int)$r['height'],'url'=>'api/media.php?id='.rawurlencode((string)$r['uuid']),'thumb_url'=>!empty($r['variants']['thumb'])?'api/media.php?id='.rawurlencode((string)$r['uuid']).'&variant=thumb':'api/media.php?id='.rawurlencode((string)$r['uuid']),'download_url'=>!empty($r['download_allowed'])?'api/media.php?id='.rawurlencode((string)$r['uuid']).'&download=1':''
    ];
    return $out;
}
function sf_media_publish_track_artwork(string $trackId,int $linkId): array {
    sf_media_ensure_schema();$q=sf_db()->prepare("SELECT l.*,a.* FROM media_links l JOIN media_assets a ON a.id=l.asset_id WHERE l.id=? AND l.entity_type='track' AND l.entity_id=?");$q->execute([$linkId,$trackId]);$r=$q->fetch();if(!$r||$r['category']!=='image')throw new InvalidArgumentException('Choose an image asset attached to this track.');$catalog=sf_catalog();$idx=null;foreach($catalog as $i=>$t)if((string)($t['id']??'')===$trackId){$idx=$i;break;}if($idx===null)throw new InvalidArgumentException('Track not found.');
    $old=(string)($catalog[$idx]['artwork']??'');$new='api/media.php?id='.rawurlencode((string)$r['uuid']).'&variant=large';$catalog[$idx]['artwork']=$new;$catalog[$idx]['media_primary_artwork_asset']=(int)$r['asset_id'];if(function_exists('sf_admin_write_catalog'))sf_admin_write_catalog($catalog);else throw new RuntimeException('Catalog writer unavailable.');
    sf_db()->prepare("UPDATE media_links SET role='artwork',featured=0,public_visible=0,updated_at=? WHERE entity_type='track' AND entity_id=? AND role='primary_artwork' AND id<>?")->execute([gmdate('c'),$trackId,$linkId]);sf_db()->prepare("UPDATE media_links SET public_visible=1,featured=1,role='primary_artwork',updated_at=? WHERE id=?")->execute([gmdate('c'),$linkId]);return ['track'=>$catalog[$idx],'previous_artwork'=>$old,'asset'=>sf_media_asset((int)$r['asset_id'])];
}
function sf_media_publish_track_audio(string $trackId,int $linkId): array {
    sf_media_ensure_schema();$q=sf_db()->prepare("SELECT l.*,a.* FROM media_links l JOIN media_assets a ON a.id=l.asset_id WHERE l.id=? AND l.entity_type='track' AND l.entity_id=?");$q->execute([$linkId,$trackId]);$r=$q->fetch();if(!$r||$r['category']!=='audio')throw new InvalidArgumentException('Choose an audio asset attached to this track.');$catalog=sf_catalog();$idx=null;foreach($catalog as $i=>$t)if((string)($t['id']??'')===$trackId){$idx=$i;break;}if($idx===null)throw new InvalidArgumentException('Track not found.');
    $old=(string)($catalog[$idx]['audio']??'');$new='api/media.php?id='.rawurlencode((string)$r['uuid']);$catalog[$idx]['audio']=$new;if((float)$r['duration_seconds']>0)$catalog[$idx]['duration']=(int)round((float)$r['duration_seconds']);$catalog[$idx]['media_primary_asset']=(int)$r['asset_id'];if(function_exists('sf_admin_write_catalog'))sf_admin_write_catalog($catalog);else throw new RuntimeException('Catalog writer unavailable.');
    sf_db()->prepare("UPDATE media_links SET role='audio_candidate',public_visible=0,updated_at=? WHERE entity_type='track' AND entity_id=? AND role='primary_audio' AND id<>?")->execute([gmdate('c'),$trackId,$linkId]);sf_db()->prepare("UPDATE media_links SET public_visible=1,role='primary_audio',updated_at=? WHERE id=?")->execute([gmdate('c'),$linkId]);return ['track'=>$catalog[$idx],'previous_audio'=>$old,'asset'=>sf_media_asset((int)$r['asset_id'])];
}


function sf_media_managed_url(array $asset,string $variant='original'): string {
    $url='api/media.php?id='.rawurlencode((string)($asset['uuid']??''));
    if($variant!==''&&$variant!=='original')$url.='&variant='.rawurlencode($variant);
    return $url;
}
function sf_media_entity_label(string $type,string $id): string {
    if($type==='track'){foreach(sf_catalog() as $t)if((string)($t['id']??'')===$id)return (string)($t['title']??$id);}
    if($type==='release'){$p=SF_ROOT.'/data/releases.json';$rows=is_file($p)?json_decode((string)file_get_contents($p),true):[];foreach((array)$rows as $x)if((string)($x['id']??'')===$id)return (string)($x['title']??$id);}
    if($type==='show'){$p=SF_ROOT.'/data/shows.json';$rows=is_file($p)?json_decode((string)file_get_contents($p),true):[];foreach((array)$rows as $x)if((string)($x['id']??'')===$id)return (string)($x['title']??$x['venue']??$id);}
    if($type==='campaign'){sf_campaign_ensure_schema();$q=sf_db()->prepare('SELECT name FROM campaigns WHERE id=?');$q->execute([(int)$id]);$v=$q->fetchColumn();if($v!==false)return (string)$v;}
    if($type==='store'){if(function_exists('sf_commerce_product')){$p=sf_commerce_product($id,false);if($p)return (string)$p['title'];}$cfg=sf_store_config();return (string)($cfg['products'][$id]['label']??$id);}
    if($type==='site')return 'Public site';
    return $id;
}
function sf_media_usage(int $assetId): array {
    sf_media_ensure_schema();$q=sf_db()->prepare('SELECT * FROM media_links WHERE asset_id=? ORDER BY entity_type,entity_id,role,sort_order,id');$q->execute([$assetId]);$rows=$q->fetchAll();
    foreach($rows as &$r){$r['entity_label']=sf_media_entity_label((string)$r['entity_type'],(string)$r['entity_id']);$r['link']=sf_media_decode($r['link_json']??'',[]);}unset($r);
    return $rows;
}
function sf_media_has_link(string $type,string $id,array $roles=[]): bool {
    sf_media_ensure_schema();$sql='SELECT 1 FROM media_links WHERE entity_type=? AND entity_id=?';$args=[$type,$id];if($roles){$sql.=' AND role IN ('.implode(',',array_fill(0,count($roles),'?')).')';$args=array_merge($args,$roles);}$sql.=' LIMIT 1';$q=sf_db()->prepare($sql);$q->execute($args);return (bool)$q->fetchColumn();
}
function sf_media_completeness(): array {
    sf_media_ensure_schema();$pdo=sf_db();$assets=(int)$pdo->query('SELECT COUNT(*) FROM media_assets')->fetchColumn();$bytes=(int)$pdo->query('SELECT COALESCE(SUM(size_bytes),0) FROM media_assets')->fetchColumn();$unused=(int)$pdo->query('SELECT COUNT(*) FROM media_assets a WHERE NOT EXISTS (SELECT 1 FROM media_links l WHERE l.asset_id=a.id)')->fetchColumn();$broken=0;$brokenRows=[];
    foreach($pdo->query('SELECT id,uuid,title,original_name,stored_path FROM media_assets')->fetchAll() as $a){$abs=SF_ROOT.'/'.ltrim((string)$a['stored_path'],'/');if(!is_file($abs)){$broken++;if(count($brokenRows)<100)$brokenRows[]=['asset_id'=>(int)$a['id'],'uuid'=>$a['uuid'],'title'=>$a['title']?:$a['original_name'],'path'=>$a['stored_path']];}}
    $catalog=sf_catalog();$missingTrackAudio=[];$missingTrackArt=[];foreach($catalog as $t){$id=(string)($t['id']??'');if($id==='')continue;if(trim((string)($t['audio']??''))==='')$missingTrackAudio[]=['id'=>$id,'title'=>(string)($t['title']??$id)];if(trim((string)($t['artwork']??''))===''&&!sf_media_has_link('track',$id,['primary_artwork','artwork']))$missingTrackArt[]=['id'=>$id,'title'=>(string)($t['title']??$id)];}
    $rp=SF_ROOT.'/data/releases.json';$rels=is_file($rp)?json_decode((string)file_get_contents($rp),true):[];$missingRelease=[];foreach((array)$rels as $x){$id=(string)($x['id']??'');$cover=(string)($x['artwork']['cover']??'');if($id!==''&&$cover===''&&!sf_media_has_link('release',$id,['cover']))$missingRelease[]=['id'=>$id,'title'=>(string)($x['title']??$id)];}
    $sp=SF_ROOT.'/data/shows.json';$shows=is_file($sp)?json_decode((string)file_get_contents($sp),true):[];$missingShow=[];foreach((array)$shows as $x){$id=(string)($x['id']??'');if($id!==''&&trim((string)($x['poster']??''))===''&&!sf_media_has_link('show',$id,['poster']))$missingShow[]=['id'=>$id,'title'=>(string)($x['title']??$x['venue']??$id)];}
    $missingCampaign=[];try{$q=$pdo->query("SELECT id,name,status,artwork FROM campaigns WHERE status IN ('published','scheduled')");foreach($q->fetchAll() as $x){$id=(string)$x['id'];if(trim((string)$x['artwork'])===''&&!sf_media_has_link('campaign',$id,['hero']))$missingCampaign[]=['id'=>$id,'title'=>(string)$x['name']];}}catch(Throwable $e){}
    $missingStore=[];$cfg=sf_store_config();foreach((array)($cfg['products']??[]) as $id=>$p)if(!sf_media_has_link('store',(string)$id,['product_primary','product_gallery']))$missingStore[]=['id'=>(string)$id,'title'=>(string)($p['label']??$id)];if(function_exists('sf_commerce_products'))foreach(sf_commerce_products(false) as $p)if(($p['status']??'')!=='archived'&&!sf_media_has_link('store',(string)$p['id'],['product_primary','product_gallery']))$missingStore[]=['id'=>(string)$p['id'],'title'=>(string)$p['title']];
    $siteMissing=[];foreach(['logo','hero','social_share','app_icon'] as $role)if(!sf_media_has_link('site','public',[$role]))$siteMissing[]=$role;
    $publicPrivate=[];$refs=[['release',$rels,'artwork','cover'],['show',$shows,'poster',null]];foreach($refs as [$type,$rows,$field,$sub])foreach((array)$rows as $x){$id=(string)($x['id']??'');$url=$sub!==null?(string)($x[$field][$sub]??''):(string)($x[$field]??'');if($id!==''&&str_contains($url,'api/media.php?id=')){parse_str((string)parse_url($url,PHP_URL_QUERY),$qq);$uuid=(string)($qq['id']??'');$a=$uuid!==''?sf_media_asset($uuid):null;if($a){$q=$pdo->prepare('SELECT MAX(public_visible) FROM media_links WHERE asset_id=? AND entity_type=? AND entity_id=?');$q->execute([(int)$a['id'],$type,$id]);if(!(int)$q->fetchColumn())$publicPrivate[]=['entity_type'=>$type,'entity_id'=>$id,'label'=>sf_media_entity_label($type,$id),'asset'=>$uuid];}}}
    return ['assets'=>$assets,'storage_bytes'=>$bytes,'unused_assets'=>$unused,'broken_assets'=>$broken,'broken'=>$brokenRows,'missing'=>['track_audio'=>$missingTrackAudio,'track_artwork'=>$missingTrackArt,'release_cover'=>$missingRelease,'show_poster'=>$missingShow,'campaign_hero'=>$missingCampaign,'store_media'=>$missingStore,'site_roles'=>$siteMissing],'public_private_mismatch'=>$publicPrivate];
}
function sf_media_backfill_universal(): array {
    sf_media_ensure_schema();$counts=['release'=>0,'show'=>0,'campaign'=>0,'skipped'=>0];
    $register=function(string $type,string $id,string $role,string $url,bool $public,bool $featured=false)use(&$counts){if($url===''||preg_match('#^(?:https?:)?//#i',$url)||str_starts_with($url,'api/'))return;try{$a=sf_media_register_local_copy(SF_ROOT.'/'.ltrim($url,'/'),basename($url),0);sf_media_attach((int)$a['id'],$type,$id,$role,['public_visible'=>$public,'featured'=>$featured]);$counts[$type]=($counts[$type]??0)+1;}catch(Throwable $e){$counts['skipped']++;}};
    $rp=SF_ROOT.'/data/releases.json';$rels=is_file($rp)?json_decode((string)file_get_contents($rp),true):[];foreach((array)$rels as $r){$id=(string)($r['id']??'');if($id==='')continue;$pub=(($r['state']??'')==='published'&&($r['public_visible']??true)!==false);foreach(['cover','back','label_a','label_b','social_square','social_story'] as $role)$register('release',$id,$role,(string)($r['artwork'][$role]??''),$pub,$role==='cover');foreach((array)($r['archive']['media']??[]) as $m)$register('release',$id,'archive',(string)($m['url']??''),$pub,false);}
    $sp=SF_ROOT.'/data/shows.json';$shows=is_file($sp)?json_decode((string)file_get_contents($sp),true):[];foreach((array)$shows as $s){$id=(string)($s['id']??'');if($id==='')continue;$pub=(($s['public_visible']??true)!==false);$register('show',$id,'poster',(string)($s['poster']??''),$pub,true);foreach((array)($s['media']??[]) as $m)$register('show',$id,'archive',(string)($m['url']??''),$pub,false);}
    try{$q=sf_db()->query('SELECT id,status,artwork FROM campaigns');foreach($q->fetchAll() as $x){$register('campaign',(string)$x['id'],'hero',(string)($x['artwork']??''),($x['status']??'')==='published',true);}}catch(Throwable $e){}
    return $counts;
}
