<?php
declare(strict_types=1);

function sf_playlists_ensure_schema(): void {
    static $done=false;if($done)return;$pdo=sf_db();$driver=(string)(sf_db_config()['driver']??'');
    if($driver==='sqlite'){
        $pdo->exec("CREATE TABLE IF NOT EXISTS user_playlists (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',visibility TEXT NOT NULL DEFAULT 'private',source_type TEXT NOT NULL DEFAULT 'user',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_user_playlists_user_updated ON user_playlists(user_id,updated_at)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_user_playlists_visibility_updated ON user_playlists(visibility,updated_at)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS user_playlist_tracks (id INTEGER PRIMARY KEY AUTOINCREMENT,playlist_id INTEGER NOT NULL,track_id TEXT NOT NULL,position INTEGER NOT NULL DEFAULT 0,added_at TEXT NOT NULL,FOREIGN KEY(playlist_id) REFERENCES user_playlists(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_playlist_tracks_order ON user_playlist_tracks(playlist_id,position,id)");
    }else{
        $pdo->exec("CREATE TABLE IF NOT EXISTS user_playlists (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,name VARCHAR(120) NOT NULL,description TEXT NOT NULL,visibility VARCHAR(16) NOT NULL DEFAULT 'private',source_type VARCHAR(32) NOT NULL DEFAULT 'user',created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,INDEX idx_user_playlists_user_updated(user_id,updated_at),INDEX idx_user_playlists_visibility_updated(visibility,updated_at),CONSTRAINT fk_user_playlists_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS user_playlist_tracks (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,playlist_id BIGINT UNSIGNED NOT NULL,track_id VARCHAR(180) NOT NULL,position INT NOT NULL DEFAULT 0,added_at VARCHAR(40) NOT NULL,INDEX idx_playlist_tracks_order(playlist_id,position,id),CONSTRAINT fk_playlist_tracks_playlist FOREIGN KEY(playlist_id) REFERENCES user_playlists(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    }
    $done=true;
}
function sf_playlist_clean_visibility(string $visibility): string {return $visibility==='public'?'public':'private';}
function sf_playlist_clean_source(string $source): string {return in_array($source,['user','agent','agent_session'],true)?$source:'user';}
function sf_playlist_track_payload(string $trackId): ?array {
    $t=sf_track_map()[$trackId]??null;if(!$t)return null;
    return ['id'=>$trackId,'title'=>(string)($t['title']??$trackId),'release'=>(string)($t['release']??''),'artwork'=>(string)($t['artwork']??''),'duration'=>(int)($t['duration']??0),'audio'=>(string)($t['audio']??'')];
}
function sf_playlist_row(int $playlistId): ?array {sf_playlists_ensure_schema();$q=sf_db()->prepare('SELECT * FROM user_playlists WHERE id=? LIMIT 1');$q->execute([$playlistId]);$r=$q->fetch();return $r?:null;}
function sf_playlist_tracks(int $playlistId): array {
    sf_playlists_ensure_schema();$q=sf_db()->prepare('SELECT id,track_id,position,added_at FROM user_playlist_tracks WHERE playlist_id=? ORDER BY position ASC,id ASC');$q->execute([$playlistId]);$out=[];
    foreach($q->fetchAll() as $r){$t=sf_playlist_track_payload((string)$r['track_id']);if(!$t)continue;$out[]=['item_id'=>(int)$r['id'],'position'=>(int)$r['position'],'added_at'=>$r['added_at']]+$t;}
    return $out;
}
function sf_playlist_public_payload(array $r,bool $includeOwner=false): array {
    $payload=['id'=>(int)$r['id'],'name'=>(string)$r['name'],'description'=>(string)$r['description'],'visibility'=>(string)$r['visibility'],'source_type'=>(string)$r['source_type'],'created_at'=>(string)$r['created_at'],'updated_at'=>(string)$r['updated_at'],'tracks'=>sf_playlist_tracks((int)$r['id'])];
    $payload['track_count']=count($payload['tracks']);$payload['duration_seconds']=array_sum(array_map(fn($x)=>(int)$x['duration'],$payload['tracks']));if($includeOwner)$payload['user_id']=(int)$r['user_id'];return $payload;
}
function sf_playlist_get_owned(int $userId,int $playlistId): array {$r=sf_playlist_row($playlistId);if(!$r||(int)$r['user_id']!==$userId)throw new RuntimeException('Playlist not found.');return sf_playlist_public_payload($r,true);}
function sf_playlist_get_public(int $playlistId): ?array {$r=sf_playlist_row($playlistId);if(!$r||($r['visibility']??'private')!=='public')return null;return sf_playlist_public_payload($r,false);}
function sf_playlist_list(int $userId): array {
    sf_playlists_ensure_schema();$q=sf_db()->prepare('SELECT * FROM user_playlists WHERE user_id=? ORDER BY updated_at DESC,id DESC');$q->execute([$userId]);$out=[];foreach($q->fetchAll() as $r)$out[]=sf_playlist_public_payload($r,true);return $out;
}
function sf_playlist_validate_track_ids(array $trackIds,int $limit=200): array {$trackIds=array_slice($trackIds,0,$limit);$out=[];$map=sf_track_map();foreach($trackIds as $id){$id=sf_clean_text($id,180);if($id===''||!isset($map[$id]))throw new InvalidArgumentException('Playlist contains an unknown track.');$out[]=$id;}return $out;}
function sf_playlist_resequence(int $playlistId): void {$rows=sf_db()->prepare('SELECT id FROM user_playlist_tracks WHERE playlist_id=? ORDER BY position ASC,id ASC');$rows->execute([$playlistId]);$u=sf_db()->prepare('UPDATE user_playlist_tracks SET position=? WHERE id=? AND playlist_id=?');$i=0;foreach($rows->fetchAll() as $r){$u->execute([$i++,(int)$r['id'],$playlistId]);}}
function sf_playlist_create(int $userId,string $name,string $description='',string $visibility='private',string $source='user',array $trackIds=[]): array {
    sf_playlists_ensure_schema();$name=sf_clean_text($name,120);if($name==='')throw new InvalidArgumentException('Playlist name is required.');$description=sf_clean_text($description,1000);$visibility=sf_playlist_clean_visibility($visibility);$source=sf_playlist_clean_source($source);$trackIds=sf_playlist_validate_track_ids($trackIds);$now=gmdate('c');$pdo=sf_db();
    $pdo->beginTransaction();try{$q=$pdo->prepare('INSERT INTO user_playlists(user_id,name,description,visibility,source_type,created_at,updated_at) VALUES(?,?,?,?,?,?,?)');$q->execute([$userId,$name,$description,$visibility,$source,$now,$now]);$id=(int)$pdo->lastInsertId();$ins=$pdo->prepare('INSERT INTO user_playlist_tracks(playlist_id,track_id,position,added_at) VALUES(?,?,?,?)');foreach($trackIds as $i=>$trackId)$ins->execute([$id,$trackId,$i,$now]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    return sf_playlist_get_owned($userId,$id);
}
function sf_playlist_update(int $userId,int $playlistId,string $name,string $description,string $visibility): array {$p=sf_playlist_get_owned($userId,$playlistId);$name=sf_clean_text($name,120);if($name==='')throw new InvalidArgumentException('Playlist name is required.');$q=sf_db()->prepare('UPDATE user_playlists SET name=?,description=?,visibility=?,updated_at=? WHERE id=? AND user_id=?');$q->execute([$name,sf_clean_text($description,1000),sf_playlist_clean_visibility($visibility),gmdate('c'),$playlistId,$userId]);return sf_playlist_get_owned($userId,$playlistId);}
function sf_playlist_delete(int $userId,int $playlistId): void {sf_playlist_get_owned($userId,$playlistId);sf_db()->prepare('DELETE FROM user_playlists WHERE id=? AND user_id=?')->execute([$playlistId,$userId]);}
function sf_playlist_add_track(int $userId,int $playlistId,string $trackId): array {$p=sf_playlist_get_owned($userId,$playlistId);$track=sf_playlist_track_payload($trackId);if(!$track)throw new InvalidArgumentException('Unknown track.');$pos=count($p['tracks']);$now=gmdate('c');sf_db()->prepare('INSERT INTO user_playlist_tracks(playlist_id,track_id,position,added_at) VALUES(?,?,?,?)')->execute([$playlistId,$trackId,$pos,$now]);sf_db()->prepare('UPDATE user_playlists SET updated_at=? WHERE id=? AND user_id=?')->execute([$now,$playlistId,$userId]);return sf_playlist_get_owned($userId,$playlistId);}
function sf_playlist_remove_item(int $userId,int $playlistId,int $itemId): array {sf_playlist_get_owned($userId,$playlistId);$q=sf_db()->prepare('DELETE FROM user_playlist_tracks WHERE id=? AND playlist_id=?');$q->execute([$itemId,$playlistId]);if(!$q->rowCount())throw new RuntimeException('Playlist track was not found.');sf_playlist_resequence($playlistId);sf_db()->prepare('UPDATE user_playlists SET updated_at=? WHERE id=? AND user_id=?')->execute([gmdate('c'),$playlistId,$userId]);return sf_playlist_get_owned($userId,$playlistId);}
function sf_playlist_reorder(int $userId,int $playlistId,array $itemIds): array {$p=sf_playlist_get_owned($userId,$playlistId);$existing=array_map(fn($x)=>(int)$x['item_id'],$p['tracks']);$requested=array_map('intval',$itemIds);if(count($existing)!==count($requested)||array_diff($existing,$requested)||array_diff($requested,$existing))throw new InvalidArgumentException('Playlist order does not match the current playlist.');$pdo=sf_db();$pdo->beginTransaction();try{$q=$pdo->prepare('UPDATE user_playlist_tracks SET position=? WHERE id=? AND playlist_id=?');foreach($requested as $i=>$itemId)$q->execute([$i,$itemId,$playlistId]);$pdo->prepare('UPDATE user_playlists SET updated_at=? WHERE id=? AND user_id=?')->execute([gmdate('c'),$playlistId,$userId]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}return sf_playlist_get_owned($userId,$playlistId);}
function sf_playlist_recent_agent_track_ids(int $userId,int $limit=20,int $minutes=180): array {sf_ops_ensure_schema();$limit=max(1,min(50,$limit));$since=gmdate('c',time()-max(5,min(1440,$minutes))*60);$q=sf_db()->prepare("SELECT track_id,MAX(id) AS last_id FROM listening_events WHERE user_id=? AND source='agent' AND created_at>=? AND event_type IN ('start','resume','complete') GROUP BY track_id ORDER BY last_id ASC LIMIT ".$limit);$q->execute([$userId,$since]);return array_values(array_filter(array_map(fn($r)=>(string)$r['track_id'],$q->fetchAll()),fn($id)=>isset(sf_track_map()[$id])));}
function sf_playlist_create_from_agent_session(int $userId,string $name='Agent Listening Session'): array {$ids=sf_playlist_recent_agent_track_ids($userId);if(!$ids)throw new RuntimeException('No recent agent-curated listening session is available to save yet.');return sf_playlist_create($userId,$name,'Saved from your recent Stonefellow agent listening session.','private','agent_session',$ids);}
function sf_agent_playlist_track_ids(string $message,?string $activeId=null,int $limit=7): array {$rows=[];foreach(sf_catalog() as $t){$score=sf_agent_track_score($t,$message);if($activeId&&($t['id']??'')===$activeId)$score+=2;$rows[]=['id'=>(string)($t['id']??''),'score'=>$score,'energy'=>(int)($t['energy']??3)];}usort($rows,fn($a,$b)=>$b['score']<=>$a['score']?:$a['energy']<=>$b['energy']);return array_values(array_filter(array_map(fn($x)=>$x['id'],array_slice($rows,0,max(1,min(20,$limit))))));}
