<?php
declare(strict_types=1);

function sf_press_json(array $v): string {return json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?:'{}';}
function sf_press_decode(mixed $v,array $fallback=[]): array {$d=is_array($v)?$v:json_decode((string)$v,true);return is_array($d)?$d:$fallback;}
function sf_press_slug(string $v,string $fallback='press-kit'): string {$v=strtolower(trim($v));$v=preg_replace('/[^a-z0-9]+/','-',$v)??'';$v=trim(substr($v,0,140),'-');return $v!==''?$v:$fallback;}

function sf_press_ensure_schema(): void {
    static $done=false;if($done)return;$pdo=sf_db();$driver=(string)(sf_db_config()['driver']??'');
    if($driver==='sqlite'){
        $pdo->exec("CREATE TABLE IF NOT EXISTS press_kits (id INTEGER PRIMARY KEY AUTOINCREMENT,slug TEXT NOT NULL UNIQUE,title TEXT NOT NULL,release_id TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'draft',headline TEXT NOT NULL DEFAULT '',summary TEXT NOT NULL DEFAULT '',bio TEXT NOT NULL DEFAULT '',contact_name TEXT NOT NULL DEFAULT '',contact_email TEXT NOT NULL DEFAULT '',website_url TEXT NOT NULL DEFAULT '',share_token_hash TEXT NULL UNIQUE,share_token_hint TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',created_by INTEGER NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_press_kits_status ON press_kits(status,updated_at)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS press_contacts (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,outlet TEXT NOT NULL DEFAULT '',email TEXT NOT NULL UNIQUE,role TEXT NOT NULL DEFAULT '',location TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'active',tags_json TEXT NOT NULL DEFAULT '[]',notes TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_press_contacts_status ON press_contacts(status,outlet,name)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS press_outreach (id INTEGER PRIMARY KEY AUTOINCREMENT,kit_id INTEGER NOT NULL,contact_id INTEGER NOT NULL,subject TEXT NOT NULL,body_text TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',delivery_id INTEGER NULL,error_text TEXT NOT NULL DEFAULT '',created_by INTEGER NULL,created_at TEXT NOT NULL,sent_at TEXT NULL,FOREIGN KEY(kit_id) REFERENCES press_kits(id) ON DELETE CASCADE,FOREIGN KEY(contact_id) REFERENCES press_contacts(id) ON DELETE RESTRICT,FOREIGN KEY(delivery_id) REFERENCES transactional_email_outbox(id) ON DELETE SET NULL,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_press_outreach_kit ON press_outreach(kit_id,created_at)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS press_coverage (id INTEGER PRIMARY KEY AUTOINCREMENT,kit_id INTEGER NULL,contact_id INTEGER NULL,outlet TEXT NOT NULL,title TEXT NOT NULL,url TEXT NOT NULL DEFAULT '',published_at TEXT NULL,coverage_type TEXT NOT NULL DEFAULT 'article',notes TEXT NOT NULL DEFAULT '',created_by INTEGER NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(kit_id) REFERENCES press_kits(id) ON DELETE SET NULL,FOREIGN KEY(contact_id) REFERENCES press_contacts(id) ON DELETE SET NULL,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_press_coverage_date ON press_coverage(published_at,created_at)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS press_events (id INTEGER PRIMARY KEY AUTOINCREMENT,kit_id INTEGER NOT NULL,event_type TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,FOREIGN KEY(kit_id) REFERENCES press_kits(id) ON DELETE CASCADE)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_press_events_kit ON press_events(kit_id,event_type,created_at)");
    }else{
        $pdo->exec("CREATE TABLE IF NOT EXISTS press_kits (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(160) NOT NULL UNIQUE,title VARCHAR(220) NOT NULL,release_id VARCHAR(160) NOT NULL DEFAULT '',status VARCHAR(32) NOT NULL DEFAULT 'draft',headline VARCHAR(500) NOT NULL DEFAULT '',summary TEXT NOT NULL,bio LONGTEXT NOT NULL,contact_name VARCHAR(180) NOT NULL DEFAULT '',contact_email VARCHAR(190) NOT NULL DEFAULT '',website_url VARCHAR(700) NOT NULL DEFAULT '',share_token_hash CHAR(64) NULL UNIQUE,share_token_hint VARCHAR(24) NOT NULL DEFAULT '',notes LONGTEXT NOT NULL,created_by BIGINT UNSIGNED NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,INDEX idx_press_kits_status(status,updated_at),CONSTRAINT fk_press_kit_admin FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS press_contacts (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,name VARCHAR(180) NOT NULL,outlet VARCHAR(220) NOT NULL DEFAULT '',email VARCHAR(190) NOT NULL UNIQUE,role VARCHAR(160) NOT NULL DEFAULT '',location VARCHAR(180) NOT NULL DEFAULT '',status VARCHAR(32) NOT NULL DEFAULT 'active',tags_json LONGTEXT NOT NULL,notes LONGTEXT NOT NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,INDEX idx_press_contacts_status(status,outlet,name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS press_outreach (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,kit_id BIGINT UNSIGNED NOT NULL,contact_id BIGINT UNSIGNED NOT NULL,subject VARCHAR(255) NOT NULL,body_text LONGTEXT NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'draft',delivery_id BIGINT UNSIGNED NULL,error_text TEXT NOT NULL,created_by BIGINT UNSIGNED NULL,created_at VARCHAR(40) NOT NULL,sent_at VARCHAR(40) NULL,INDEX idx_press_outreach_kit(kit_id,created_at),CONSTRAINT fk_press_outreach_kit FOREIGN KEY(kit_id) REFERENCES press_kits(id) ON DELETE CASCADE,CONSTRAINT fk_press_outreach_contact FOREIGN KEY(contact_id) REFERENCES press_contacts(id) ON DELETE RESTRICT,CONSTRAINT fk_press_outreach_delivery FOREIGN KEY(delivery_id) REFERENCES transactional_email_outbox(id) ON DELETE SET NULL,CONSTRAINT fk_press_outreach_admin FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS press_coverage (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,kit_id BIGINT UNSIGNED NULL,contact_id BIGINT UNSIGNED NULL,outlet VARCHAR(220) NOT NULL,title VARCHAR(500) NOT NULL,url VARCHAR(900) NOT NULL DEFAULT '',published_at VARCHAR(40) NULL,coverage_type VARCHAR(40) NOT NULL DEFAULT 'article',notes LONGTEXT NOT NULL,created_by BIGINT UNSIGNED NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,INDEX idx_press_coverage_date(published_at,created_at),CONSTRAINT fk_press_coverage_kit FOREIGN KEY(kit_id) REFERENCES press_kits(id) ON DELETE SET NULL,CONSTRAINT fk_press_coverage_contact FOREIGN KEY(contact_id) REFERENCES press_contacts(id) ON DELETE SET NULL,CONSTRAINT fk_press_coverage_admin FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS press_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,kit_id BIGINT UNSIGNED NOT NULL,event_type VARCHAR(40) NOT NULL,detail_json LONGTEXT NOT NULL,created_at VARCHAR(40) NOT NULL,INDEX idx_press_events_kit(kit_id,event_type,created_at),CONSTRAINT fk_press_event_kit FOREIGN KEY(kit_id) REFERENCES press_kits(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    }
    $done=true;
}

function sf_press_kit(int|string $id): ?array {
    sf_press_ensure_schema();$col=is_int($id)||ctype_digit((string)$id)?'id':'slug';$q=sf_db()->prepare("SELECT * FROM press_kits WHERE $col=? LIMIT 1");$q->execute([$id]);$k=$q->fetch();if(!$k)return null;$k['media']=function_exists('sf_media_links')?sf_media_links('press_kit',(string)$k['id']):[];$k['public_media']=function_exists('sf_media_public_links')?sf_media_public_links('press_kit',(string)$k['id']):[];return $k;
}
function sf_press_kits(): array {sf_press_ensure_schema();$rows=sf_db()->query("SELECT k.*,(SELECT COUNT(*) FROM press_outreach o WHERE o.kit_id=k.id) outreach_count,(SELECT COUNT(*) FROM press_coverage c WHERE c.kit_id=k.id) coverage_count,(SELECT COUNT(*) FROM press_events e WHERE e.kit_id=k.id AND e.event_type='view') view_count FROM press_kits k ORDER BY k.id DESC")->fetchAll();return $rows;}
function sf_press_save_kit(array $raw,int $adminId): array {
    sf_press_ensure_schema();$id=max(0,(int)($raw['id']??0));$title=sf_clean_text($raw['title']??'',220);if($title==='')throw new InvalidArgumentException('Press kit title is required.');$slug=sf_press_slug((string)($raw['slug']??$title));$status=(string)($raw['status']??'draft');if(!in_array($status,['draft','published','private','archived'],true))$status='draft';$email=sf_clean_text($raw['contact_email']??'',190);if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))throw new InvalidArgumentException('Press contact email is invalid.');$now=gmdate('c');$vals=[$slug,$title,sf_clean_text($raw['release_id']??'',160),$status,sf_clean_text($raw['headline']??'',500),sf_clean_text($raw['summary']??'',6000),sf_clean_text($raw['bio']??'',20000),sf_clean_text($raw['contact_name']??'',180),$email,sf_clean_text($raw['website_url']??'',700),sf_clean_text($raw['notes']??'',12000),$now];
    if($id){$q=sf_db()->prepare('UPDATE press_kits SET slug=?,title=?,release_id=?,status=?,headline=?,summary=?,bio=?,contact_name=?,contact_email=?,website_url=?,notes=?,updated_at=? WHERE id=?');$q->execute([...$vals,$id]);}
    else{$q=sf_db()->prepare("INSERT INTO press_kits(slug,title,release_id,status,headline,summary,bio,contact_name,contact_email,website_url,share_token_hash,share_token_hint,notes,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,NULL,'',?,?,?,?)");$q->execute([...array_slice($vals,0,10),$vals[10],$adminId?:null,$now,$now]);$id=(int)sf_db()->lastInsertId();}
    $k=sf_press_kit($id);if(!$k)throw new RuntimeException('Press kit could not be saved.');return $k;
}
function sf_press_rotate_token(int $kitId): array {
    $k=sf_press_kit($kitId);if(!$k)throw new InvalidArgumentException('Press kit not found.');$raw=bin2hex(random_bytes(24));$hash=hash('sha256',$raw);$hint=substr($raw,0,6).'…'.substr($raw,-4);sf_db()->prepare('UPDATE press_kits SET share_token_hash=?,share_token_hint=?,updated_at=? WHERE id=?')->execute([$hash,$hint,gmdate('c'),$kitId]);$k=sf_press_kit($kitId)?:$k;return ['kit'=>$k,'token'=>$raw,'url'=>sf_press_share_url($k,$raw)];
}
function sf_press_share_url(array $kit,string $token=''): string {$base=rtrim(sf_public_base_url(),'/');$url=($base!==''?$base:'').'/press/'.rawurlencode((string)$kit['slug']);if($token!=='')$url.='?token='.rawurlencode($token);return $url;}
function sf_press_access_allowed(array $kit,string $token=''): bool {
    $status=(string)($kit['status']??'draft');if($status==='published')return true;if($status!=='private')return false;$hash=(string)($kit['share_token_hash']??'');return $hash!==''&&$token!==''&&hash_equals($hash,hash('sha256',$token));
}
function sf_press_release(string $releaseId): ?array {$path=SF_ROOT.'/data/releases.json';$rows=is_file($path)?json_decode((string)file_get_contents($path),true):[];foreach((array)$rows as $r)if((string)($r['id']??'')===$releaseId)return $r;return null;}
function sf_press_public_payload(array $kit): array {
    $release=$kit['release_id']!==''?sf_press_release((string)$kit['release_id']):null;$tracks=[];$map=[];foreach(sf_catalog() as $t)if(!empty($t['id']))$map[(string)$t['id']]=$t;
    foreach((array)($release['track_ids']??[]) as $tid){$t=$map[(string)$tid]??null;if(!$t)continue;$tracks[]=['id'=>(string)$t['id'],'title'=>(string)($t['title']??$tid),'audio'=>(string)($t['audio']??''),'artwork'=>(string)($t['artwork']??''),'duration'=>(int)($t['duration']??0),'year'=>(int)($t['year']??0),'story'=>(string)($t['story']??'')];}
    $site=sf_site_settings();$artistMedia=['logo'=>(string)($site['media_logo']??''),'hero'=>(string)($site['media_hero']??''),'social_share'=>(string)($site['media_social_share']??''),'app_icon'=>(string)($site['media_app_icon']??''),'artist_photo'=>(string)($site['media_artist_photo']??'')];return ['id'=>(int)$kit['id'],'slug'=>(string)$kit['slug'],'title'=>(string)$kit['title'],'headline'=>(string)$kit['headline'],'summary'=>(string)$kit['summary'],'bio'=>(string)$kit['bio'],'contact_name'=>(string)$kit['contact_name'],'contact_email'=>(string)$kit['contact_email'],'website_url'=>(string)$kit['website_url'],'release'=>$release?['id'=>(string)$release['id'],'title'=>(string)($release['title']??''),'type'=>(string)($release['type']??''),'release_date'=>(string)($release['release_date']??''),'genre'=>(string)($release['genre']??''),'description'=>(string)($release['description']??''),'liner_notes'=>(string)($release['liner_notes']??''),'credits'=>(array)($release['credits']??[]),'artwork'=>(array)($release['artwork']??[])]:null,'tracks'=>$tracks,'media'=>function_exists('sf_media_public_links')?sf_media_public_links('press_kit',(string)$kit['id']):[],'artist_media'=>$artistMedia,'generated_at'=>gmdate('c')];
}
function sf_press_public_kit(string $slug,string $token=''): ?array {$k=sf_press_kit($slug);if(!$k||!sf_press_access_allowed($k,$token))return null;return sf_press_public_payload($k);}

function sf_press_contact(int $id): ?array {$q=sf_db()->prepare('SELECT * FROM press_contacts WHERE id=?');$q->execute([$id]);$r=$q->fetch();if(!$r)return null;$r['tags']=sf_press_decode($r['tags_json']??'',[]);return $r;}
function sf_press_contacts(): array {sf_press_ensure_schema();$rows=sf_db()->query('SELECT * FROM press_contacts ORDER BY CASE status WHEN \'active\' THEN 0 WHEN \'do_not_contact\' THEN 1 ELSE 2 END,outlet,name')->fetchAll();foreach($rows as &$r)$r['tags']=sf_press_decode($r['tags_json']??'',[]);unset($r);return $rows;}
function sf_press_save_contact(array $raw): array {
    sf_press_ensure_schema();$id=max(0,(int)($raw['id']??0));$name=sf_clean_text($raw['name']??'',180);$email=strtolower(trim((string)($raw['email']??'')));if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL))throw new InvalidArgumentException('Press contact name and valid email are required.');$status=(string)($raw['status']??'active');if(!in_array($status,['active','do_not_contact','archived'],true))$status='active';$tags=array_values(array_unique(array_filter(array_map(fn($x)=>sf_clean_text($x,60),(array)($raw['tags']??[])))));$now=gmdate('c');$vals=[$name,sf_clean_text($raw['outlet']??'',220),$email,sf_clean_text($raw['role']??'',160),sf_clean_text($raw['location']??'',180),$status,sf_press_json($tags),sf_clean_text($raw['notes']??'',8000),$now];
    if($id){$q=sf_db()->prepare('UPDATE press_contacts SET name=?,outlet=?,email=?,role=?,location=?,status=?,tags_json=?,notes=?,updated_at=? WHERE id=?');$q->execute([...$vals,$id]);}
    else{$q=sf_db()->prepare('INSERT INTO press_contacts(name,outlet,email,role,location,status,tags_json,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)');$q->execute([...array_slice($vals,0,8),$now,$now]);$id=(int)sf_db()->lastInsertId();}
    return sf_press_contact($id)?:[];
}
function sf_press_outreach(int $kitId=0): array {$where=$kitId>0?'WHERE o.kit_id=?':'';$q=sf_db()->prepare("SELECT o.*,c.name contact_name,c.outlet,c.email,k.title kit_title FROM press_outreach o JOIN press_contacts c ON c.id=o.contact_id JOIN press_kits k ON k.id=o.kit_id $where ORDER BY o.id DESC LIMIT 500");$q->execute($kitId>0?[$kitId]:[]);return $q->fetchAll();}
function sf_press_send_outreach(int $kitId,int $contactId,string $subject,string $body,string $token,int $adminId): array {
    sf_press_ensure_schema();$kit=sf_press_kit($kitId);$contact=sf_press_contact($contactId);if(!$kit||!$contact)throw new InvalidArgumentException('Press kit or contact was not found.');if(($contact['status']??'')!=='active')throw new RuntimeException('This press contact is marked '.$contact['status'].' and cannot receive outreach.');$subject=sf_clean_text($subject,255);$body=sf_clean_text($body,30000);if($subject===''||$body==='')throw new InvalidArgumentException('Subject and message are required.');if(($kit['status']??'')==='private'&&!sf_press_access_allowed($kit,$token))throw new RuntimeException('A valid current private-kit token is required before sending this outreach.');if(($kit['status']??'')==='draft'||($kit['status']??'')==='archived')throw new RuntimeException('Publish the EPK or set it private before sending outreach.');
    $url=sf_press_share_url($kit,($kit['status']??'')==='private'?$token:'');$mail=$body."\n\nPress kit: ".$url;$delivery=sf_transactional_email(0,(string)$contact['email'],$subject,$mail,'press_outreach');$status=(string)($delivery['status']??'failed');$now=gmdate('c');$q=sf_db()->prepare('INSERT INTO press_outreach(kit_id,contact_id,subject,body_text,status,delivery_id,error_text,created_by,created_at,sent_at) VALUES(?,?,?,?,?,?,?,?,?,?)');$q->execute([$kitId,$contactId,$subject,$body,$status,!empty($delivery['id'])?(int)$delivery['id']:null,sf_clean_text($delivery['error']??'',1000),$adminId?:null,$now,$status==='sent'?$now:null]);$id=(int)sf_db()->lastInsertId();$q=sf_db()->prepare('SELECT * FROM press_outreach WHERE id=?');$q->execute([$id]);return ['outreach'=>$q->fetch()?:[],'delivery'=>$delivery,'url'=>$url];
}
function sf_press_coverage(): array {$rows=sf_db()->query("SELECT c.*,k.title kit_title,p.name contact_name FROM press_coverage c LEFT JOIN press_kits k ON k.id=c.kit_id LEFT JOIN press_contacts p ON p.id=c.contact_id ORDER BY COALESCE(c.published_at,c.created_at) DESC,c.id DESC LIMIT 500")->fetchAll();return $rows;}
function sf_press_save_coverage(array $raw,int $adminId): array {
    sf_press_ensure_schema();$id=max(0,(int)($raw['id']??0));$outlet=sf_clean_text($raw['outlet']??'',220);$title=sf_clean_text($raw['title']??'',500);if($outlet===''||$title==='')throw new InvalidArgumentException('Coverage outlet and title are required.');$type=(string)($raw['coverage_type']??'article');if(!in_array($type,['article','review','interview','radio','podcast','video','playlist','other'],true))$type='other';$now=gmdate('c');$vals=[($raw['kit_id']??'')!==''?(int)$raw['kit_id']:null,($raw['contact_id']??'')!==''?(int)$raw['contact_id']:null,$outlet,$title,sf_clean_text($raw['url']??'',900),($raw['published_at']??'')?:null,$type,sf_clean_text($raw['notes']??'',10000),$now];
    if($id){$q=sf_db()->prepare('UPDATE press_coverage SET kit_id=?,contact_id=?,outlet=?,title=?,url=?,published_at=?,coverage_type=?,notes=?,updated_at=? WHERE id=?');$q->execute([...$vals,$id]);}
    else{$q=sf_db()->prepare('INSERT INTO press_coverage(kit_id,contact_id,outlet,title,url,published_at,coverage_type,notes,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$q->execute([...array_slice($vals,0,8),$adminId?:null,$now,$now]);$id=(int)sf_db()->lastInsertId();}
    $q=sf_db()->prepare('SELECT * FROM press_coverage WHERE id=?');$q->execute([$id]);return $q->fetch()?:[];
}
function sf_press_event(int $kitId,string $eventType,array $detail=[]): void {$allowed=['view','media_click','contact_click','release_play','download_click'];if(!in_array($eventType,$allowed,true))return;$safe=[];foreach(array_slice($detail,0,12,true) as $k=>$v)$safe[sf_clean_text($k,60)]=is_scalar($v)?sf_clean_text($v,500):'';sf_db()->prepare('INSERT INTO press_events(kit_id,event_type,detail_json,created_at) VALUES(?,?,?,?)')->execute([$kitId,$eventType,sf_press_json($safe),gmdate('c')]);}
function sf_press_events(int $kitId=0,int $limit=200): array {$where=$kitId>0?'WHERE kit_id=?':'';$q=sf_db()->prepare("SELECT * FROM press_events $where ORDER BY id DESC LIMIT ".max(1,min(1000,$limit)));$q->execute($kitId>0?[$kitId]:[]);$rows=$q->fetchAll();foreach($rows as &$r)$r['detail']=sf_press_decode($r['detail_json']??'',[]);unset($r);return $rows;}
function sf_press_summary(): array {
    sf_press_ensure_schema();$pdo=sf_db();$kits=(int)$pdo->query('SELECT COUNT(*) FROM press_kits')->fetchColumn();$published=(int)$pdo->query("SELECT COUNT(*) FROM press_kits WHERE status='published'")->fetchColumn();$private=(int)$pdo->query("SELECT COUNT(*) FROM press_kits WHERE status='private'")->fetchColumn();$contacts=(int)$pdo->query("SELECT COUNT(*) FROM press_contacts WHERE status='active'")->fetchColumn();$sent=(int)$pdo->query("SELECT COUNT(*) FROM press_outreach WHERE status IN ('sent','queued')")->fetchColumn();$failed=(int)$pdo->query("SELECT COUNT(*) FROM press_outreach WHERE status='failed'")->fetchColumn();$coverage=(int)$pdo->query('SELECT COUNT(*) FROM press_coverage')->fetchColumn();$views=(int)$pdo->query("SELECT COUNT(*) FROM press_events WHERE event_type='view'")->fetchColumn();return ['kits'=>$kits,'published'=>$published,'private'=>$private,'contacts'=>$contacts,'outreach'=>$sent,'outreach_failed'=>$failed,'coverage'=>$coverage,'views'=>$views];
}
function sf_press_agent_brief(): string {$s=sf_press_summary();$lines=['PRESS + EPK','Kits '.$s['kits'].' | public '.$s['published'].' | private '.$s['private'].' | active contacts '.$s['contacts'].' | outreach '.$s['outreach'].' | failed '.$s['outreach_failed'].' | coverage '.$s['coverage'].' | EPK views '.$s['views']];foreach(array_slice(sf_press_kits(),0,8) as $k)$lines[]='- '.$k['title'].' | '.$k['status'].' | views '.$k['view_count'].' | outreach '.$k['outreach_count'].' | coverage '.$k['coverage_count'];return implode("\n",$lines);}
