<?php
declare(strict_types=1);

function sf_rights_json(array $v): string {return json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?:'{}';}
function sf_rights_decode(mixed $v,array $fallback=[]): array {$d=is_array($v)?$v:json_decode((string)$v,true);return is_array($d)?$d:$fallback;}
function sf_rights_bp(mixed $percent): int {$v=(float)$percent;return max(0,min(10000,(int)round($v*100)));}
function sf_rights_pct(int $bp): float {return round($bp/100,2);}
function sf_rights_valid_iswc(string $v): bool {$v=strtoupper(preg_replace('/[^A-Z0-9]/','',$v)??'');return $v===''||(bool)preg_match('/^T\d{10}$/',$v);}
function sf_rights_normalize_iswc(string $v): string {$v=strtoupper(preg_replace('/[^A-Z0-9]/','',$v)??'');return sf_rights_valid_iswc($v)?$v:'';}

function sf_rights_ensure_schema(): void {
    static $done=false;if($done)return;$pdo=sf_db();$driver=(string)(sf_db_config()['driver']??'');
    if($driver==='sqlite'){
        $pdo->exec("CREATE TABLE IF NOT EXISTS rights_parties (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,legal_name TEXT NOT NULL DEFAULT '',party_type TEXT NOT NULL DEFAULT 'writer',email TEXT NOT NULL DEFAULT '',pro_affiliation TEXT NOT NULL DEFAULT '',ipi_cae TEXT NOT NULL DEFAULT '',publisher_ipi TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',created_by INTEGER NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_rights_parties_name ON rights_parties(name,party_type)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS rights_works (id INTEGER PRIMARY KEY AUTOINCREMENT,track_id TEXT NOT NULL UNIQUE,title TEXT NOT NULL,iswc TEXT NOT NULL DEFAULT '',pro_work_id TEXT NOT NULL DEFAULT '',copyright_year INTEGER NOT NULL DEFAULT 0,composition_copyright TEXT NOT NULL DEFAULT '',master_copyright TEXT NOT NULL DEFAULT '',publisher_name TEXT NOT NULL DEFAULT '',territory TEXT NOT NULL DEFAULT 'worldwide',registration_status TEXT NOT NULL DEFAULT 'draft',notes TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS rights_splits (id INTEGER PRIMARY KEY AUTOINCREMENT,work_id INTEGER NOT NULL,party_id INTEGER NOT NULL,split_type TEXT NOT NULL,role TEXT NOT NULL DEFAULT '',percent_bp INTEGER NOT NULL DEFAULT 0,controlled INTEGER NOT NULL DEFAULT 1,notes TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(work_id,party_id,split_type,role),FOREIGN KEY(work_id) REFERENCES rights_works(id) ON DELETE CASCADE,FOREIGN KEY(party_id) REFERENCES rights_parties(id) ON DELETE RESTRICT)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_rights_splits_work ON rights_splits(work_id,split_type)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS rights_licenses (id INTEGER PRIMARY KEY AUTOINCREMENT,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,license_type TEXT NOT NULL,licensor_party_id INTEGER NULL,status TEXT NOT NULL DEFAULT 'pending',territory TEXT NOT NULL DEFAULT 'worldwide',starts_at TEXT NULL,ends_at TEXT NULL,reference TEXT NOT NULL DEFAULT '',terms TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',created_by INTEGER NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(licensor_party_id) REFERENCES rights_parties(id) ON DELETE SET NULL,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_rights_licenses_entity ON rights_licenses(entity_type,entity_id,status,ends_at)");
    }else{
        $pdo->exec("CREATE TABLE IF NOT EXISTS rights_parties (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,name VARCHAR(180) NOT NULL,legal_name VARCHAR(220) NOT NULL DEFAULT '',party_type VARCHAR(40) NOT NULL DEFAULT 'writer',email VARCHAR(190) NOT NULL DEFAULT '',pro_affiliation VARCHAR(80) NOT NULL DEFAULT '',ipi_cae VARCHAR(80) NOT NULL DEFAULT '',publisher_ipi VARCHAR(80) NOT NULL DEFAULT '',notes TEXT NOT NULL,created_by BIGINT UNSIGNED NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,INDEX idx_rights_parties_name(name,party_type),CONSTRAINT fk_rights_party_admin FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS rights_works (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,track_id VARCHAR(160) NOT NULL UNIQUE,title VARCHAR(255) NOT NULL,iswc VARCHAR(24) NOT NULL DEFAULT '',pro_work_id VARCHAR(120) NOT NULL DEFAULT '',copyright_year INT NOT NULL DEFAULT 0,composition_copyright VARCHAR(500) NOT NULL DEFAULT '',master_copyright VARCHAR(500) NOT NULL DEFAULT '',publisher_name VARCHAR(255) NOT NULL DEFAULT '',territory VARCHAR(120) NOT NULL DEFAULT 'worldwide',registration_status VARCHAR(32) NOT NULL DEFAULT 'draft',notes TEXT NOT NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS rights_splits (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,work_id BIGINT UNSIGNED NOT NULL,party_id BIGINT UNSIGNED NOT NULL,split_type VARCHAR(32) NOT NULL,role VARCHAR(100) NOT NULL DEFAULT '',percent_bp INT NOT NULL DEFAULT 0,controlled TINYINT(1) NOT NULL DEFAULT 1,notes TEXT NOT NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,UNIQUE KEY uq_rights_split(work_id,party_id,split_type,role),INDEX idx_rights_splits_work(work_id,split_type),CONSTRAINT fk_rights_split_work FOREIGN KEY(work_id) REFERENCES rights_works(id) ON DELETE CASCADE,CONSTRAINT fk_rights_split_party FOREIGN KEY(party_id) REFERENCES rights_parties(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS rights_licenses (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,entity_type VARCHAR(32) NOT NULL,entity_id VARCHAR(160) NOT NULL,license_type VARCHAR(48) NOT NULL,licensor_party_id BIGINT UNSIGNED NULL,status VARCHAR(32) NOT NULL DEFAULT 'pending',territory VARCHAR(120) NOT NULL DEFAULT 'worldwide',starts_at VARCHAR(40) NULL,ends_at VARCHAR(40) NULL,reference VARCHAR(255) NOT NULL DEFAULT '',terms TEXT NOT NULL,notes TEXT NOT NULL,created_by BIGINT UNSIGNED NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,INDEX idx_rights_licenses_entity(entity_type,entity_id,status,ends_at),CONSTRAINT fk_rights_license_party FOREIGN KEY(licensor_party_id) REFERENCES rights_parties(id) ON DELETE SET NULL,CONSTRAINT fk_rights_license_admin FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    }
    $done=true;
}

function sf_rights_track(string $trackId): ?array {foreach(sf_catalog() as $t)if((string)($t['id']??'')===$trackId)return $t;return null;}
function sf_rights_work(string $trackId): ?array {
    sf_rights_ensure_schema();$q=sf_db()->prepare('SELECT * FROM rights_works WHERE track_id=? LIMIT 1');$q->execute([$trackId]);$w=$q->fetch();if(!$w)return null;$q=sf_db()->prepare('SELECT s.*,p.name party_name,p.legal_name,p.party_type,p.pro_affiliation,p.ipi_cae,p.publisher_ipi FROM rights_splits s JOIN rights_parties p ON p.id=s.party_id WHERE s.work_id=? ORDER BY s.split_type,s.id');$q->execute([(int)$w['id']]);$w['splits']=$q->fetchAll();$q=sf_db()->prepare("SELECT l.*,p.name licensor_name FROM rights_licenses l LEFT JOIN rights_parties p ON p.id=l.licensor_party_id WHERE l.entity_type='track' AND l.entity_id=? ORDER BY l.id DESC");$q->execute([$trackId]);$w['licenses']=$q->fetchAll();$w['readiness']=sf_rights_readiness($w);return $w;
}
function sf_rights_party(int $id): ?array {$q=sf_db()->prepare('SELECT * FROM rights_parties WHERE id=?');$q->execute([$id]);return $q->fetch()?:null;}
function sf_rights_parties(): array {sf_rights_ensure_schema();return sf_db()->query('SELECT * FROM rights_parties ORDER BY name,id')->fetchAll();}

function sf_rights_readiness_eval(int $compositionBp,int $masterBp,array $licenses=[]): array {
    $blockers=[];$warnings=[];if($compositionBp!==10000)$blockers[]='Composition ownership totals '.sf_rights_pct($compositionBp).'%, not 100%.';if($masterBp!==10000)$blockers[]='Master ownership totals '.sf_rights_pct($masterBp).'%, not 100%.';
    $today=gmdate('Y-m-d');foreach($licenses as $l){$status=(string)($l['status']??'pending');$end=substr((string)($l['ends_at']??''),0,10);if(in_array($status,['pending','restricted'],true))$blockers[]='License '.($l['license_type']??'clearance').' is '.$status.'.';elseif($status==='cleared'&&$end!==''&&$end<$today)$blockers[]='License '.($l['license_type']??'clearance').' expired '.$end.'.';elseif($status==='cleared'&&$end!==''&&$end>=gmdate('Y-m-d',time())&&$end<=gmdate('Y-m-d',time()+60*86400))$warnings[]='License '.($l['license_type']??'clearance').' expires '.$end.'.';}
    return ['ready'=>!$blockers,'composition_bp'=>$compositionBp,'master_bp'=>$masterBp,'composition_percent'=>sf_rights_pct($compositionBp),'master_percent'=>sf_rights_pct($masterBp),'blockers'=>array_values(array_unique($blockers)),'warnings'=>array_values(array_unique($warnings))];
}
function sf_rights_readiness(array $work): array {
    $comp=0;$master=0;foreach((array)($work['splits']??[]) as $s){if(($s['split_type']??'')==='composition')$comp+=(int)$s['percent_bp'];if(($s['split_type']??'')==='master')$master+=(int)$s['percent_bp'];}
    $r=sf_rights_readiness_eval($comp,$master,(array)($work['licenses']??[]));$metaWarn=[];if(trim((string)($work['composition_copyright']??''))==='')$metaWarn[]='Composition copyright is blank.';if(trim((string)($work['master_copyright']??''))==='')$metaWarn[]='Master copyright is blank.';$r['warnings']=array_values(array_unique(array_merge($r['warnings'],$metaWarn)));return $r;
}

function sf_rights_backfill_catalog(): array {
    sf_rights_ensure_schema();$now=gmdate('c');$added=0;$updated=0;foreach(sf_catalog() as $t){$id=sf_clean_text($t['id']??'',160);if($id==='')continue;$m=(array)($t['metadata']??[]);$q=sf_db()->prepare('SELECT id FROM rights_works WHERE track_id=?');$q->execute([$id]);$wid=(int)($q->fetchColumn()?:0);$vals=[sf_clean_text($t['title']??$id,255),sf_rights_normalize_iswc((string)($m['iswc']??'')),sf_clean_text($m['pro_work_id']??'',120),max(0,(int)($t['year']??0)),sf_clean_text($m['composition_copyright']??'',500),sf_clean_text($m['master_copyright']??'',500),sf_clean_text($m['publisher']??'',255),'worldwide',$now];
      if($wid){$q=sf_db()->prepare("UPDATE rights_works SET title=?,iswc=CASE WHEN iswc='' THEN ? ELSE iswc END,pro_work_id=CASE WHEN pro_work_id='' THEN ? ELSE pro_work_id END,copyright_year=CASE WHEN copyright_year=0 THEN ? ELSE copyright_year END,composition_copyright=CASE WHEN composition_copyright='' THEN ? ELSE composition_copyright END,master_copyright=CASE WHEN master_copyright='' THEN ? ELSE master_copyright END,publisher_name=CASE WHEN publisher_name='' THEN ? ELSE publisher_name END,territory=CASE WHEN territory='' THEN ? ELSE territory END,updated_at=? WHERE id=?");$q->execute([...$vals,$wid]);$updated++;}
      else{$q=sf_db()->prepare("INSERT INTO rights_works(track_id,title,iswc,pro_work_id,copyright_year,composition_copyright,master_copyright,publisher_name,territory,registration_status,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'draft','',?,?)");$q->execute([$id,...array_slice($vals,0,8),$now,$now]);$added++;}
    }return ['added'=>$added,'updated'=>$updated];
}

function sf_rights_save_work(string $trackId,array $raw): array {
    sf_rights_ensure_schema();$track=sf_rights_track($trackId);if(!$track)throw new InvalidArgumentException('Catalog track not found.');$existing=sf_rights_work($trackId);$iswc=sf_rights_normalize_iswc((string)($raw['iswc']??''));if(trim((string)($raw['iswc']??''))!==''&&$iswc==='')throw new InvalidArgumentException('ISWC must be T followed by 10 digits.');$status=(string)($raw['registration_status']??'draft');if(!in_array($status,['draft','submitted','registered','not_applicable'],true))$status='draft';$now=gmdate('c');$vals=[sf_clean_text($raw['title']??($track['title']??$trackId),255),$iswc,sf_clean_text($raw['pro_work_id']??'',120),max(0,(int)($raw['copyright_year']??($track['year']??0))),sf_clean_text($raw['composition_copyright']??'',500),sf_clean_text($raw['master_copyright']??'',500),sf_clean_text($raw['publisher_name']??'',255),sf_clean_text($raw['territory']??'worldwide',120),$status,sf_clean_text($raw['notes']??'',10000),$now];
    if($existing){$q=sf_db()->prepare('UPDATE rights_works SET title=?,iswc=?,pro_work_id=?,copyright_year=?,composition_copyright=?,master_copyright=?,publisher_name=?,territory=?,registration_status=?,notes=?,updated_at=? WHERE track_id=?');$q->execute([...$vals,$trackId]);}
    else{$q=sf_db()->prepare('INSERT INTO rights_works(track_id,title,iswc,pro_work_id,copyright_year,composition_copyright,master_copyright,publisher_name,territory,registration_status,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');$q->execute([$trackId,...array_slice($vals,0,10),$now,$now]);}
    return sf_rights_work($trackId)?:[];
}
function sf_rights_save_party(array $raw,int $adminId): array {
    sf_rights_ensure_schema();$id=max(0,(int)($raw['id']??0));$name=sf_clean_text($raw['name']??'',180);if($name==='')throw new InvalidArgumentException('Party name is required.');$type=(string)($raw['party_type']??'writer');if(!in_array($type,['writer','composer','publisher','artist','label','master_owner','licensor','other'],true))$type='other';$now=gmdate('c');$vals=[$name,sf_clean_text($raw['legal_name']??'',220),$type,sf_clean_text($raw['email']??'',190),sf_clean_text($raw['pro_affiliation']??'',80),sf_clean_text($raw['ipi_cae']??'',80),sf_clean_text($raw['publisher_ipi']??'',80),sf_clean_text($raw['notes']??'',5000),$now];
    if($id){$q=sf_db()->prepare('UPDATE rights_parties SET name=?,legal_name=?,party_type=?,email=?,pro_affiliation=?,ipi_cae=?,publisher_ipi=?,notes=?,updated_at=? WHERE id=?');$q->execute([...$vals,$id]);}
    else{$q=sf_db()->prepare('INSERT INTO rights_parties(name,legal_name,party_type,email,pro_affiliation,ipi_cae,publisher_ipi,notes,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$q->execute([...array_slice($vals,0,8),$adminId?:null,$now,$now]);$id=(int)sf_db()->lastInsertId();}
    return sf_rights_party($id)?:[];
}
function sf_rights_save_split(string $trackId,array $raw): array {
    $work=sf_rights_work($trackId);if(!$work)throw new InvalidArgumentException('Rights work not found.');$id=max(0,(int)($raw['id']??0));$partyId=max(0,(int)($raw['party_id']??0));if(!$partyId||!sf_rights_party($partyId))throw new InvalidArgumentException('Choose a rights party.');$type=(string)($raw['split_type']??'composition');if(!in_array($type,['composition','master'],true))throw new InvalidArgumentException('Split type must be composition or master.');$bp=sf_rights_bp($raw['percent']??0);if($bp<=0)throw new InvalidArgumentException('Split percentage must be greater than zero.');$now=gmdate('c');$role=sf_clean_text($raw['role']??'',100);$notes=sf_clean_text($raw['notes']??'',4000);$controlled=!empty($raw['controlled'])?1:0;
    if($id){$q=sf_db()->prepare('UPDATE rights_splits SET party_id=?,split_type=?,role=?,percent_bp=?,controlled=?,notes=?,updated_at=? WHERE id=? AND work_id=?');$q->execute([$partyId,$type,$role,$bp,$controlled,$notes,$now,$id,(int)$work['id']]);}
    else{$q=sf_db()->prepare('INSERT INTO rights_splits(work_id,party_id,split_type,role,percent_bp,controlled,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)');$q->execute([(int)$work['id'],$partyId,$type,$role,$bp,$controlled,$notes,$now,$now]);}
    return sf_rights_work($trackId)?:[];
}
function sf_rights_delete_split(string $trackId,int $splitId): bool {$work=sf_rights_work($trackId);if(!$work)return false;$q=sf_db()->prepare('DELETE FROM rights_splits WHERE id=? AND work_id=?');$q->execute([$splitId,(int)$work['id']]);return $q->rowCount()>0;}
function sf_rights_save_license(array $raw,int $adminId): array {
    sf_rights_ensure_schema();$id=max(0,(int)($raw['id']??0));$etype=(string)($raw['entity_type']??'track');if(!in_array($etype,['track','release'],true))throw new InvalidArgumentException('License entity must be track or release.');$eid=sf_clean_text($raw['entity_id']??'',160);if($eid==='')throw new InvalidArgumentException('License entity is required.');$type=(string)($raw['license_type']??'other');if(!in_array($type,['sync','mechanical','master_use','sample','cover','remix','name_likeness','other'],true))$type='other';$status=(string)($raw['status']??'pending');if(!in_array($status,['pending','cleared','restricted','expired','not_required'],true))$status='pending';$now=gmdate('c');$vals=[$etype,$eid,$type,($raw['licensor_party_id']??'')!==''?(int)$raw['licensor_party_id']:null,$status,sf_clean_text($raw['territory']??'worldwide',120),($raw['starts_at']??'')?:null,($raw['ends_at']??'')?:null,sf_clean_text($raw['reference']??'',255),sf_clean_text($raw['terms']??'',10000),sf_clean_text($raw['notes']??'',10000),$now];
    if($id){$q=sf_db()->prepare('UPDATE rights_licenses SET entity_type=?,entity_id=?,license_type=?,licensor_party_id=?,status=?,territory=?,starts_at=?,ends_at=?,reference=?,terms=?,notes=?,updated_at=? WHERE id=?');$q->execute([...$vals,$id]);}
    else{$q=sf_db()->prepare('INSERT INTO rights_licenses(entity_type,entity_id,license_type,licensor_party_id,status,territory,starts_at,ends_at,reference,terms,notes,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$q->execute([...array_slice($vals,0,11),$adminId?:null,$now,$now]);$id=(int)sf_db()->lastInsertId();}
    $q=sf_db()->prepare('SELECT * FROM rights_licenses WHERE id=?');$q->execute([$id]);return $q->fetch()?:[];
}
function sf_rights_delete_license(int $id): bool {$q=sf_db()->prepare('DELETE FROM rights_licenses WHERE id=?');$q->execute([$id]);return $q->rowCount()>0;}

function sf_rights_release_readiness(string $releaseId): array {
    $path=SF_ROOT.'/data/releases.json';$rels=is_file($path)?json_decode((string)file_get_contents($path),true):[];$release=null;foreach((array)$rels as $r)if((string)($r['id']??'')===$releaseId){$release=$r;break;}if(!$release)return ['release_id'=>$releaseId,'title'=>$releaseId,'ready'=>false,'tracks'=>[],'blockers'=>['Release not found.']];
    $tracks=[];$blockers=[];foreach((array)($release['track_ids']??[]) as $tid){$w=sf_rights_work((string)$tid);$r=$w?$w['readiness']:['ready'=>false,'blockers'=>['Rights work not initialized.'],'warnings'=>[],'composition_percent'=>0,'master_percent'=>0];$tracks[]=['track_id'=>(string)$tid,'title'=>(string)(sf_rights_track((string)$tid)['title']??$tid),'readiness'=>$r];if(empty($r['ready']))foreach((array)$r['blockers'] as $b)$blockers[]=(string)(sf_rights_track((string)$tid)['title']??$tid).': '.$b;}
    $q=sf_db()->prepare("SELECT * FROM rights_licenses WHERE entity_type='release' AND entity_id=? ORDER BY id");$q->execute([$releaseId]);$licenses=$q->fetchAll();$lr=sf_rights_readiness_eval(10000,10000,$licenses);$blockers=array_merge($blockers,$lr['blockers']);return ['release_id'=>$releaseId,'title'=>(string)($release['title']??$releaseId),'state'=>(string)($release['state']??'draft'),'ready'=>!$blockers,'tracks'=>$tracks,'licenses'=>$licenses,'blockers'=>array_values(array_unique($blockers)),'warnings'=>$lr['warnings']];
}
function sf_rights_summary(): array {
    sf_rights_ensure_schema();$pdo=sf_db();$works=[];$ready=0;$blocked=0;$warnings=0;foreach($pdo->query('SELECT track_id FROM rights_works ORDER BY id')->fetchAll(PDO::FETCH_COLUMN) as $tid){$w=sf_rights_work((string)$tid);if(!$w)continue;$works[]=$w;if(!empty($w['readiness']['ready']))$ready++;else$blocked++;$warnings+=count((array)$w['readiness']['warnings']);}
    $parties=(int)$pdo->query('SELECT COUNT(*) FROM rights_parties')->fetchColumn();$pending=(int)$pdo->query("SELECT COUNT(*) FROM rights_licenses WHERE status IN ('pending','restricted')")->fetchColumn();$today=gmdate('Y-m-d');$soon=gmdate('Y-m-d',time()+60*86400);$q=$pdo->prepare("SELECT COUNT(*) FROM rights_licenses WHERE status='cleared' AND ends_at IS NOT NULL AND ends_at<>'' AND substr(ends_at,1,10) BETWEEN ? AND ?");$q->execute([$today,$soon]);$expiring=(int)$q->fetchColumn();$releases=[];$path=SF_ROOT.'/data/releases.json';$rs=is_file($path)?json_decode((string)file_get_contents($path),true):[];foreach((array)$rs as $r)if(!empty($r['id']))$releases[]=sf_rights_release_readiness((string)$r['id']);
    return ['works'=>count($works),'ready'=>$ready,'blocked'=>$blocked,'parties'=>$parties,'pending_licenses'=>$pending,'expiring_licenses'=>$expiring,'warnings'=>$warnings,'work_rows'=>$works,'release_rows'=>$releases];
}
function sf_rights_agent_brief(): string {
    $s=sf_rights_summary();$lines=['RIGHTS + LICENSING','Works: '.$s['works'].' | rights ready '.$s['ready'].' | blocked '.$s['blocked'].' | parties '.$s['parties'].' | pending/restricted licenses '.$s['pending_licenses'].' | expiring licenses '.$s['expiring_licenses']];
    foreach(array_slice(array_filter($s['work_rows'],fn($w)=>empty($w['readiness']['ready'])),0,8) as $w)$lines[]='- '.($w['title']??$w['track_id']).' blocked: '.implode('; ',(array)$w['readiness']['blockers']);
    foreach(array_slice(array_filter($s['release_rows'],fn($r)=>empty($r['ready'])),0,6) as $r)$lines[]='- release '.($r['title']??$r['release_id']).' blocked: '.implode('; ',array_slice((array)$r['blockers'],0,4));
    return implode("\n",$lines);
}
