<?php
declare(strict_types=1);

function sf_ticket_json(array $v): string {return json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?:'{}';}
function sf_ticket_decode(mixed $v,array $fallback=[]): array {$d=is_array($v)?$v:json_decode((string)$v,true);return is_array($d)?$d:$fallback;}
function sf_ticket_code(): string {return 'SFV-'.strtoupper(substr(bin2hex(random_bytes(8)),0,12));}
function sf_ticket_slug(string $v,string $fallback='offer'): string {$v=strtolower(trim($v));$v=preg_replace('/[^a-z0-9]+/','-',$v)??'';$v=trim(substr($v,0,120),'-');return $v!==''?$v:$fallback;}

function sf_ticketing_ensure_schema(): void {
    static $done=false;if($done)return;sf_crm_ensure_schema();$pdo=sf_db();$driver=(string)(sf_db_config()['driver']??'');
    if($driver==='sqlite'){
        $pdo->exec("CREATE TABLE IF NOT EXISTS ticket_offers (id INTEGER PRIMARY KEY AUTOINCREMENT,show_id TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,title TEXT NOT NULL,offer_type TEXT NOT NULL DEFAULT 'rsvp',status TEXT NOT NULL DEFAULT 'draft',description TEXT NOT NULL DEFAULT '',fulfillment_type TEXT NOT NULL DEFAULT 'reservation',external_url TEXT NOT NULL DEFAULT '',price_cents INTEGER NOT NULL DEFAULT 0,capacity INTEGER NOT NULL DEFAULT 0,claimed_qty INTEGER NOT NULL DEFAULT 0,max_per_fan INTEGER NOT NULL DEFAULT 1,requires_membership INTEGER NOT NULL DEFAULT 0,minimum_package_id INTEGER NULL,minimum_rank INTEGER NOT NULL DEFAULT 0,requires_vip INTEGER NOT NULL DEFAULT 0,requires_priority_presale INTEGER NOT NULL DEFAULT 0,starts_at TEXT NULL,ends_at TEXT NULL,campaign_id INTEGER NULL,created_by INTEGER NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(minimum_package_id) REFERENCES subscription_packages(id) ON DELETE SET NULL,FOREIGN KEY(campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_ticket_offers_show_status ON ticket_offers(show_id,status,starts_at)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS ticket_reservations (id INTEGER PRIMARY KEY AUTOINCREMENT,offer_id INTEGER NOT NULL,show_id TEXT NOT NULL,user_id INTEGER NOT NULL,contact_id INTEGER NULL,email TEXT NOT NULL,display_name TEXT NOT NULL DEFAULT '',quantity INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'reserved',confirmation_code TEXT NOT NULL UNIQUE,request_key TEXT NOT NULL UNIQUE,source TEXT NOT NULL DEFAULT 'direct',campaign_id INTEGER NULL,reserved_at TEXT NOT NULL,checked_in_at TEXT NULL,cancelled_at TEXT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(offer_id) REFERENCES ticket_offers(id) ON DELETE RESTRICT,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(contact_id) REFERENCES fan_contacts(id) ON DELETE SET NULL,FOREIGN KEY(campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_ticket_reservations_user ON ticket_reservations(user_id,status,reserved_at)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_ticket_reservations_show ON ticket_reservations(show_id,status,reserved_at)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS ticket_events (id INTEGER PRIMARY KEY AUTOINCREMENT,offer_id INTEGER NULL,reservation_id INTEGER NULL,show_id TEXT NOT NULL,event_type TEXT NOT NULL,actor_user_id INTEGER NULL,details_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,FOREIGN KEY(offer_id) REFERENCES ticket_offers(id) ON DELETE SET NULL,FOREIGN KEY(reservation_id) REFERENCES ticket_reservations(id) ON DELETE SET NULL,FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_ticket_events_show_created ON ticket_events(show_id,created_at)");
    }else{
        $pdo->exec("CREATE TABLE IF NOT EXISTS ticket_offers (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,show_id VARCHAR(160) NOT NULL,slug VARCHAR(140) NOT NULL UNIQUE,title VARCHAR(220) NOT NULL,offer_type VARCHAR(32) NOT NULL DEFAULT 'rsvp',status VARCHAR(24) NOT NULL DEFAULT 'draft',description TEXT NOT NULL,fulfillment_type VARCHAR(32) NOT NULL DEFAULT 'reservation',external_url TEXT NOT NULL,price_cents INT NOT NULL DEFAULT 0,capacity INT NOT NULL DEFAULT 0,claimed_qty INT NOT NULL DEFAULT 0,max_per_fan INT NOT NULL DEFAULT 1,requires_membership TINYINT(1) NOT NULL DEFAULT 0,minimum_package_id BIGINT UNSIGNED NULL,minimum_rank INT NOT NULL DEFAULT 0,requires_vip TINYINT(1) NOT NULL DEFAULT 0,requires_priority_presale TINYINT(1) NOT NULL DEFAULT 0,starts_at VARCHAR(40) NULL,ends_at VARCHAR(40) NULL,campaign_id BIGINT UNSIGNED NULL,created_by BIGINT UNSIGNED NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,INDEX idx_ticket_offers_show_status(show_id,status,starts_at),CONSTRAINT fk_ticket_offer_package FOREIGN KEY(minimum_package_id) REFERENCES subscription_packages(id) ON DELETE SET NULL,CONSTRAINT fk_ticket_offer_campaign FOREIGN KEY(campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL,CONSTRAINT fk_ticket_offer_admin FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS ticket_reservations (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,offer_id BIGINT UNSIGNED NOT NULL,show_id VARCHAR(160) NOT NULL,user_id BIGINT UNSIGNED NOT NULL,contact_id BIGINT UNSIGNED NULL,email VARCHAR(190) NOT NULL,display_name VARCHAR(120) NOT NULL DEFAULT '',quantity INT NOT NULL DEFAULT 1,status VARCHAR(24) NOT NULL DEFAULT 'reserved',confirmation_code VARCHAR(40) NOT NULL UNIQUE,request_key VARCHAR(190) NOT NULL UNIQUE,source VARCHAR(80) NOT NULL DEFAULT 'direct',campaign_id BIGINT UNSIGNED NULL,reserved_at VARCHAR(40) NOT NULL,checked_in_at VARCHAR(40) NULL,cancelled_at VARCHAR(40) NULL,created_at VARCHAR(40) NOT NULL,updated_at VARCHAR(40) NOT NULL,INDEX idx_ticket_reservations_user(user_id,status,reserved_at),INDEX idx_ticket_reservations_show(show_id,status,reserved_at),CONSTRAINT fk_ticket_reservation_offer FOREIGN KEY(offer_id) REFERENCES ticket_offers(id) ON DELETE RESTRICT,CONSTRAINT fk_ticket_reservation_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_ticket_reservation_contact FOREIGN KEY(contact_id) REFERENCES fan_contacts(id) ON DELETE SET NULL,CONSTRAINT fk_ticket_reservation_campaign FOREIGN KEY(campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $pdo->exec("CREATE TABLE IF NOT EXISTS ticket_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,offer_id BIGINT UNSIGNED NULL,reservation_id BIGINT UNSIGNED NULL,show_id VARCHAR(160) NOT NULL,event_type VARCHAR(80) NOT NULL,actor_user_id BIGINT UNSIGNED NULL,details_json LONGTEXT NOT NULL,created_at VARCHAR(40) NOT NULL,INDEX idx_ticket_events_show_created(show_id,created_at),CONSTRAINT fk_ticket_event_offer FOREIGN KEY(offer_id) REFERENCES ticket_offers(id) ON DELETE SET NULL,CONSTRAINT fk_ticket_event_reservation FOREIGN KEY(reservation_id) REFERENCES ticket_reservations(id) ON DELETE SET NULL,CONSTRAINT fk_ticket_event_actor FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    }$done=true;
}
function sf_ticket_show(string $id): ?array {foreach(sf_live_shows() as $s)if((string)($s['id']??'')===$id)return $s;return null;}
function sf_ticket_log(string $event,string $showId,?int $offerId=null,?int $reservationId=null,?int $actorUserId=null,array $details=[]): int {
    sf_ticketing_ensure_schema();$q=sf_db()->prepare('INSERT INTO ticket_events(offer_id,reservation_id,show_id,event_type,actor_user_id,details_json,created_at) VALUES(?,?,?,?,?,?,?)');$q->execute([$offerId,$reservationId,$showId,sf_clean_text($event,80),$actorUserId?:null,sf_ticket_json($details),gmdate('c')]);return (int)sf_db()->lastInsertId();
}
function sf_ticket_offer(int|string $id): ?array {
    sf_ticketing_ensure_schema();$col=is_int($id)||ctype_digit((string)$id)?'id':'slug';$q=sf_db()->prepare("SELECT * FROM ticket_offers WHERE $col=? LIMIT 1");$q->execute([$id]);$r=$q->fetch();if(!$r)return null;$r['show']=sf_ticket_show((string)$r['show_id']);return $r;
}
function sf_ticket_offer_save(array $raw,int $adminId): array {
    sf_ticketing_ensure_schema();$id=max(0,(int)($raw['id']??0));$showId=sf_clean_text($raw['show_id']??'',160);$show=sf_ticket_show($showId);if(!$show)throw new InvalidArgumentException('Choose a valid Stonefellow show.');$title=sf_clean_text($raw['title']??'',220);if($title==='')throw new InvalidArgumentException('Offer title is required.');$slug=sf_ticket_slug((string)($raw['slug']??$title),$showId.'-offer');$type=(string)($raw['offer_type']??'rsvp');if(!in_array($type,['rsvp','ticket','vip','meet_greet','presale'],true))throw new InvalidArgumentException('Invalid ticket offer type.');$status=(string)($raw['status']??'draft');if(!in_array($status,['draft','published','paused','closed','archived'],true))throw new InvalidArgumentException('Invalid offer status.');$fulfillment=(string)($raw['fulfillment_type']??'reservation');if(!in_array($fulfillment,['reservation','external'],true))throw new InvalidArgumentException('Invalid fulfillment type.');$external=sf_clean_text($raw['external_url']??'',1200);$price=max(0,(int)($raw['price_cents']??0));if($fulfillment==='external'&&!filter_var($external,FILTER_VALIDATE_URL))throw new InvalidArgumentException('External ticket offers require a valid URL.');if($price>0&&$fulfillment!=='external')throw new InvalidArgumentException('Paid ticket offers require external checkout. Stonefellow internal reservations are free.');$capacity=max(0,(int)($raw['capacity']??0));$maxPer=max(1,min(20,(int)($raw['max_per_fan']??1)));$pkg=max(0,(int)($raw['minimum_package_id']??0))?:null;$rank=max(0,(int)($raw['minimum_rank']??0));if($pkg){$p=sf_package($pkg);if(!$p)throw new InvalidArgumentException('Minimum membership tier not found.');$rank=max($rank,(int)($p['membership_rank']??0));}$starts=sf_clean_text($raw['starts_at']??'',40)?:null;$ends=sf_clean_text($raw['ends_at']??'',40)?:null;if($starts&&strtotime($starts)===false)throw new InvalidArgumentException('Offer start time is invalid.');if($ends&&strtotime($ends)===false)throw new InvalidArgumentException('Offer end time is invalid.');if($starts&&$ends&&strtotime($ends)<=strtotime($starts))throw new InvalidArgumentException('Offer end must be after its start.');$campaign=max(0,(int)($raw['campaign_id']??0))?:null;if($campaign&&function_exists('sf_campaign_get')&&!sf_campaign_get($campaign))throw new InvalidArgumentException('Campaign not found.');$requiresMembership=!empty($raw['requires_membership'])||$pkg||$rank>0||!empty($raw['requires_vip'])||!empty($raw['requires_priority_presale']);$now=gmdate('c');
    $fields=[$showId,$slug,$title,$type,$status,sf_clean_text($raw['description']??'',8000),$fulfillment,$external,$price,$capacity,$maxPer,$requiresMembership?1:0,$pkg,$rank,!empty($raw['requires_vip'])?1:0,!empty($raw['requires_priority_presale'])?1:0,$starts,$ends,$campaign,$now];
    try{if($id){$q=sf_db()->prepare('UPDATE ticket_offers SET show_id=?,slug=?,title=?,offer_type=?,status=?,description=?,fulfillment_type=?,external_url=?,price_cents=?,capacity=?,max_per_fan=?,requires_membership=?,minimum_package_id=?,minimum_rank=?,requires_vip=?,requires_priority_presale=?,starts_at=?,ends_at=?,campaign_id=?,updated_at=? WHERE id=?');$q->execute([...$fields,$id]);if(!$q->rowCount()&&!sf_ticket_offer($id))throw new InvalidArgumentException('Ticket offer not found.');}else{$q=sf_db()->prepare('INSERT INTO ticket_offers(show_id,slug,title,offer_type,status,description,fulfillment_type,external_url,price_cents,capacity,claimed_qty,max_per_fan,requires_membership,minimum_package_id,minimum_rank,requires_vip,requires_priority_presale,starts_at,ends_at,campaign_id,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,0,?,?,?,?,?,?,?,?,?,?,?,?)');$q->execute([$showId,$slug,$title,$type,$status,$fields[5],$fulfillment,$external,$price,$capacity,$maxPer,$requiresMembership?1:0,$pkg,$rank,!empty($raw['requires_vip'])?1:0,!empty($raw['requires_priority_presale'])?1:0,$starts,$ends,$campaign,$adminId?:null,$now,$now]);$id=(int)sf_db()->lastInsertId();}}catch(PDOException $e){if(in_array((string)$e->getCode(),['23000','19'],true))throw new InvalidArgumentException('Ticket offer slug must be unique.');throw $e;}return sf_ticket_offer($id)?:[];
}
function sf_ticket_access(array $offer,?int $userId): array {
    $now=time();$starts=(string)($offer['starts_at']??'');$ends=(string)($offer['ends_at']??'');$state=$userId&&function_exists('sf_membership_state')?sf_membership_state($userId,false):['active'=>false,'rank'=>0,'package_id'=>0,'benefits'=>[]];$benefits=(array)($state['benefits']??[]);$reason='available';$allowed=true;$presale=false;
    if(($offer['status']??'')!=='published'){$allowed=false;$reason='not_published';}
    if($allowed&&$ends!==''&&strtotime($ends)<$now){$allowed=false;$reason='closed';}
    if($allowed&&$starts!==''&&strtotime($starts)>$now){$earlyDays=max(0,(int)($benefits['early_access_days']??0));$presale=!empty($state['active'])&&!empty($benefits['priority_presale'])&&$earlyDays>0&&strtotime($starts)<=($now+$earlyDays*86400);if(!$presale){$allowed=false;$reason='not_open';}else$reason='member_presale';}
    if($allowed&&!empty($offer['requires_membership'])&&empty($state['active'])){$allowed=false;$reason='membership_required';}
    if($allowed&&(int)($offer['minimum_rank']??0)>0&&(int)($state['rank']??0)<(int)$offer['minimum_rank']){$allowed=false;$reason='higher_tier_required';}
    if($allowed&&!empty($offer['minimum_package_id'])){$p=sf_package((int)$offer['minimum_package_id']);$need=(int)($p['membership_rank']??0);if(empty($state['active'])||(int)($state['rank']??0)<$need){$allowed=false;$reason='higher_tier_required';}}
    if($allowed&&!empty($offer['requires_vip'])&&empty($benefits['vip_access'])){$allowed=false;$reason='vip_required';}
    if($allowed&&!empty($offer['requires_priority_presale'])&&empty($benefits['priority_presale'])){$allowed=false;$reason='presale_required';}
    $remaining=(int)$offer['capacity']>0?max(0,(int)$offer['capacity']-(int)$offer['claimed_qty']):null;if($allowed&&$remaining!==null&&$remaining<=0){$allowed=false;$reason='sold_out';}
    if($allowed&&($offer['fulfillment_type']??'reservation')==='reservation'&&!$userId){$allowed=false;$reason='sign_in_required';}
    return ['allowed'=>$allowed,'reason'=>$reason,'presale'=>$presale,'remaining'=>$remaining,'membership'=>$state];
}
function sf_ticket_public_offer(array $offer,?int $userId): array {
    $a=sf_ticket_access($offer,$userId);$show=$offer['show']??sf_ticket_show((string)$offer['show_id']);return ['id'=>(int)$offer['id'],'slug'=>(string)$offer['slug'],'show_id'=>(string)$offer['show_id'],'show_title'=>(string)($show['title']??$show['venue']??$offer['show_id']),'show_date'=>(string)($show['date']??''),'venue'=>(string)($show['venue']??''),'location'=>$show?sf_live_location($show):'','title'=>(string)$offer['title'],'offer_type'=>(string)$offer['offer_type'],'description'=>(string)$offer['description'],'fulfillment_type'=>(string)$offer['fulfillment_type'],'external_url'=>$a['allowed']?(string)$offer['external_url']:'','price_cents'=>(int)$offer['price_cents'],'capacity'=>(int)$offer['capacity'],'claimed_qty'=>(int)$offer['claimed_qty'],'max_per_fan'=>(int)$offer['max_per_fan'],'requires_membership'=>!empty($offer['requires_membership']),'minimum_package_id'=>(int)($offer['minimum_package_id']??0),'minimum_rank'=>(int)$offer['minimum_rank'],'requires_vip'=>!empty($offer['requires_vip']),'requires_priority_presale'=>!empty($offer['requires_priority_presale']),'starts_at'=>$offer['starts_at'],'ends_at'=>$offer['ends_at'],'access'=>$a];
}
function sf_ticket_public_offers(?int $userId=null,string $showId=''): array {
    sf_ticketing_ensure_schema();$sql="SELECT * FROM ticket_offers WHERE status='published'";$args=[];if($showId!==''){$sql.=' AND show_id=?';$args[]=$showId;}$sql.=' ORDER BY COALESCE(starts_at,created_at),id';$q=sf_db()->prepare($sql);$q->execute($args);$rows=[];foreach($q->fetchAll() as $r){$r['show']=sf_ticket_show((string)$r['show_id']);if(!$r['show']||($r['show']['public_visible']??true)===false)continue;$rows[]=sf_ticket_public_offer($r,$userId);}return $rows;
}
function sf_ticket_reservations_for_user(int $userId): array {sf_ticketing_ensure_schema();$q=sf_db()->prepare('SELECT r.*,o.title offer_title,o.offer_type,o.fulfillment_type FROM ticket_reservations r JOIN ticket_offers o ON o.id=r.offer_id WHERE r.user_id=? ORDER BY r.id DESC');$q->execute([$userId]);$rows=$q->fetchAll();foreach($rows as &$r)$r['show']=sf_ticket_show((string)$r['show_id']);unset($r);return $rows;}
function sf_ticket_reserve(int $offerId,int $userId,int $qty,string $requestKey,string $source='direct'): array {
    sf_ticketing_ensure_schema();$qty=max(1,min(20,$qty));$requestKey=sf_clean_text($requestKey,190);if($requestKey==='')throw new InvalidArgumentException('Reservation request key is required.');$pdo=sf_db();$existing=$pdo->prepare('SELECT * FROM ticket_reservations WHERE request_key=?');$existing->execute([$requestKey]);if($r=$existing->fetch()){if((int)$r['user_id']!==$userId)throw new RuntimeException('Reservation request key conflict.');return $r;}
    $uQ=$pdo->prepare('SELECT id,email,display_name FROM users WHERE id=? AND status=?');$uQ->execute([$userId,'active']);$user=$uQ->fetch();if(!$user)throw new InvalidArgumentException('Active Stonefellow account required.');$contact=sf_crm_sync_user($userId);if(!$contact)throw new RuntimeException('Could not resolve fan CRM identity.');$offer=sf_ticket_offer($offerId);if(!$offer)throw new InvalidArgumentException('Ticket offer not found.');$access=sf_ticket_access($offer,$userId);if(!$access['allowed'])throw new RuntimeException('This offer is not available: '.$access['reason'].'.');if(($offer['fulfillment_type']??'reservation')!=='reservation')throw new InvalidArgumentException('This offer uses external ticketing.');
    $now=gmdate('c');$pdo->beginTransaction();try{
        $lockSql='SELECT * FROM ticket_offers WHERE id=?'.(((string)(sf_db_config()['driver']??''))==='mysql'?' FOR UPDATE':'');$lock=$pdo->prepare($lockSql);$lock->execute([$offerId]);$current=$lock->fetch();if(!$current||($current['status']??'')!=='published')throw new RuntimeException('This offer is no longer available.');
        $mine=$pdo->prepare("SELECT COALESCE(SUM(quantity),0) FROM ticket_reservations WHERE offer_id=? AND user_id=? AND status IN ('reserved','checked_in')");$mine->execute([$offerId,$userId]);$already=(int)$mine->fetchColumn();if($already+$qty>(int)$current['max_per_fan'])throw new RuntimeException('This reservation exceeds the per-fan limit.');
        if((int)$current['capacity']>0){$up=$pdo->prepare("UPDATE ticket_offers SET claimed_qty=claimed_qty+?,updated_at=? WHERE id=? AND status='published' AND claimed_qty+?<=capacity");$up->execute([$qty,$now,$offerId,$qty]);if($up->rowCount()!==1)throw new RuntimeException('This offer no longer has enough capacity.');}else{$pdo->prepare('UPDATE ticket_offers SET claimed_qty=claimed_qty+?,updated_at=? WHERE id=?')->execute([$qty,$now,$offerId]);}
        $code=sf_ticket_code();$campaign=(int)($current['campaign_id']??0)?:null;$q=$pdo->prepare("INSERT INTO ticket_reservations(offer_id,show_id,user_id,contact_id,email,display_name,quantity,status,confirmation_code,request_key,source,campaign_id,reserved_at,checked_in_at,cancelled_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'reserved',?,?,?,?,?,NULL,NULL,?,?)");$q->execute([$offerId,(string)$current['show_id'],$userId,(int)$contact['id'],(string)$user['email'],(string)$user['display_name'],$qty,$code,$requestKey,sf_clean_text($source,80),$campaign,$now,$now,$now]);$rid=(int)$pdo->lastInsertId();$pdo->commit();$offer=array_merge($offer,$current);
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    sf_ticket_log('reserved',(string)$offer['show_id'],$offerId,$rid,$userId,['quantity'=>$qty,'source'=>$source]);$event=($offer['offer_type']??'')==='vip'?'vip_reserved':'ticket_reserved';sf_crm_log_event((int)$contact['id'],$userId,$event,'Reserved '.$offer['title'],'show',(string)$offer['show_id'],['offer_id'=>$offerId,'offer_type'=>$offer['offer_type'],'quantity'=>$qty,'confirmation_code'=>$code]);if(function_exists('sf_notify_user'))sf_notify_user($userId,'show','Reservation confirmed: '.$offer['title'],'Confirmation '.$code.'. '.($offer['show']['venue']??''),'?view=tickets');$q=$pdo->prepare('SELECT * FROM ticket_reservations WHERE id=?');$q->execute([$rid]);return $q->fetch()?:[];
}
function sf_ticket_cancel(int $reservationId,int $userId,bool $admin=false): array {
    sf_ticketing_ensure_schema();$pdo=sf_db();$q=$pdo->prepare('SELECT r.*,o.title offer_title,o.offer_type FROM ticket_reservations r JOIN ticket_offers o ON o.id=r.offer_id WHERE r.id=?');$q->execute([$reservationId]);$r=$q->fetch();if(!$r)throw new InvalidArgumentException('Reservation not found.');if(!$admin&&(int)$r['user_id']!==$userId)throw new RuntimeException('You cannot cancel this reservation.');if($r['status']==='cancelled')return $r;if($r['status']==='checked_in')throw new RuntimeException('A checked-in reservation cannot be cancelled.');$now=gmdate('c');$pdo->beginTransaction();try{$u=$pdo->prepare("UPDATE ticket_reservations SET status='cancelled',cancelled_at=?,updated_at=? WHERE id=? AND status='reserved'");$u->execute([$now,$now,$reservationId]);if($u->rowCount()===1)$pdo->prepare('UPDATE ticket_offers SET claimed_qty=CASE WHEN claimed_qty>=? THEN claimed_qty-? ELSE 0 END,updated_at=? WHERE id=?')->execute([(int)$r['quantity'],(int)$r['quantity'],$now,(int)$r['offer_id']]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}if($u->rowCount()===1){sf_ticket_log('cancelled',(string)$r['show_id'],(int)$r['offer_id'],$reservationId,$userId,['quantity'=>(int)$r['quantity'],'admin'=>$admin]);if(!empty($r['contact_id']))sf_crm_log_event((int)$r['contact_id'],(int)$r['user_id'],'ticket_cancelled','Cancelled '.$r['offer_title'],'show',(string)$r['show_id'],['offer_id'=>(int)$r['offer_id'],'quantity'=>(int)$r['quantity']]);}$q=$pdo->prepare('SELECT * FROM ticket_reservations WHERE id=?');$q->execute([$reservationId]);return $q->fetch()?:$r;
}
function sf_ticket_check_in(int $reservationId,int $adminUserId): array {
    sf_ticketing_ensure_schema();$pdo=sf_db();$q=$pdo->prepare('SELECT r.*,o.title offer_title,o.offer_type FROM ticket_reservations r JOIN ticket_offers o ON o.id=r.offer_id WHERE r.id=?');$q->execute([$reservationId]);$r=$q->fetch();if(!$r)throw new InvalidArgumentException('Reservation not found.');if($r['status']==='checked_in')return $r;if($r['status']!=='reserved')throw new RuntimeException('Only reserved guests can check in.');$now=gmdate('c');$u=$pdo->prepare("UPDATE ticket_reservations SET status='checked_in',checked_in_at=?,updated_at=? WHERE id=? AND status='reserved'");$u->execute([$now,$now,$reservationId]);if($u->rowCount()===1){sf_ticket_log('checked_in',(string)$r['show_id'],(int)$r['offer_id'],$reservationId,$adminUserId,['quantity'=>(int)$r['quantity']]);if(!empty($r['contact_id']))sf_crm_log_event((int)$r['contact_id'],(int)$r['user_id'],'guest_checked_in','Checked in: '.$r['offer_title'],'show',(string)$r['show_id'],['offer_id'=>(int)$r['offer_id'],'quantity'=>(int)$r['quantity']]);}$q=$pdo->prepare('SELECT * FROM ticket_reservations WHERE id=?');$q->execute([$reservationId]);return $q->fetch()?:$r;
}
function sf_ticket_check_in_code(string $code,int $adminUserId): array {$q=sf_db()->prepare('SELECT id FROM ticket_reservations WHERE confirmation_code=?');$q->execute([strtoupper(sf_clean_text($code,40))]);$id=(int)($q->fetchColumn()?:0);if(!$id)throw new InvalidArgumentException('Confirmation code not found.');return sf_ticket_check_in($id,$adminUserId);}
function sf_ticket_guest_list(string $showId='',int $offerId=0): array {
    sf_ticketing_ensure_schema();$where=['1=1'];$args=[];if($showId!==''){$where[]='r.show_id=?';$args[]=$showId;}if($offerId>0){$where[]='r.offer_id=?';$args[]=$offerId;}$sql='SELECT r.*,o.title offer_title,o.offer_type FROM ticket_reservations r JOIN ticket_offers o ON o.id=r.offer_id WHERE '.implode(' AND ',$where).' ORDER BY r.reserved_at DESC,r.id DESC LIMIT 2000';$q=sf_db()->prepare($sql);$q->execute($args);$rows=$q->fetchAll();foreach($rows as &$r)$r['show']=sf_ticket_show((string)$r['show_id']);unset($r);return $rows;
}
function sf_ticket_summary(): array {
    sf_ticketing_ensure_schema();$pdo=sf_db();$q=$pdo->query("SELECT COUNT(*) offers,SUM(CASE WHEN status='published' THEN 1 ELSE 0 END) published,COALESCE(SUM(claimed_qty),0) claimed FROM ticket_offers");$o=$q->fetch()?:[];$q=$pdo->query("SELECT COUNT(*) reservations,COALESCE(SUM(CASE WHEN status IN ('reserved','checked_in') THEN quantity ELSE 0 END),0) reserved_qty,COALESCE(SUM(CASE WHEN status='checked_in' THEN quantity ELSE 0 END),0) checked_in_qty FROM ticket_reservations");$r=$q->fetch()?:[];$q=$pdo->query("SELECT COUNT(*) FROM ticket_reservations r JOIN ticket_offers o ON o.id=r.offer_id WHERE o.offer_type IN ('vip','meet_greet') AND r.status IN ('reserved','checked_in')");$vip=(int)$q->fetchColumn();return ['offers'=>(int)($o['offers']??0),'published'=>(int)($o['published']??0),'claimed_qty'=>(int)($o['claimed']??0),'reservations'=>(int)($r['reservations']??0),'reserved_qty'=>(int)($r['reserved_qty']??0),'checked_in_qty'=>(int)($r['checked_in_qty']??0),'vip_reservations'=>$vip];
}
function sf_ticket_admin_offers(): array {sf_ticketing_ensure_schema();$rows=sf_db()->query('SELECT * FROM ticket_offers ORDER BY id DESC LIMIT 500')->fetchAll();foreach($rows as &$r){$r['show']=sf_ticket_show((string)$r['show_id']);$r['access']=sf_ticket_access($r,null);}unset($r);return $rows;}
function sf_ticket_agent_context(?int $userId=null): string {
    $offers=sf_ticket_public_offers($userId);$lines=['TICKETS + VIP'];foreach(array_slice($offers,0,12) as $o)$lines[]='- offer '.$o['title'].' | '.$o['show_date'].' | '.$o['venue'].' | '.$o['offer_type'].' | '.($o['access']['allowed']?'available':$o['access']['reason']).($o['access']['remaining']!==null?' | '.$o['access']['remaining'].' remaining':'');if($userId){foreach(array_slice(sf_ticket_reservations_for_user($userId),0,8) as $r)$lines[]='- my reservation '.$r['confirmation_code'].' | '.$r['offer_title'].' | '.$r['status'].' | qty '.$r['quantity'];}return implode("\n",$lines);
}
